### ISSUE TITLE
Selenium-based bots are not completing questionnaire

### ISSUE THREAD

**Issue by davisagli** [Dallinger/Dallinger#1003]
Bots using BotBase (such as the bartlett1932 bots) are not successfully completing the questionnaire. My guess is that this is because the questionnaire was modified to validate that an answer was actually provided, and the bot is not actually trying to fill out the answers.

**Comment by cguardia** [comment]
Finally made a PR for this fix: https://github.com/Dallinger/Dallinger/pull/1101
