### ISSUE TITLE
Codecov tests remain incomplete

### ISSUE THREAD

**Issue by vlall** [Dallinger/Dallinger#1024]
Code coverage tests (codecov/patch and codecov/project) remain in a "working" state but never full complete. This happened for a number of PRs this past week. The content of the PR does not seem to effect the status of this completing, and the PRs have been rebuilt multiple times. 

This could an external problem with codecov

**Comment by davisagli** [comment]
Did the other tests complete successfully? I think the travis run only reports coverage to codecov if the run was successful.
