### ISSUE TITLE
config.write() omits unintended keys

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#1079]
## Expected Behavior
If `config.write()` is called with `filter_sensitive=False`, all keys should be written to the new config.txt output file.

## Current Behavior
Keys with substrings in the `SENSITIVE_KEY_NAMES` list are omitted from the resulting file.

## Steps to Reproduce (for bugs)
1. `dallinger sandbox --verbose` with a sensitive key set in .dallignerconfig
2. observer config.txt file written to be `git commit`ed to heroku

**Comment by alecpm** [comment]
Closing, since this PR is merged.
