### ISSUE TITLE
Ubuntu installation documentation not quite right

### ISSUE THREAD

**Issue by jcpeterson** [Dallinger/Dallinger#1099]
The documentation recommends:
`sudo apt-get update && apt-get install -y postgresql postgresql-contrib`
This doesn't run, giving a complaint about having root.

Instead, I was successful with:
`sudo apt-get update && sudo apt-get install -y postgresql postgresql-contrib`

**Comment by jcpeterson** [comment]
Looks like the rest of the documentation doesn't quite work anymore either, at least for ubuntu 18.04.

Firstly, these five lines wouldn't run without sudo:

```
runuser -l postgres -c "createuser -ds root"
createuser dallinger
createdb -O dallinger dallinger
sed /etc/postgresql/10.3/main/pg_hba.conf -e 's/md5/trust/g' --in-place
sed -e "s/[#]\?listen_addresses = .*/listen_addresses = '*'/g" -i '/etc/postgresql/10.3/main/postgresql.conf'
```
Also, the postgres version folder is no longer as detailed. The current newest for ubuntu is 10.4, but the folder was '10'. The instructions should say to use ls `/etc/postgresql` instead of `psql --version` to make sure one finds the right path name.


Next,

**Comment by witekdev** [comment]
@jcpeterson I was installing on Ubuntu 16.04 and made notes as I went through the process, perhaps they will be helpful: https://github.com/Dallinger/Dallinger/issues/999

**Comment by jcpeterson** [comment]
Thanks @witekdev. I'll look through this more, but so far it's pretty confusing :/

It would be nice if the documentation gave a description of what needs to happen to use postgres rather than pasting the lines that worked at one point. The sed lines are straightforward. It's also not clear to me if things act differently when using sudo versus not. For example, I get a fatal error like you mention when not using sudo, but don't get it when I use sudo...

**Comment by witekdev** [comment]
@jcpeterson 
I agree, there is active effort currently to improve and expand the docs and create examples and api references. Hopefully soon any new comers to dallinger will have a much easier time getting started and using the project.

**Comment by witekdev** [comment]
@jcpeterson the documentation has been updated for Ubuntu. I tested on various versions, let us know if you run into other issues or feedback. Thanks!

**Comment by jcpeterson** [comment]
Thanks a lot, I really appreciate it. I'll try working through this a bit later and get back if I have any issues. Hopefully things go smoothly.
