### ISSUE TITLE
Qualification blacklist does not support more than 10 qualification names

### ISSUE THREAD

**Issue by eamonnbell** [Dallinger/Dallinger#1107]
## Expected Behavior

Given more than 10 qualification names in `qualification_blacklist`, Dallinger should fail gracefully or batch `boto` calls to overcome that limitation 

## Current Behavior

App builds and deploys but fails to launch

## Steps to Reproduce (for bugs)
1. add 10 or more qualification names to `qualification_blacklist`
2. dallinger sandbox --verbose
3. application builds and pushes but fails to launch
4. initial recruitment fails because this assertion does not pass

https://github.com/boto/boto/blob/abb38474ee5124bb571da0c42be67cd27c47094f/boto/mturk/qualification.py#L34

## Context
Blacklisting is a very useful feature, it should support arbitrary numbers of qualifications. I am not sure if this is an MTurk limitation or a boto limitation. If not an MTurk limitation, then Dallinger should partition the names in `qualification_blacklist` over successive API calls so this limitation in its dependency is avoided.

## Your Environment
* Dallinger version used: 3.4.1
* Operating System and version (desktop or mobile): Linux XXXX 4.12.6-1-ARCH #1 SMP PREEMPT Sat Aug 12 09:16:22 CEST 2017 x86_64 GNU/Linux
* Browser and version (e.g. Chrome 39, node.js 5.4): n/a
* Link to your project: n/a

**Comment by jessesnyder** [comment]
@eamonnbell I've confirmed that it *is* the version of the boto library used in versions of Dallinger prior to 4.0.0 which creates this limitation. Is upgrading Dallinger an option for you? Time might be better spent helping you get past upgrade hurdles rather than creating a workaround for the old boto library.

Cheers,
-Jesse

**Comment by eamonnbell** [comment]
Thanks for the update. In June there were good reasons to stay at 3.x but I have forgotten what they were...

**Comment by jessesnyder** [comment]
Closing this for now, as there is support for arbitrary blacklist sizes in Dallinger 4.X.
