### ISSUE TITLE
Restructuring documentation? New documentation theme?

### ISSUE THREAD

**Issue by vlall** [Dallinger/Dallinger#1145]
Documentation can get somewhat overwhelming in its current format. Perhaps some sort of restructuring next iteration can help with this. Maybe even using a new theme as I can see some drawback with the current theme. 

One problem with the current theme is that that the table of contents disappears after you click on a link. This is different from other documentation themes where you have a table of contents that stays accessible in a left div. Here's an example of a theme that might be less confusing:
https://sphinx-rtd-theme.readthedocs.io/en/latest/demo/structure.html

**Comment by witekdev** [comment]
Probably also relevant to consider this issue https://github.com/Dallinger/Dallinger/issues/341 as we look how we restructure the docs.
