### ISSUE TITLE
Give immediate visual feedback when a UI button is pressed

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#116]
## Expected Behavior

When a button is pressed, it gives immediate visual feedback that the press has been registered.
## Current Behavior

It gives no indication until the action (e.g., web request) completes.

**Comment by suchow** [comment]
This particularly refers to UI buttons during consent, instructions, submitting the final questionnaire, etc.

**Comment by jessesnyder** [comment]
@suchow I started down the path of incorporating a method for freezing form inputs and showing a spinner into dallinger itself, but the dallinger front-end parts really aren't set up to be extended at this point, so I'm going to back all that out and leave everything in GU for now.

Longer term, it seems that common scenarios like this (UI for forms which may take a while to process) should be supported by the framework in the same what that using the waiting room system is. Having some base template in dallinger which could be extended by experiment templates would help with this (similar to layout.html in GU).

**Comment by jessesnyder** [comment]
Closing based on 7/20 merge
