### ISSUE TITLE
Automatic pycodestyle updates break flake8

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#1164]
We are pinned to the latest version of flake8 (3.5.0), which is incompatible with the latest pycodestyle (2.4.0). Pyupbot repeatedly pushes us into upgrading pycodestyle and re-breaking things.

**Comment by vlall** [comment]
I'm wondering how this works with the constraints.txt PR that we have (do we put the filter in the constraints.txt file?)

**Comment by alecpm** [comment]
@vlall It should work, see my comment on the constraints PR.
