### ISSUE TITLE
yarn missing from documentation

### ISSUE THREAD

**Issue by witekdev** [Dallinger/Dallinger#1228]
It looks like yarn is now required to build the documentation: https://github.com/Dallinger/Dallinger/commit/5bb360293276e298abd36bcbc2f3b98cba26454e

However, it is not included as a requirements in the developer documentation.

## Expected Behavior
Running ``` tox -e docs ``` should build the docs

## Current Behavior
```
docs runtests: commands[1] | yarn
ERROR: InvocationError for command could not find executable 'yarn'
___________________________________________________________________________________________ summary ___________________________________________________________________________________________
ERROR:   docs: commands failed
```

## Your Environment
Ubuntu 16.04

We need to update the documentation to include:
https://yarnpkg.com/lang/en/docs/install/#debian-stable
and
https://yarnpkg.com/lang/en/docs/install/#mac-stable

**Comment by alecpm** [comment]
`yarn` is required (though `npm` would also be fine), but it is not installable via a requirements file. See:

https://yarnpkg.com/lang/en/docs/install/

I guess this needs to be added to the contributing to Dallinger docs. Though now I'm confused why the Travis/tox builds have been succeeding.

**Comment by witekdev** [comment]
@alecpm yeah, I realized it's not installable via requirements file when I tried to install it just now. 
Issue updated.
