### ISSUE TITLE
Use the word Experiment as opposed to Experimental

### ISSUE THREAD

**Issue by witekdev** [Dallinger/Dallinger#1237]
I find the use of  ``` Experimental design ``` and ``` Required Experimental Files ``` in the **Learning to use Dallinger** section: http://docs.dallinger.io/en/latest/learning_to_use_dallinger.html potentially confusing, since we are talking about designing a Dallinger Experiment?

Propose to change it to "Experiment"

**Comment by witekdev** [comment]
@vlall your thoughts?

**Comment by vlall** [comment]
Experimental is confusing, it implies you're experimenting building experiments, but here we're really just talking about experiments.
