### ISSUE TITLE
The participant `recruiter_id` doesn't reflect the actual recruiter used

### ISSUE THREAD

**Issue by alecpm** [Dallinger/Dallinger#1367]
## Expected Behavior
When using the `multi` recruiter the Participant's `recruiter_id` value should be set to the value of the actual recruiter used as included in the ad's `recruiter` url parameter.

## Current Behavior
Participants all have `recruiter_id` set to `multi` which is not generally useful information.

## Steps to Reproduce (for bugs)
1. Set config to use recruiter `multi`
2. Run experiment
3. Observe `recruiter_id` values for Participants

## Context
The UPenn team needs to be able to distinguish between bots and human participants in data analysis and when determining bot behavior. The current behavior doesn't provide a good mechanism for determining which users are human in a `multi` recruiter experiment.

We pass the correct recruiter name to the ad, but unlike other ad variables we don't save it and include it in request to create a participant.

## Your Environment
* Dallinger version used: 4.0.0/master

**Comment by alecpm** [comment]
This turned out to be an issue specific to the `HighPerformanceBotBase` class. The default templates + JS sends the proper recruiter, so participants with browsers (humans and selenium bots) would have recruiters set correctly. The PR above makes the `HighPerformanceBotBase.sign_up()` method set a custom recruiter that includes the bot class name.

**Comment by jessesnyder** [comment]
Merged - closing.
