### ISSUE TITLE
Dallinger commands consume huge amounts of storage in some cases

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#1710]
Reported by @thomasmorgan while working with Lotty Brand.

This may be simply do to the fact that we copy anything in the experiment directory that doesn't match and exclude pattern, or it may be something more insidious.

## Expected Behavior
Running `dallinger` commands should increase general storage usage by only a small amount, corresponding to the size of the python, html, and JS files required to run the experiment.

## Current Behavior
Files that happen to be in the experiment directory are copied to the experiment temp directory even if they're unrelated to experiment execution.

Storage consumption can increase dramatically.

## Steps to Reproduce (for bugs)
1. Put an arbitrary file in the experiment directory
2. Run `dallinger debug`
3. Check contents of the exported temp directory

## Context
Experiment authors can run out of disk space while performing basic Dallinger tasks.

**Comment by vlall** [comment]
This should be fixed by #1713
