### ISSUE TITLE
dallinger debug errors in experiment.py show up too late -- 2 points

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#1885]
If there are *any* problem in experiment.py they don't show up as errors unless you wait for two minutes!!!

Running "dallinger debug --verbose"
You get this:
❯❯ Experiment launch failed. Trying again (attempt 2 of 4) in 10 seconds ...
and then all four attempts happens, only than an error massage appears- this is almost impossible to debug since it takes for ever to see any issue with experiment.py (for example wrong class name)

The problem comes from
deployment.py
This is hardcoded into it "MAX_ATTEMPTS = 4"
One option is to change it to: "MAX_ATTEMPTS = 1"

Alternatively change the try except scheme so the error massage is showing right after every attempt (rather than in the end after all 4 attempts finished)

**Comment by pmcharrison** [comment]
Maybe this could become an option in `config.txt`?

**Comment by jacobyn** [comment]
I think this should be only in the deploy/sandbox, I can't see why one need it in debug mode. The idea of this to make the experiment more robust to failuere in lunching, this is not an issue in denug mode.

**Comment by alecpm** [comment]
Merged.
