### ISSUE TITLE
Choosing Python version on Heroku -- 2 points

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2032]
It should be possible to specify in the config file (or similar) what version of Python we want to use on Heroku.

**Comment by jessesnyder** [comment]
@pmcharrison @jacobyn @MatthewWilkes  Heroku expects a string like `python-3.6.6` to set the python version. Which feels more natural to include in your config.txt file for the new key `heroku_python_version`:
1. `python-3.6.6`
2. `3.6.6`

Either is equally easy; just trying to figure out what someone is more likely to do without consulting the docs.

**Comment by MatthewWilkes** [comment]
I vote for 2
