### ISSUE TITLE
Documentation: how to deploy with a dependency on a private Git repository

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2036]
We have been deploying experiments that depend on private Git repositories by adding lines like the following to requirements.txt:

-e git+https://pmcharrison:<password>@gitlab.com/computational-audition-lab/dlgr-monitor#egg=dlgr_monitor

However, this involves hard-coding the GitLab password into requirements.txt. Is there a better way?

**Comment by skleinfeldt** [comment]
Large number of points because we need to research, discuss, and settle on a solution.

**Comment by pmcharrison** [comment]
It seems really easy to add an SSH key to Heroku - https://devcenter.heroku.com/articles/keys#adding-keys-to-heroku - and from what I understand, this is manual step that has to be done just once per Heroku account, right? Then the repository can be linked to via requirements.txt as normal.

**Comment by jacobyn** [comment]
The number of points here should be changed considering that this seems to be a minor issue.

**Comment by skleinfeldt** [comment]
We are removing this from the Jazkarta iteration and assigning it to @pmcharrison to add the information he discovered to the Dallinger documentation. @jessesnyder will assist with information about how to do that.

**Comment by jessesnyder** [comment]
New docs are here:
https://github.com/Dallinger/Dallinger/pull/2071/files

**Comment by pmcharrison** [comment]
@jessesnyder, do I need to do something to make sure this reaches PR review? I'm aware that it's not in the Iteration 2 board.

**Comment by jessesnyder** [comment]
@pmcharrison It's already merged and in Dallinger 6.0.0!

**Comment by jessesnyder** [comment]
(Close this issue as you see fit.)

**Comment by pmcharrison** [comment]
Weird! The pull request looks open to me - https://github.com/Dallinger/Dallinger/pull/2091

**Comment by jessesnyder** [comment]
Sorry, @pmcharrison - I had this confused with another docs PR (mine from last iteration that included the "how to build docs" docs). ;-)

I'll test out doc building and review the PR.

**Comment by pmcharrison** [comment]
Thanks @jessesnyder !
