### ISSUE TITLE
Incorporating the new network visualization

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2089]
[This continues #2038]

We have implemented Nori’s network visualization as an extension to the base Experiment class. This code is available here - https://gitlab.com/computational-audition-lab/psynet/-/blob/master/psynet/experiment.py - specifically under render_monitor_template. We would like to suggest that you incorporate this into the new experiment dashboard. It requires a few external resources to be incorporated into static/, you can see these in the source code, but they include things like vis-network.min.css and vis.min.js.

**Comment by pmcharrison** [comment]
Currently the repository is private, Jesse, can you share your email address (on Slack if you prefer) so we can add you?

**Comment by jacobyn** [comment]
A network visualisation. 
Here is an updated list of features:
 

- Clicking on a node in the network should take us to a route like /monitor/node/<node_id>.
- Clicking on a participant should do something similar, by default also linking to data from the ‘Manage HITS individually’ side of things.
- Number of infos and failed infos
- Number of nodes and failed nodes
- Finished participants, etc.
- State of the chains: number of nodes completed, full = true/false
- We should be able to customise what happens on this page - the idea is that individual experiments will customise it to reflect their particular implementation (using jinja2 and Python OOP), it might for example show a video or something. It would be nice if this route were embedded inside the dashboard, e.g. in an iframe, such that you don’t have to leave the dashboard to visualise a node.
