### ISSUE TITLE
Dashboard start: password and initial links -- 5 points

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2090]
[This continues #2038]

As an experimenter you could access a dashboard route with a password. After the password has been entered you will not be asked again for the password. The password will be generated automatically at deploy (there will be no password for debug) and printed at the console during deployment. 
After the password the dashboard will for now contain just a few links (e.g links to heroku papertrail logs, heroku postgres).

**Comment by pmcharrison** [comment]
It could also contain the network visualisation.
