### ISSUE TITLE
Change experiment files when the experiment is running: 8 pts

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2114]
[For Nori Iteration 3]

In the current implementation you need to shut down the Dallinger progress in order to make changes in the source code visible. This is a shame for local debugging, because booting up and shutting down the server (and re-copying all experiment files to the tmp folder) takes unnecessary time.

Instead we would like that – in debug mode – once changes to the code are made they are visible upon reloading the website. Clearly this is a difficult task to achieve in the most general sense, because deployment files may be altered by the Python source code, but a partial solution for static files would still be very useful.

We can think of possible solutions to this problem. It might be sufficient to automatically update all changes in the user’s experiment folder automatically to the tmp file. One way to set this up would be to select a predefined tmp file for your project to go to, see [here](https://github.com/polvanrijn/Dallinger/commit/9fa5694492f05dac2db3409a98edf7e6a0ee111e). One way to keep the folders in sync would simply be to write some sync script (e.g. rsync). Another possibility would be to work with symbolic links.

It is important that reloading the page in debug mode, doesn’t kick the participant out of the experiment automatically. [Here](https://stackoverflow.com/questions/16344756/auto-reloading-python-flask-app-upon-code-changes) it is described how Flask app can automatically reload changes in the source code.

**Comment by jessesnyder** [comment]
I covet this feature also. About a year ago I started toying with a `dallinger develop` command that used the symbolic link approach. I didn't even begin playing with change monitoring, but someone (I forget who) also mentioned https://pypi.org/project/watchdog/ for this.

**Comment by pmcharrison** [comment]
This feature has become increasingly important now because migrating to the new Blueprint management system seems to stop PsyNet from being able to hot-reload HTML/JS/CSS changes from files within the PsyNet package. To be honest, I'm not sure why this worked in the first place, but in any case, it was an incomplete solution because it didn't cover Python files. 

Personally, I do most of my development work directly to the PsyNet package, and presumably most experiment directory monitoring schemes will fail to detect changes to this. For me then the directory monitoring aspect of this feature is lower priority. FWIW Shiny apps monitor a single file, `restart.txt`; if the last modified time changes, then the app restarts. So, you can just return `touch restart.txt` in the terminal to restart the app. Something similar could work well here.

**Comment by alecpm** [comment]
If we want to support Flask auto-reload using a simple text file then we'd probably need to configure [FLASK_RUN_EXTRA_FILES](https://flask.palletsprojects.com/en/1.1.x/cli/#watch-extra-files-with-the-reloader)

**Comment by pmcharrison** [comment]
I was happy to see this too!

> When using development mode, the reloader will trigger whenever your Python code **or imported modules** change.
