### ISSUE TITLE
Specifying additional static files to add to the deployment -- 3 pts

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2115]
[For Nori Iteration 3]

Currently the Dallinger deployment process copies files from two locations:

1. The Dallinger source code

2. The local experiment directory

We would like to add a third step to this copying process, where files are copied from arbitrary additional locations as specified in the Experiment class. This is useful for situations where one wants to deploy files that are contained inside another Python package, without having to copy them into the local experiment directory. This would be important for improving the modularity/composability of Dallinger experiment implementations.

There is some flexibility in how we might specify the additional files/directories to copy. One possibility is to provide a list of tuples, where the first element in the tuple is a string corresponding to the file/directory to copy, and the second element is a string corresponding to the target location to which it should be copied (which should be a relative path from the experiment directory) , with any nonexistent parent directories being created. The files/directories would then be copied in order, beginning with the first in the list. For example:

``` python
[
    ("/home/css/funky.css", "static/css/funky.css"),
    ("/home/music/stimuli/stimuli-2018", "static/audio/stimuli"),
    ("/home/music/stimuli/stimuli-2019", "static/audio/stimuli")
]
```

Following the existing Dallinger logic, if a **file** is copied twice to the same location, (e.g. once from the Dallinger source, then once again from the custom list in the Experiment class), the latter version should overwrite the first version. 

Following the existing Dallinger logic, we want **directories** to be copied using a merging strategy. In the above example, `static/audio/stimuli` would therefore contain the combined contents of `/home/music/stimuli/stimuli-2018` and `/home/music/stimuli/stimuli-2019`, with the latter taking the precedence in the case of duplicated files. Likewise, suppose that the experiment class contains the following:

``` python
[
    ("/home/generic-static", "static")
]
```

and the local experiment directory also contains a static directory. Then the ‘generic-static’ directory should be copied first, and the contents of the local ‘static’ directory should then be copied into this directory. Any subdirectories of the local directory should likewise be merged into the corresponding subdirectories of the ‘generic-static’ directory.

Rsync may be a good tool for this recursive merging.

There is a question about which order these three deployment steps should be carried out in. Probably the following makes most sense:

1. The Dallinger source code

2. Custom locations specified in the Experiment class

3. The local experiment directory

**Comment by MatthewWilkes** [comment]
@pmcharrison There's a wrinkle in this, as specified, so I'd be very keen on understanding your particular use-case.

In particular, the problem is that by defining this in the experiment file, we need to be able to import the experiment during the file collation step, which would mean installing all dependencies as well. This would significantly lengthen the time taken to perform various operations.

I had the idea that if you don't need to be able to do any conditional logic as part of those assignments, we could create a text file with the mappings, and parse that. This would mean we can avoid the additional python environment construction time. It then occurred to me that symlinks are a way of approaching this, and I discovered that Dallinger already uses a copy command that follows symlinks, so that could be done with no changes.

So, I guess the questions are:
1. Do you need any form of conditionals or is it fine to have these files defined outside of Python
2. Were you aware that symlinks worked already? If not, are they "good enough", or would you still like the layering of directories that you can achieve with the config file?

**Comment by pmcharrison** [comment]
Hi @MatthewWilkes, thanks for thinking about this important point.

I was interested to think about your proposed solutions. I'm not sure about them yet, though, on account of our current use case. 

A key priority at the moment is to minimise the copy-and-paste boilerplate when defining our experiments. We use our custom library psynet to hide as much of this boilerplate as possible, and we want to psynet to hide as many of the standard static files as possible. Users then defined their experiments by importing psynet and using psynet's custom Experiment class.

Now, you have proposed two approaches:

1. Using a text file in the experiment directory to specify the imports.
2. Using symlinks in the experiment directory to link to external files.

The problem with both of these approaches is that the user now has to put some extra boilerplate in the experiment directory that should ideally be hidden from them.

I think the solutions to this problem come in two categories:

1. Add a pre-deploy hook to psynet that automatically generates the text file specifying the imports. This will necessitate importing `experiment.py`.

2. The solution you've been contemplating so far, which necessitates Dallinger importing `experiment.py`.

Clearly for our use case, options 1 and 2 involve an equivalent performance overhead, and therefore 2 is preferable for its simplicity. However, it is a problem to impose the performance overhead on all Dallinger users even if they are not using this new functionality. 

One possibility would be to add a line in config.txt that the user has to enable if they want this functionality.

It is also worth noting that we talked yesterday about adding custom pre-deployment scripts to be run on the local machine. I then talked us out of doing it, reasoning that if the user wants these scripts, they can just run them manually before running the dallinger command. However, what I didn't think about is the time cost of importing experiment.py. If this is time-consuming, as you noted, it would be preferable to run all these commands within the same Python process. In this case we'd want Dallinger to import experiment.py anyway, which would solve this file collation issue.

Another thing I thought I'd mention concerns personal experience writing Dallinger experiments. In particular, if you make an error in experiment.py that makes importing experiment.py fail, then this typically causes a cryptic Dallinger error, something like 'Unknown exception in worker process'. In such cases, I tell people to track down the error by launching a standalone Python session and trying to import experiment.py manually. This makes me think that it would be a useful feature anyway if the deployment function tried to import experiment.py on the main process.

The last question concerns Dallinger's slow import time. This is the init file:

``` py
"""This is Dallinger, a platform for simulating evolution with people."""

from . import (
    bots,
    command_line,
    config,
    models,
    information,
    nodes,
    networks,
    processes,
    transformations,
    experiment,
    experiments,
    heroku,
    registration,
)
from .patches import patch

import logging
from logging import NullHandler

logger = logging.getLogger(__name__)
logger.addHandler(NullHandler())

patch()

__all__ = (
    "bots",
    "command_line",
    "config",
    "models",
    "information",
    "nodes",
    "networks",
    "processes",
    "transformations",
    "heroku",
    "experiment",
    "experiments",
    "registration",
    "logger",
)
```

I guess there is a reason for forcing the user to import everything on package load, instead of a lazier import process?

Anyway, my bottom line two propositions would be: 

1. Maybe we can add this new functionality, but make it optional via config.txt?
2. Alternatively, maybe we decide that importing experiment.py is worth the performance overhead for several reasons, and we just grit our teeth and go with it? Possibly having thought about whether we could optimise the Dallinger import process.

**Comment by jessesnyder** [comment]
>  In such cases, I tell people to track down the error by launching a standalone Python session and trying to import experiment.py manually. This makes me think that it would be a useful feature anyway if the deployment function tried to import experiment.py on the main process.

@pmcharrison Do you ever use `dallinger verify`? It does what you describe. The check isn't run implicitly when other `dallinger [x]` deployment-related commands are run, since it slows things down, but it's probably a good habit to teach. (Assuming it actually catches the problems you're describing!)

**Comment by pmcharrison** [comment]
Hi @jessesnyder, you're right, that works for the local debugging!

It raises another question for me, though - I tried `dallinger verify` on a colleague's experiment and it failed because the experiment imports local modules, e.g.

``` py
import questions
```

where `questions` refers to `questions.py` in the local directory. This kind of thing works with `dallinger debug` but not with `dallinger verify`. Any advice?

**Comment by pmcharrison** [comment]
We were also wondering what the performance hit you're talking about is. How long does it take you to import experiment.py? For us it is pretty quick.

**Comment by jessesnyder** [comment]
@pmcharrison Try an explicit relative import(?):

```py
from . import questions
```

Also, you're right: it's fast enough that I'm tempted to run it implicitly where we're currently just checking a subset of things, but we need to make sure it's not overly restrictive in some way.

**Comment by pmcharrison** [comment]
Thanks @jessesnyder! That works fine.
