### ISSUE TITLE
Adding “Manage HITs Individually” functionality to the dashboard -- EPIC

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2116]
[For Nori Iteration 3]

[This continues #2038]
 
Child tickets: #2200 (8 points), #2201, #2202, #2203, #2204.

**A wrapper for the Mechanical Turk API. This wrapper should provide access to the following features:**

Manage HIT functionality 1: MTurk (#2200)

Based on https://manage-hits-individually.s3.amazonaws.com/v4.0/index.html#/credentials

This functionality provide the following:

1. The current balance of the recruiter’s MTurk account.
2. State of the current HIT:

- HIT title
- HIT base payment
- HIT description
- HIT time of creation
- HIT time of expiration
- Requested assignments
- Pending assignments
- Reviewed assignments
- Remaining assignments
- Assignment completed
- HIT keywords

3. HIT ad page as an iframe (see here: https://docs.google.com/presentation/d/1BozvqVDHqtltIXGVspjHaD4EdTaXrNC4dXbtr4GdQsE/edit?usp=sharing)
4. The ability to expire the HIT
5. The ability to extend the HIT

- Extend until (select a date from a calendar) (see here https://docs.google.com/presentation/d/1BozvqVDHqtltIXGVspjHaD4EdTaXrNC4dXbtr4GdQsE/edit?usp=sharing)
- Extend by (number of HITs)

6. Simple link to the requester account in MTurk (simple link to https://requester.mturk.com/)
7. Simple link to the qualification page in MTurk (simple link to https://requester.mturk.com/qualification_types)

The following has been archived:

> Manage HIT functionality 2: participant view: basics  (#2201)
> 
> This is based on https://manage-hits-individually.s3.amazonaws.com/v4.0/index.html#/credentials
> 
> Present information for all the workers that did/ currently doing the HIT. For each worker show as a table the following information:
> 1. Assignment ID
> 2. Worker ID
> 3. Accepted at (time) (e.g “17 hours ago”)
> 4. Submitted at (time)  (e.g “16 hours ago”)
> 5. Auto approve (time)  (e.g “15 hours ago”)
> 6. Approve  time (time)  (e.g “15 hours ago”)
> 7. Status (e.g “Approved”)
> 8. Rejected (T/F)
> 
> It would be great if this table could be extensible by the person writing `experiment.py`. Each column could be defined, for example, as a function that takes a list of participant IDs and returns a list of output values.

The following has been archived:

> Manage HIT functionality 3: participant view: compensate and bonus (#2202)
> [This continues #2116 and #2201]
> 
> Compensate and bonus this adds actionable functionality to the table of participants who participate in the HIT of #2201:
> 
> 1. For each participant we should be able to click on them and give them a bonus of a given size. 
> 2. For each participant we should be able to click on them and invoke dallinger auto compensate method for this participant
> 3. We should be able to select many  participants (by clicking on something for example a tick box) and then give all of them the same bonus.
> 4. We should be able select many participants and invoke the dallinger auto compensate function (with the same bonus).

The following has been archived:

> Manage HIT functionality 4: participant view: dallinger integration (#2203)
> [This continues #2116 and #2201 and #2202 ]
> This issue adds links between the table of participants of #2201 and #2202 and dallinger:
> 
> 1. We should be able to see a dallinger participant ID for this participant
> 2. We should be able to see the dallinger participant informaation  for this participant
> 3. We should be able to see all the infos created by this participant in some kind of a table format.

Manage HIT functionality 5: panic tab (#2204)

This is a dashboard tab that suppose to help a user to perform  quick actions in case of a problem:
1. Expire HIT (same functionality as above; this relies on #2201)
2. The ability to set AutoRecruit to “False” / “True” (The feature  that stops dallinger from continuing recruiting)
4. Dallinger destroy 
	
The following has been archived:

> 3. Stop everything: The ability to compensate all active participants by a given amount, expire the HIT, and terminate the experiment. This would be useful if we quickly need to shut down a given experiment for whatever reason. (this feature relies on #2202; the rest of the ticket is relatively

**Comment by jacobyn** [comment]
Example of the manage HIT individually interface:
https://manage-hits-individually.s3.amazonaws.com/v4.0/index.html#/credentials
and
https://manage-hits-individually.s3.amazonaws.com/v5.0/index.html#/credentials
