### ISSUE TITLE
Adding email notification to automated compensation command

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2122]
@jessesnyder has implemented an automated MTurk compensation command (#2028). This issue proposes adding an email notification service to this compensation command, to explain to the participant what just happened and how to access their HIT.

@jessesnyder proposed checking in advance that the email service works. This is a neat idea, but I see two potential problems:

- The most comprehensive way to check would be by sending an email and waiting to receive it, but  this will introduce significant waiting time on each call of the command. In unfortunate cases, we could even have a situation where the test passes but then the subsequent email attempt fails.

- If the email fails, I think we still want to complete the other parts of the compensation, and do the email manually.

So, how about the following: we always attempt to send the email, and check whether it was delivered successfully (perhaps through reference to the status code, or by cc-ing ourselves and checking that we receive the email, or similar). If delivery fails, then we instead print the email we would have sent to the console, and tell the user that they should send the email manually. This way I think we are fairly robust to errors in the email setup. 

These are just ideas though and please feel free to implement something different if it feels more natural. I just wanted to share my thoughts and hopefully save some time.

**Comment by jessesnyder** [comment]
See new comments on #2028

**Comment by pmcharrison** [comment]
Closing this because it has been addressed in #2028 .
