### ISSUE TITLE
Images in demo READMEs are broken in docs

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#216]
@jhamrick Can I assign this to you?
## Expected Behavior

When visiting a demo page, images that display correctly in that demo's README should also be viewable in that demo's docs page.
## Current Behavior

The image link is broken on the docs page.
## Steps to Reproduce (for bugs)

Compare:

https://github.com/Dallinger/Dallinger/tree/master/demos/iterated-drawing

to 

http://dallinger.readthedocs.io/en/latest/demos/iterated-drawing.html
## Context

I believe this has something to do with the [documentation build script](https://github.com/Dallinger/Dallinger/blob/master/docs/source/build_demo_docs.py).

**Comment by jhamrick** [comment]
Both those links show images. Has this been fixed in another PR?

**Comment by suchow** [comment]
@jhamrick I "fixed" it in a hacky way by copying all the images from all the demos into the images directory of the docs (https://github.com/Dallinger/Dallinger/commit/fe86bfc60b07519eb803288a483bda93037a0502#diff-94f100be0cc50b88d9b2acde968d69afR10). This is a bad solution, however, because no two image can share a filename. It would be better if each demo was given its own images directory in the docs. Or maybe there is some way to do this automatically using Sphinx?

**Comment by jhamrick** [comment]
I see. Ok, I'll take a look.
