### ISSUE TITLE
Explore how to best create extendable dashboard tabs/elements -- 2 pts

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2190]
[This continues #2038]

Extendable dashboard tabs/elements: Hooks to extend/ customize the dashboard for a particular application: for example adding a tab for an experiment specific monitoring of some aspect of the data, or experiment specific statistics of the data collected.

**Comment by skleinfeldt** [comment]
@jacobyn and @pmcharrison if this is satisfactory please close.

**Comment by pmcharrison** [comment]
Looking good!
