### ISSUE TITLE
Extendable dashboard tabs/elements (new issue)

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2194]
[This continues #2038]
[It the new issue that replace #2190 as that issue changed content to an exploration]

Hooks to extend/ customize the dashboard for a particular application: for example adding a tab for an experiment specific monitoring of some aspect of the data, or experiment specific statistics of the data collected.

**Comment by skleinfeldt** [comment]
This is being done in conjunction with #2090 so has not been estimated separately.
