### ISSUE TITLE
Manage HIT functionality 1: MTurk - 8pt

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2200]
[This continues #2116] also Based on https://manage-hits-individually.s3.amazonaws.com/v4.0/index.html#/credentials

We decided that the actionable parts (The ability to expire the HIT/ The ability to extend the HIT)  can be splitted to a new issue in case of time limit.

This functionality provide the following:

- [x] 1. The current balance of the recruiter’s MTurk account.
- [x] 2. State of the current HIT:
    - [x] HIT title
    - [x] HIT keywords
    - [x] HIT base payment
    - [x] HIT description
    - [x] HIT time of creation
    - [x] HIT time of expiration
    - [x] Number of requested assignments
    - [x] Number of pending assignments
    - [x] Number of reviewed assignments
    - [x] Number of remaining assignments
    - [x] Number of assignment completed

**Comment by jessesnyder** [comment]
@jacobyn What are the values for these items, specifically?
>Requested assignments
Pending assignments
Reviewed assignments
Remaining assignments
Assignment completed

**Comment by jacobyn** [comment]
It took me some time to understand the question, and I hope I got it right.  In all those cases the values are counts e.g:

- Number of requested assignments
- Number of Pending assignments
- Number of Reviewed assignments
- Number of Remaining assignments
- Number of Assignment completed
I hope this clarifies the issue.

**Comment by jessesnyder** [comment]
@jacobyn For the values that change over time (like the assignment stats above) was it your expectation that you'd refresh the page manually, or did you want the page to make async calls back to the server for the latest info at some regular interval?

**Comment by jacobyn** [comment]
My sense is that it is OK, if it is pulled once, and if you want to refresh it you simply reload the page. Another idea is that we have an additional button that can refresh the information for the entire tab. I don't think we should do periodic calls to refresh the information here.

**Comment by jessesnyder** [comment]
The MTurk "tab" is actually a separate page, so refresh will work fine here.

**Comment by jessesnyder** [comment]
@jacobyn A number of these items are done (see checkboxes). There was quite a lot of infrastructure to take care of, so the 8 points is looking like the right number. I'll try to finish a couple more of the really easy items this week. Should be ready for testing (I've tested in debug [where it uses fake data] and sandbox).

![Screen Shot 2020-06-22 at 3 49 26 PM](https://user-images.githubusercontent.com/63560/85343521-eb61a200-b4a1-11ea-9c1b-fe680a562a98.png)

![Screen Shot 2020-06-22 at 3 50 04 PM](https://user-images.githubusercontent.com/63560/85343525-eef52900-b4a1-11ea-8b73-d1d3b74f7b76.png)

![Screen Shot 2020-06-22 at 3 52 05 PM](https://user-images.githubusercontent.com/63560/85343533-f3b9dd00-b4a1-11ea-8dc0-3eba7d2d25f7.png)

**Comment by jessesnyder** [comment]
@jacobyn A few more questions:
1. Is "assignments remaining" max/requested - completed, or something else?
2. What is "reviewed assignments"? (This may not actually be MTurk information?)
3. Is the context of the ad page iframe the MTurk worker's view, the MTurk requester's view, or th e page on the Heroku server?
4. Items 6 & 7 are just simple links which vary only by whether it's the sandbox or "real" MTurk that's in use, is that right?

**Comment by jacobyn** [comment]
Remaining = Requested - Pending - Reviewed

Reviewed = Approved HITs (see here: 
https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_AssignmentDataStructureArticle.html)
3. In manage HIT individually (the app above) it takes the ad url from the amazon "question" (the thing submitted to Mturk to initiate the HIT): 
<ExternalQuestion xmlns="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2006-07-14/ExternalQuestion.xsd"><ExternalURL>https://dlgr-exp2.herokuapp.com/ad?recruiter=mturk</ExternalURL><FrameHeight>600</FrameHeight></ExternalQuestion>
but this in reality simply point to heroku's (dallinger) ad.html.
The idea is to monitor the health of the ad and see it correctness (since as a requester you don't typically see the ad from the prespective of the worker). To conclude:  iframe the page on the heroku server.

4. yes.

5. Something like "Thu Jun 18 2020 (5 days ago)" 
or "Mon Jun 22 2020 (20 hours ago)" this is what Manage Hit is using and I think it's quite nice.

**Comment by jessesnyder** [comment]
On the assignment status information, if we’re not pressed for space on the dashboard (we’re definitely not yet!), I think it would be good to show both the MTurk terminology and your preferred terminology for each state. I’m still a little confused about how they translate.
MTurk gives us the following attributes on a HIT related to assignments:

- max assignments
- available
- completed
- pending

In some cases the mapping from MTurk terms to yours is obvious:

- “Number of requested …” = max
- “Number of pending…” = available
- “Number of completed…” = completed
- “Number of pending…” = pending

Points of confusion:
- What’s the difference between “Completed” and “Reviewed” in your terminology?
- What's the difference between MTurk's "available" and your "remaining", if any?

Here are the values MTurk provides in HIT information, with their definitions:

> NumberOfAssignmentsPending (integer) --
> The number of assignments for this HIT that are being previewed or have been accepted by Workers, but have not yet been submitted, returned, or abandoned.
> 
> NumberOfAssignmentsAvailable (integer) --
> The number of assignments for this HIT that are available for Workers to accept.
> 
> NumberOfAssignmentsCompleted (integer) --
> The number of assignments for this HIT that have been approved or rejected.

**Comment by jacobyn** [comment]
Mturk terminology is fine. I used terminology based on "managed HIT individually" but it's not critical. So using Mtruk terminology is good enough.
Specifically   “Completed” = “Reviewed”  (they are the same)
"Remaining" = "Available"  (they are the same)

**Comment by jessesnyder** [comment]
Continued in #2226
