### ISSUE TITLE
Manage HIT functionality 2: participant view: basics: 5pts

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2201]
[This continues #2116] also Based on https://manage-hits-individually.s3.amazonaws.com/v4.0/index.html#/credentials

Present information for all the workers that did the HIT:

For each worker show as a table the following information:
1. Assignment ID
2. Worker ID
3. Accepted at (time) (e.g “17 hours ago”)
4. Submitted at (time)  (e.g “16 hours ago”)
5. Auto approve (time)  (e.g “15 hours ago”)
6. Approve  time (time)  (e.g “15 hours ago”)
7. Status (e.g “Approved”)
8. Rejected (T/F)

It would be great if this table could be extensible by the person writing `experiment.py`. Each column could be defined, for example, as a function that takes a list of participant IDs and returns a list of output values.

**Comment by pmcharrison** [comment]
We decided that this is not necessary any more, given the new plans for the participant table.
