### ISSUE TITLE
Manage HIT functionality 3: participant view: compensate and bonus: 5pts

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2202]
[This continues #2116 and #2201] 

Compensate and bonus this adds actionable functionality to the table of participants who participate in the HIT of #2201:

1. For each participant we should be able to click on them and give them a bonus of a given size. 
2. For each participant we should be able to click on them and invoke dallinger auto compensate method for this participant
3. We should be able to select many  participants (by clicking on something for example a tick box) and then give all of them the same bonus.
4. We should be able select many participants and invoke the dallinger auto compensate function (with the same bonus).

**Comment by pmcharrison** [comment]
Given that the compensation tool is currently designed to be executed at the command-line on the deployment computer,  the best way to implement this is presumably to auto-generate commands that can be pasted to the user's command line.

**Comment by pmcharrison** [comment]
We decided that this is not necessary any more, given the new plans for the participant table.
