### ISSUE TITLE
Manage HIT functionality 4: participant view: dallinger integration: ?pts

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2203]
[This continues #2116 and #2201 and #2202 ]
This issue adds links between the table of participants of #2201 and #2202 and dallinger:

1. We should be able to see a dallinger participant ID for this participant
2. We should be able to see the dallinger participant informaation  for this participant
3. We should be able to see all the infos created by this participant in some kind of a table format.

**Comment by pmcharrison** [comment]
Proposal: we add a new panel to the dashboard that allows us to view arbitrary database tables.
This dashboard can be filtered by arbitrary columns, e.g. participant_id and network_id.

Then, we add a button to the participant table (described in another issue) that sends us to the info table,
filtered by the participant_id.

**Comment by jacobyn** [comment]
Discussion in the planning meeting: maybe it will be better to find a general way to display tables (including info) in the dashboard. Peter and Nori will think of this.

**Comment by pmcharrison** [comment]
We decided that this is not necessary any more, given the new plans for the participant table.
