### ISSUE TITLE
Finish off lifecycle tab: 3pt

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2204]
[This continues #2116]

This is provided in the 'Lifecycle' tab of the dashboard.

We decide to implement as a command line, part of this is to check "Expire HIt".

- [ ] The ability to set AutoRecruit to “False” / “True”
- [x] Expire HIT (same functionality as in previous issue)
- [x] Export data (same as functionality in previous issue)
- [x] Export the data with no-scrub (same as export data but add the --no-scrub flag) 
- [x] Dallinger destroy 

We originally proposed the following command too:

> Stop everything: The ability to compensate all active participants by a given amount, expire the HIT, and terminate the experiment. This would be useful if we quickly need to shut down a given experiment for whatever reason.

but we've decided we don't think this is a good idea any more.

**Comment by jacobyn** [comment]
Discussion in the planning meeting. We can not implement "destroy" in the dashboard - needs to be a command line. In this case maybe all of the above can be done in the command line? Peter and Nori needs to do research about "expire HIT" to see if it really not working.

**Comment by pmcharrison** [comment]
Currently we have 3. Export data and 4. destroy implemented. We just need the following, now:

- The ability to set AutoRecruit to “False” / “True”
- Expire HIT (same functionality as in previous issue)

**Comment by jacobyn** [comment]
Note that I updated an additional requested feature related to the --no-scrub option.
