### ISSUE TITLE
Monitor 1: Placeholders, refresh and stats: 8pts

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2219]
[This is a child of #2218]

## Step 1 : preliminaries

Make sure that the demo (see below for a link) works for you (using dallinger debug), run it with a few participants (by finishing the experiment and running again) and observe how the network shows the progress of the experiment (by refreshing http://0.0.0.0:5000/monitor) after every few trials. Try at least 3 participants to see how infos are colored by participants.

The code can be found here “network-monitor.html” found here: https://gitlab.com/computational-audition-lab/psynet/-/blob/dev/psynet/templates/network-monitor.html . An example for running it can be found here:
https://gitlab.com/computational-audition-lab/psynet/-/tree/dev/psynet/demos/non_adaptive (this may need installing psynet: `pip3 install -e .`)  if you run this experiment and refresh the monitor you will see it in action. 
Please contact Peter (peter.harrison@ae.mpg.de) with your GitLab username / email address and he will give you access.

## Step 2 : placeholders for the overall design

Create placeholders (without any implementation) for the 5 elements:
1.Refresh button
2.Statistics
3.Graph
4.Details
5. Settings

The layout should perhaps look like something like this:

![Dashboardoverview](https://user-images.githubusercontent.com/10518584/86007859-4ce0be00-ba18-11ea-9be7-a2005f8de83d.png)

## Step 3: implement the statistics panel

Implement a basic statistics panel showing the basic information. This panel provide information about the number of nodes, participants, networks, information, and transformations. There should be a customizable way to add statistics items by the experimenter, for example, in a particular experiment, report infos of different types or count participants who are assigned to a particular group of stimuli in the network.

Information that needs to be provided is:

1. Number of participants (working, abandoned, return, approved and  active ; the first four  are identical in their definition to the participant table; “active” are participants with more than 10 info associated with them). 
2. Networks - the number of networks from each role (e.g “experiment/ train”), indicate the number of failed networks (from each type) as well. The results should look like that:

> 20 training network, 4 (25%) failed.
> 30 experiment network, 15 (50%) failed.

3. Nodes - the number of nodes; indicate the number of failed nodes.
4. Number of infos - indicates the number of failed infos.
5. Number of transformation - indicated the number of transformations (show it only if "show transformation" is on in "settings")
6. Customizable backend hooks that allow the experimenter to specify additional information (such as average duration of the HIT, number of networks with a specific property or state,  or an injected JS showing graphical information about participant duration). An example of such a customizable item is hard coded into the current example, as in here:
![Example to a extended item](https://user-images.githubusercontent.com/10518584/86008393-fde75880-ba18-11ea-924b-e5b14140dc5b.png)

**Comment by alecpm** [comment]
PR #2225
