### ISSUE TITLE
Monitor 2: graphical monitor and details: 8pts

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2220]
[This is a child of #2218]

This should fully implement the visualization functionality. Make the simplified assumption that the setting uses the “Select all”  option so everything is displayed. 

## Information on the current implementation

1. The code can be found here “network-monitor.html” found here: https://gitlab.com/computational-audition-lab/psynet/-/blob/dev/psynet/templates/network-monitor.html . An example for running it can be found here:
https://gitlab.com/computational-audition-lab/psynet/-/tree/dev/psynet/demos/non_adaptive
Please contact Peter (peter.harrison@ae.mpg.de) with your GitLab username / email address and he will give you access.

2. Most of the work is done by the getnNetwork() in network-monitor.html. This code implements most of the functionality, but the level of the programming may not be sufficient for dallinger and therefore requires refactoring. The first stage could use the code as is, and later one can refactor it and add the additional functionality described below.

3. The current implementation uses a standard graph library. Note that we have a very large network and this puts a constraint on the parameters of the library; there are also some bugs in the way this library is implemented. I ended converging on this parameter, which works fine:

```
var options = {
                layout: {
                    improvedLayout: false,
                    hierarchical: {
                        direction: 'UD',
                        sortMethod: 'directed',
                        edgeMinimization: false, // this is super important as of a bug in the library
                        nodeSpacing: 80, // important due to a bug in the library
                        treeSpacing: 200 // important due to a bug in the librarys
                    }
                },
                interaction: {dragNodes: false},
                physics: {
                    enabled: false,
                    stabilization: false
                },
                edges: {
                    width: 2
                },


```
In addition, in my implementation I grabbed the data from the backend using backend code (this grabs everything without filtering):

```
def network_structure(self):
        from dallinger import models
        from dallinger.models import Vector, Network, Node, Info, Transformation, Participant

        jnodes = [n.__json__() for n in Node.query.all()]
        jnetworks = [n.__json__() for n in Network.query.all()]
        jinfos = [n.__json__() for n in Info.query.all()]
        jparticipants = [n.__json__() for n in Participant.query.all()]

        jvectors = [{
            "origin_id": v.origin_id,
            "destination_id": v.destination_id,
            "id": v.id,
            "failed": v.failed
        } for v in Vector.query.all()]

        return {
            "networks": jnetworks,
            "nodes": jnodes,
            "vectors": jvectors,
            "infos": jinfos,
            "participants": jparticipants,
            "trans": []
        }
```

Note that in the final implementation, if the user selects “setting” to display only partial information then the back-end should return part of the information. Currently this is not implemented, and the filtering is done at the front-end, which is inefficient and causes issues when we need to display very large networks (with a few thousand nodes).

### 1. Networks are grouped by “role” 
In my implementation the way to perform the grouping is to add  father node and connect it with invisible edges to all the network nodes:

![Role](https://user-images.githubusercontent.com/10518584/86033768-c046f780-ba39-11ea-9593-2fd63eb09e14.png)

### 2. Each role is associated with a unique color

![RoleAndColor](https://user-images.githubusercontent.com/10518584/86033788-ca68f600-ba39-11ea-9920-d6d7e65d2b14.png)

In my implementation this was done with the following code:

```
  roles_colors = []; ///  assign pseudo random colors for each role
            for (var j = 0; j < roles.length; j++) {
                rr = 50 + (((j + 3) * 11557) % 200); // pseudorandom colors
                gg = 50 + (((j + 3171) * 31511) % 200);
                bb = 50 + (((j + 371) * 11517) % 200);
                clr = 'rgb(' + String(rr) + ',' + String(gg) + ',' + String(bb) + ')';
                roles_colors[j] = clr;
            }

```

### 3. Each network shows as a single icon, and the network number is indicated below:
![network2](https://user-images.githubusercontent.com/10518584/86033928-0a2fdd80-ba3a-11ea-9fba-57e47f9c1afe.png)

### 4. Each network is connected to a source (if it exists).
If a source does not exist the network is connected to the node with the earliest creation time.
![networkAndSource](https://user-images.githubusercontent.com/10518584/86033982-1d42ad80-ba3a-11ea-8b81-2a7bdbcf19f2.png)

### 5. Failing items (networks/nodes/infos)
If a network (and any other item) has failed it will show in red. For example, here is a network that failed (for illustration purposes not all the nodes were also failed, but in practice when a network fails usually dallinger fails all associated items, so everything would be colored red, but here this is not the case in order to illustrate the coloring of different failed items):
![failed](https://user-images.githubusercontent.com/10518584/86034107-495e2e80-ba3a-11ea-927b-8ba5f945e71d.png)

### 6. Displaying dallinger's vectors
We use the nodes and vectors to create a graph displaying the connection between nodes in the graph.
 This looks like so:
![vectors](https://user-images.githubusercontent.com/10518584/86034212-70b4fb80-ba3a-11ea-9780-235534a88997.png)

```
In my implementation this is taken care by this code in the js part of `network-monitor.html`:
  // actually push the node to node list
                nodes.push(Object.assign(
                    {
                        id: list_of_node_indx[node.id],
                        label: msg + String(node.id), color: clr,
                        title: ('<pre><code><font size="-2">' + JSON.stringify(node, null, 2) + '</font></code></pre>'),
                        group: mgroup,
                        font: {align: 'inside'}
                    },
                    extract_network_meta_data(node.network_id)
                ));
            }

            // create edges for vectors
            for (var i = 0; i < ndata.net_structure.vectors.length; i++) {
                vector = ndata.net_structure.vectors[i]
                var from = vector.origin_id;
                var to = vector.destination_id;
                if (vector.failed) {
                    mclr = 'red'
                } else {
                    mclr = 'blue'
                }

                edges.push(Object.assign(
                    {
                        from: list_of_node_indx[from],
                        to: list_of_node_indx[to],
                        arrows: 'to',
                        title: ('<pre><code><font size="-2">' + JSON.stringify(vector, null, 2) + '</font></code></pre>'),
                        color: mclr
                    },
                    extract_network_meta_data(
                        ndata.net_structure.nodes.filter(function (el) {
                            return el.id === from
                        })[0].network_id
                    )
                ));
            }

```
### 7. Infos:
Infos are connected to the nodes that they are associated with. This should look like so:

![infos](https://user-images.githubusercontent.com/10518584/86034322-a823a800-ba3a-11ea-8888-155ac6093c0b.png)

### 8. Failed infos.
A failed info should be colored red (as mentioned above):

![failedInfo](https://user-images.githubusercontent.com/10518584/86034373-c4bfe000-ba3a-11ea-9818-5862eeca80f1.png)

### 9. Coloring infos by participant 

An non failed info should be colored by the participant number that it is associated with:
This means that each participant is associated with a unique color.

![rainbowinfos](https://user-images.githubusercontent.com/10518584/86034446-e8832600-ba3a-11ea-8f87-cb4f94c5e819.png)

In my implementation this was done with the following code:

  ```
// find all participants and make list, also assigned unique colors to participants
            for (var i = 0; i < ndata.net_structure.participants.length; i++) {
                participant = ndata.net_structure.participants[i];
                participant_id = participant.id;
                if (participant_id == null) {
                    participant_id = 0;
                    participant = '<empty>';
                }
                rr = 10 + (((i + 357) * 2551) % 150); // pseudorandom colors
                gg = 30 + (((i + 3571) * 2511) % 200);
                bb = 100 + (((i + 3571) * 2511) % 150);
                participant.clr = 'rgb(' + String(rr) + ',' + String(gg) + ',' + String(bb) + ')'
                list_of_participants[participant_id] = participant;
            }

```

### 10. Coloring nodes.

Here are the rules for  coloring nodes:
a. If a node fails it should be colored red - this rule has a priority over all other rules.
b. If a node is not associated with any info it should be colored blue.
c. If a node is associated with just one participant (all the infos of this node are from a single participant) it should be colored by the participant’s color
d. If a node is associated with multiple participants (it has infos associated with more than one participant) it should be colored in black.

Here is a visual illustration of how these rules operate in my implementation:

![coloringNodes](https://user-images.githubusercontent.com/10518584/86034557-1cf6e200-ba3b-11ea-9607-b45075d6391e.png)

### 11. Details panel

Whenever clicking on a graph item such as a node, network, info, or a participant, specific information regarding this item should be displayed in the “details” area. This should go to dallinger and call a “/show” route that can be called on any item (node, info, network, participant). This route returns an HTML that is injected to the “Details” section. 

However, one can override the “show” route in a given custom class, and allow for inspecting the element in a more detailed way, returning a combination of HTML and js (or jinja?). For example, if the info really represents an audio recording, we should be able to override the “show” route to a html/ java script that will allow us to play the audio file in the browser. Another use case would be to display for a chain network a short movie that depicts all the states of the chain (this will happen by overriding the show route of a network). It is the responsibility of the experimenter to write this customized “show” route; by default, the details show simply a formatted json.

For example, here is what should happen if a source is clicked (and the default json is displayed):

![detailPanel](https://user-images.githubusercontent.com/10518584/86034591-3435cf80-ba3b-11ea-8ca5-b725339b9a01.png)

Note that currently the functionality that is partially  implemented uses hovering, but this is less usable since the space presented by the hovering is limited, and it is more difficult to customize it.

This is how the workflow should look like:
![workfl](https://user-images.githubusercontent.com/10518584/86034648-4ca5ea00-ba3b-11ea-88ac-c3d52ca76305.png)

### 12. Indicating the participant number on edges
Participants should also be indicated on the edges between nodes and infos like this:
![participants](https://user-images.githubusercontent.com/10518584/86034718-6e9f6c80-ba3b-11ea-92e4-d46ab2f07c97.png)

### 13. Seeing participants' details.

The participant on these edges should be clickable, showing the details associated with this participant in the “details” section. This should invoke the “show” route of the participant in the backend, and by default should provide the information stored in the participant table of the participant. It should be customizable to inject additional html/js for a given experiment (for example one can program something that shows some graphical indication of the participant's performance). This is not implemented in the current version.

### 14. Showing transformations

Transformations should be indicated by a dashed line between infos, with the transformation number indicated as here:

![Trans](https://user-images.githubusercontent.com/10518584/86034831-98f12a00-ba3b-11ea-812b-914ccf7389d0.png)

Note that this often causes ugly visualizations, so by default, transformation information should not be displayed, but one can add this to settings and display them if needed. Clicking on a transformation number should evoke the “show” route in the “details” section.

**Comment by alecpm** [comment]
Included in PR #2225
