### ISSUE TITLE
Monitor 3: implement settings panel to select for partial information: 8pts

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2221]
[This is a child of #2218]

The panel should allows the experimenter to specify what element will be presented. Note that only the information specified in “settings” should be reloaded by comand, i.e in case of a very large network, we don’t need to reload all the graphs if the settings specify just one network to show; only that network will be retrieved from the frontend.  Note that this feature is not fully implemented in the current code (in the current code the filtering is done in the frontend and this is not efficent).

The should be some kind of hierarchical checkbox that allow you to select:
1. **Select all**: so that if this option is selected the graph shows everything.
2. **Select/deselect only networks with a particular role** (e.g select/deselect all experiment networks) 
3.  **Select/deselect a particular network** (choose by number)
4. Show only network and sources (**collapse mode**) - this option will show a shortened version where each network is represented by just a single node (and the source, if extant). This is useful since if we have a very large network we would like to reduce load time by presenting a smaller and more compact representation:
![colapse mode](https://user-images.githubusercontent.com/10518584/86008811-98479c00-ba19-11ea-8123-be2f31782145.png)

5. **Hide/show transformations** (in many cases, showing the transformation makes the graph less readable, so the user should have the option to show/hide transformations). The default is *not* to show transformation or load information about them.

Note that if you select to show partial information then the idea is that refreshing would lead to loading only part of the information, this should enable a reduction of load time for very large networks.

**Comment by alecpm** [comment]
Included in PR #2225
