### ISSUE TITLE
Resuming a participant's session from a different browser/computer: 5pt

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2242]
Currently a participant is identified by a row in the Participant table. They are expected to participate in the experiment in one continuous session. This continuity is maintained, in part, by the Javascript object `dallinger.identity`, which stores the current participant ID with other information like worker ID and assignment ID.

It would be very useful for us if a participant could reconnect to a given participant ID from a fresh browser session, maybe on a different computer. This would require supplementing `createParticipant` with something like `loadParticipant`, where `loadParticipant` takes as an argument the participant ID that is meant to be loaded. Like `createParticipant`, `loadParticipant` would be responsible for filling in the appropriate information (in particular the participant ID, but maybe also HIT ID, assignment ID etc.) in `dlgr.identity`.  We'd probably want to provide some kind of security measure to stop people from just putting in an arbitrary participant ID of their choice. Maybe the best way to do this is just to use `assignmentID`, which should be already unique to each participant, and is available already via their customized URL.

For our applications, we'd want to be able to resume a long time after initially starting the experiment, maybe days later.

**Comment by alecpm** [comment]
@pmcharrison Do we want the route that loads the participant by `assignment_id` to perform some sort of customizable action when loading a participant or should it just return data and allow the JS that calls the `dallinger.loadParticipant` method to perform actions based on the `Deferred` response?

**Comment by alecpm** [comment]
This isn't super critical, but basically I'm wondering whether you anticipate the process of loading a participant to perhaps synchronously make changes to the experiment data in order to determine what REST verb is most appropriate for the route we use to load the participant data.

**Comment by pmcharrison** [comment]
Thanks for the thoughts, @alecpm. Originally I had thought of it as a passive process doing the bare minimum, i.e. reinstantiating the participant object. However, on reflection I think it could indeed be useful to have a customisable action performed at this point, perhaps defined in the `Experiment` class. While we're here, I guess it would *also* be useful to have a customisable action performed when a new participant is created for the first time (i.e. via the `@app.route("/participant/<worker_id>/<hit_id>/<assignment_id>/<mode>", methods=["POST"])` route).

**Comment by alecpm** [comment]
@pmcharrison I was thinking the same thing, and that's an essential part of my implementation plan for #2258. I'll do the something similar on this one.

**Comment by alecpm** [comment]
See PR #2321
