### ISSUE TITLE
`debug_experiment` assumes that the experiment finishes

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2246]
The pytest fixture `debug_experiment` currently throws an error if the experiment doesn't complete (e.g. by all networks filling):

``` py
@pytest.fixture
def debug_experiment(request, env, clear_workers):
    timeout = pytest.config.getvalue("recruiter_timeout", 30)
    # Make sure debug server runs to completion with bots
    p = pexpect.spawn(
        "dallinger", ["debug", "--no-browsers"], env=env, encoding="utf-8"
    )
    p.logfile = sys.stdout

    try:
        p.expect_exact(u"Server is running", timeout=timeout)
        yield p
        if request.node.rep_setup.passed and request.node.rep_call.passed:
            p.expect_exact(u"Experiment completed", timeout=timeout)
            p.expect_exact(u"Local Heroku process terminated", timeout=timeout)
    finally:
        try:
            p.sendcontrol("c")
            p.read()
        except IOError:
            pass
```

In particular, it waits to see `"Experiment completed"`, and if this never happens, a timeout occurs.

I propose that we relax this check. I think that it would be useful to be able to construct experiment tests that don't necessarily complete the entire experiment, but perhaps only test part of the experiment logic, or run a small portion of the participant quota. This functionality would be particularly useful when constructing tests for experiment implementations that have a life outside of the test suite (e.g. real experiment implementations or demos).

**Comment by jacobyn** [comment]
@pmcharrison can you please give an example?

**Comment by pmcharrison** [comment]
I don't have a ready-made example at the moment, but I can make one if is definitely necessary. Is there something that was unclear about my explanation? I'm just proposing deleting the following lines:

``` py
if request.node.rep_setup.passed and request.node.rep_call.passed:
            p.expect_exact(u"Experiment completed", timeout=timeout)
            p.expect_exact(u"Local Heroku process terminated", timeout=timeout)
```

such that the test works even if the experiment doesn't fill up all its networks.

**Comment by alecpm** [comment]
I think it's probably best to create a new fixture for that purpose, since ensuring that the the experiment does run to completion is generally an important part of the tests that currently use that fixture. The other thing to note is that if those checks are absent the test will run until the timeout expires which will result in an exception being raised and the test failing with an error. I think the new fixture will probably need to be structured a bit differently to allow the running experiment to be shutdown without erroring.

**Comment by pmcharrison** [comment]
OK, good to know. Given that it can’t be done easily with the current
fixture, I would propose forgetting about this change, and we’ll just make
sure to document this requirement.
