### ISSUE TITLE
Dashboard password is wrong in sandbox: 1pt

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2251]
Dallinger sandbox provides a password:

```
Dashboard URL: https://dlgr-8c6cc88c.herokuapp.com/dashboard/
Dashboard user: admin
Dashboard password: q8OvL5n0CZrSVkvl1yh3
```

When using this password you get an error:

`There was a problem with your submission`

![image](https://user-images.githubusercontent.com/10518584/87873022-30ec8e80-c9be-11ea-8249-76a24c0d85e7.png)

**Comment by jacobyn** [comment]
The papertrail  error is here:
```

Jul 19 04:03:42 dlgr-e7ced49d app/web.1 INFO:flask_wtf.csrf:The CSRF token is invalid.
Jul 19 04:03:42 dlgr-e7ced49d app/web.1 INFO:geventwebsocket.handler:10.30.108.123 - - [2020-07-19 11:03:42] "POST /dashboard/login?next=%2Fdashboard%2F HTTP/1.1" 200 4014 0.120346
```

**Comment by alecpm** [comment]
Were there multiple web dynos setup in the sandbox run? I suspect the CSRF token (included as a hidden input in the login form) may have been generated on one dyno and submitted to another which didn't recognize it. If that's the case, we may need to adjust the CSRF logic to ensure the tokens are shared between Dynos, or do something to ensure that clients are always directed to the same dyno on successive requests.

**Comment by jacobyn** [comment]
Hi Alec, most of our apps used multiple dynos. Though this behavior occurred also when I sandbox dallinger demos - Bartlett and Mcmcp (I think they come up with a minimal configuration).

**Comment by alecpm** [comment]
PR #2265

**Comment by alecpm** [comment]
PR is merged.
