### ISSUE TITLE
Dashboard monitor page arrangement: 1pt

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2253]
When monitor contains more networks it is organized in a long column:

![image](https://user-images.githubusercontent.com/10518584/87876977-ccd8c300-c9db-11ea-82be-9476d5cc7493.png)

It should be instead organized in two columns one for "statistics" and "setting" and the other for the graph and "details".

Note that when the network is simple we see the right arrangement: 
![image](https://user-images.githubusercontent.com/10518584/87877033-3953c200-c9dc-11ea-92ee-e5d1547b5f96.png)

**Comment by alecpm** [comment]
I think this may be the result of some browser dependent CSS handling of flexbox layouts. It should be relatively easy to address, but it would help to know what browser(s) you are seeing this behavior in. I didn't see this behavior when testing multiple network demos using the original demo experiment the network monitor was extracted from.

**Comment by jacobyn** [comment]
Thank you Alec. I am using an updated chrome version.

**Comment by alecpm** [comment]
If you're seeing this with the psynet demo, you may need to remove the `bootstrap.min.css` from the demo. A newer version is included with Dallinger now, and that version is required for the flex layout that we're using in this screen.

**Comment by pmcharrison** [comment]
Ah, that's absolutely right - thanks @alecpm !!

@jacobyn , PsyNet needs some updating to work with the new Bootstrap, hopefully it'll be a quick fix.
