### ISSUE TITLE
Dallinger deploy from zip file: 5pt

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2259]
The Dallinger CLI provides two pairs of functions that are theoretically rather powerful: hibernate/awaken and export/load. The documentation is as follows:

> ## hibernate
> Temporarily scales down the specified app to save money. All dynos are removed and so are many of the add-ons. Hibernating apps are non-functional. It is likely that the app will not be entirely free while hibernating. To restore the app use awaken. A required --app <app> parameter specifies the experiment by its id.

> ## awaken
> Restore a hibernating app. A required --app <app> parameter specifies the experiment by its id.

> ## export
> Download the database and partial server logs to a zipped folder within the data directory of the experimental folder. Databases are stored in CSV format. A required --app <app> parameter specifies the experiment by its id. Use the optional --local flag if exporting a local experiment data. An optional --no-scrub flag will stop the scrubbing of personally identifiable information in the export. The scrubbing of PII is enabled by default.

> ## load
> Import database state from an exported zip file and leave the server running until stopping the process with <control>-c. A required --app <app> parameter specifies the experiment by its id. An optional --verbose flag prints more detailed logs to the command line. Use the optional --replay flag to start the experiment locally in replay mode after loading the data into the local database.

These functions currently work for the current use cases:

- Finalising an experiment and exporting the resulting data (`export`).
- Freezing a Heroku-deployed experiment so that you can reinstantiate it later for debugging (`hibernate`/`awaken`).
- Loading an exported experiment from its exported zip file so you can explore the networks as if you were a participant (`export`/`load`).

However, they do not work for the following use case: taking a snapshot of an experiment, shutting down the deployment, and subsequently continuing the experiment by redeploying from the snapshot. 
As far as we can see, the main issue standing in the way is that `dallinger awaken` does not create a new recruiter, so no new participants will be recruited. 

Clearly there are two ways that we could redeploy an experiment to collect more data:

- Redeploy by scaling up a hibernated Heroku app (similar to the `awaken` function)
- Redeploy from an exported zip file (similar to the `load` function).

In my opinion we should focus on the second route (zip file). I see no application except for debugging where the first route would be preferable. The advantages of the second route are that a) it's easy to backup multiple zip files as snapshots, and b) it's easy to edit the zip files.

Following this logic, we would therefore propose the following:

Add an optional argument to `dallinger deploy` that allows the user to specify a zip file to load the experiment from. This zip file should take the format as created by `dallinger export`. Applying this option means that the zip file will be used to populate the database, similar to `dallinger load`.

In order to prevent the same participant from taking the experiment twice, we should tell the experimenter to have a config.txt like this:

```
group_name = myexp
assign_qualifications = true
qualification_blacklist = myexp
```

If we've thought through this correctly, this should allows us to redeploy experiments from arbitrary snapshots, as desired.

**Comment by pmcharrison** [comment]
Just tried to run `dallinger load` and got this error:

```
Traceback (most recent call last):
  File "/Users/peter.harrison/.virtualenvs/dlgr_env/bin/dallinger", line 11, in <module>
    load_entry_point('dallinger', 'console_scripts', 'dallinger')()
  File "/Users/peter.harrison/.virtualenvs/dlgr_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/peter.harrison/.virtualenvs/dlgr_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/Users/peter.harrison/.virtualenvs/dlgr_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/Users/peter.harrison/.virtualenvs/dlgr_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/peter.harrison/Dropbox/Academic/projects/harrison-peter/Dallinger/dallinger/__init__.py", line 3, in <module>
    from . import (
  File "/Users/peter.harrison/Dropbox/Academic/projects/harrison-peter/Dallinger/dallinger/command_line.py", line 27, in <module>
    from dallinger import data
  File "/Users/peter.harrison/Dropbox/Academic/projects/harrison-peter/Dallinger/dallinger/data.py", line 33, in <module>
    import odo
  File "/Users/peter.harrison/.virtualenvs/dlgr_env/lib/python3.7/site-packages/odo/__init__.py", line 29, in <module>
    from .backends.pandas import pd
  File "/Users/peter.harrison/.virtualenvs/dlgr_env/lib/python3.7/site-packages/odo/backends/pandas.py", line 94, in <module>
    @convert.register((pd.Timestamp, pd.Timedelta), (pd.tslib.NaTType, type(None)))
  File "/Users/peter.harrison/.virtualenvs/dlgr_env/lib/python3.7/site-packages/pandas/__init__.py", line 263, in __getattr__
    raise AttributeError(f"module 'pandas' has no attribute '{name}'")
AttributeError: module 'pandas' has no attribute 'tslib'
```

I think this error signifies that the code was written for an old version of pandas, and has not been kept up to date.

**Comment by jessesnyder** [comment]
```
    extras_require={
        'data': [
            "networkx<2.0",  # 2.0 is incompatible with odo
            "odo",
            "openpyxl<2.5",  # 2.5 is incompatible with tablib
            "pandas==0.23.4",
            "tablib<0.12",    # 0.12 is incompatible
        ],
```
I think the problem may be that we've pinned the version of pandas, but allowed the version of odo to roam free. Will research.

**Comment by jessesnyder** [comment]
@pmcharrison I found this issue in the pandas repo: https://github.com/blaze/odo/issues/621

I do not encounter this problem running odo 0.5.0 with pandas 0.23.4. Are you running these versions? If not, I wonder if a ` pip install -e ".[data]"` would fix it?

**Comment by pmcharrison** [comment]
Thanks @jessesnyder , my bad, your advice fixed it!

**Comment by pmcharrison** [comment]
I did struggle to login to the dashboard after `dallinger load`, so it's maybe worth checking that the dashboard still works after you implement this updated `dallinger deploy` (not sure whether you want to generate a new password or keep the old one)
