### ISSUE TITLE
Dashboard links to external resources: 1pt

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2269]
There are several issues:

- [x]  The dashboard heroku links don't work:

![image](https://user-images.githubusercontent.com/10518584/88169229-fda73b00-cc1b-11ea-89b5-2e6e931d85ba.png)

```
Refused to display ‘https://id.heroku.com/login’ in a frame because it set ‘X-Frame-Options’ to ‘sameorigin’.
```

It may be that, for security reasons, it is not practical to use iframes after all. Perhaps we should just provide links such that the user can open the Heroku pages in new tabs.

- [x] We would like the Amazon links in the Mturk to open a new browser window tab (instead of navigating away from the dashhboard) 
![image](https://user-images.githubusercontent.com/10518584/88170221-a4d8a200-cc1d-11ea-8ff2-4869fa9c822e.png)
 
- [x] We would like to add a link to Heroku metrics (in the Heroku tab):
![image](https://user-images.githubusercontent.com/10518584/88177466-34d01900-cc29-11ea-9483-8bfbb02d3e57.png)

**Comment by jessesnyder** [comment]
The heroku metrics update depends on the merge of https://github.com/Dallinger/Dallinger/pull/2282, since otherwise it will suffer the same problems on custom app IDs.

**Comment by jacobyn** [comment]
Hi Jesse, loved your work on this.
A small (UI style) suggestion.  
Currently there are dropdown links:
![image](https://user-images.githubusercontent.com/10518584/88370190-d83c3d80-cd91-11ea-9a87-8021827bb3a7.png)
once you click on the dropdown links it shows this:
![image](https://user-images.githubusercontent.com/10518584/88370208-e2f6d280-cd91-11ea-8864-ef42c6e87f23.png)

I think it make more sense that the Heroku tab will not have a dropdown links but just a normal tab, and the links will be part of the tab. Something like this:
![image](https://user-images.githubusercontent.com/10518584/88370258-00c43780-cd92-11ea-9c69-9e046999bc5f.png)

What do you think?

**Comment by jacobyn** [comment]
In addition I think it's better if the links is opened in a new browser tab (rather than navigating out of the dashboard). Maybe this what already happens (it's hard to see this from the webcast).
