### ISSUE TITLE
Dashboard location of "logout" button: 0pt

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2275]
The location of the "logout" in the end of the page is hard to work with.

![image](https://user-images.githubusercontent.com/10518584/88192824-46bbb700-cc3d-11ea-82d6-b927c375f94a.png)

Perhaps put it in the top of the dashboard in the top right?
![image](https://user-images.githubusercontent.com/10518584/88193697-3fe17400-cc3e-11ea-8e70-e2bf2f70b608.png)

Could be also a bottom in the top right.

**Comment by alecpm** [comment]
See PR #2280
