### ISSUE TITLE
Dashboard: displaying large object JSONs

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2283]
If the object has a wide pretty-printed JSON representation, then the displayed text stretches the dashboard panel, making the network impossible to read. See the below example:

<img width="1782" alt="Screenshot 2020-07-24 at 11 50 27" src="https://user-images.githubusercontent.com/22684998/88379839-ded3b080-cda3-11ea-9a69-017a28d1c402.png">

Proposed fix: add a `max-width` and `overflow: scroll` property to this `<pre>` section. That produces something like this (in this particular example, I added `max-width: 800px; overflow: scroll`.)

<img width="562" alt="Screenshot 2020-07-24 at 11 53 46" src="https://user-images.githubusercontent.com/22684998/88380176-57d30800-cda4-11ea-9329-65a17687824d.png">

<img width="1602" alt="Screenshot 2020-07-24 at 11 52 06" src="https://user-images.githubusercontent.com/22684998/88380038-1a6e7a80-cda4-11ea-9061-143cde25eb36.png">

I wasn't sure on what the precise value of `max-width` should be, it seemed a bit complicated to work out the best option. But something hard-coded (e.g. 800px) would be better than nothing.

**Comment by alecpm** [comment]
@jessesnyder noticed this a couple of days ago and I included a fix for it in PR #2280.

**Comment by pmcharrison** [comment]
Amazing. Thanks!
