### ISSUE TITLE
Passing extra variables to ad.html and consent.html: 2pts

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2297]
It is often useful to pass extra variables to ad.html or consent.html, however this ability is not currently provided by Dallinger. The "/ad" route is long and complex, and finishes like this:

``` py
return render_template(
    "ad.html",
    recruiter=recruiter_name,
    hitid=hit_id,
    assignmentid=assignment_id,
    workerid=worker_id,
    mode=config.get("mode"),
    app_id=app_id,
)
```

We would like to be able to inject extra variables into this `render_template` call, with these variables being defined as a class attribute on the Experiment class (see `extra_files` for a similar approach. Likewise, we would like to be able to inject extra variables into the `render_template` call for consent.html.

**Comment by alecpm** [comment]
There is an `experiment` variable that is injected to the template context automatically (along with the os environment as `env`) using a Flask `context_processor`. We need to document that feature.

**Comment by pmcharrison** [comment]
This solves the issue - thanks! But yes, some documentation would be useful.

**Comment by jessesnyder** [comment]
@pmcharrison (cc @alecpm ) Having forgotten about the `context_processor` thing I did some playing with this, which I'll summarize in case it's preferable to that existing solution (I think it is for most cases; the full experiment injection was a bit of a hack for Griduniverse). I tried both the fixed class attribute that you'd asked for, and also an instance method which takes the request as an argument, and both worked, with no difference in implementation complexity. The instance method would give you access to the database, and allow you to return different values for different routes/template combinations. An advantage of this technique would be that Dallinger-the-framework could include this hook in other `render_template()` calls if we wanted to, and the dynamic aspect would (optionally) live in the Experiment class.

Both options, added to Bartlett:
```python
class Bartlett1932(Experiment):
    """Define the structure of the experiment."""

    ad_route_template_params = {"first_name": "Jesse"}  # class attribute

    def template_params(self, request):  # instance method
        return {"endpoint": request.endpoint}
...
```

In the ad.html template:
```html
<h3>From class attribute:</h3>
<pre> {{ first_name }}</pre>

<h3>From instance method:</h3>
<pre>{{ endpoint }}</pre>
```

Output:

![Psychology_Experiment](https://user-images.githubusercontent.com/63560/103320701-4e9d3580-49eb-11eb-9c5a-bdcb86370afb.png)

Currently implementing _both_ changes in `experiment_server.advertisement()`:
```python
    experiment_class = experiment.load()
    experiment_instance = Experiment(session)
    return render_template(
        "ad.html",
        recruiter=recruiter_name,
        hitid=hit_id,
        assignmentid=assignment_id,
        workerid=worker_id,
        mode=config.get("mode"),
        app_id=app_id,
        **experiment_class.ad_route_template_params,
        **experiment_instance.template_params(request)
    )
...
```

**Comment by alecpm** [comment]
I don't have a strong opinion here. If it's likely that attributes from the request object are needed within these variables then the instance method is preferable to the attribute. Otherwise an attribute is simpler (and can be made dynamic with access to the db `session` using a property decorator). Direct access to the experiment instance should provide complete flexibility, but is perhaps too unconstrained for this use case. Since we already provide the last option, maybe that's sufficient once it's documented, even if it's not immediately clear how to solve this specific problem with that generic feature.

**Comment by pmcharrison** [comment]
Thanks for exploring this, @jessesnyder and @alecpm! 

I think I would vote for the most flexible of all of these, i.e. having access to the experiment instance. I would tend to think there's little benefit in adding the instance method in addition to the pre-existing experiment injection, but for one thing - can Jinja2 access object properties defined with the `@property` decorator? I had a vague feeling that it couldn't but I can't find any documentation supporting that hunch right now. If indeed we can't use `@property` fields within Jinja2, then @jessesnyder 's new method does add something useful.

**Comment by jessesnyder** [comment]
A `@property` decorator seems to work fine, so it sounds like we can close this issue(?)
 
Experiment class:
```python
    @property
    def time(self):
        return "The time is now."
```

Template:
```html
<h3>From injected experiment:</h3>
<pre>{{ experiment.time }}</pre>
```

Output:
![Psychology_Experiment](https://user-images.githubusercontent.com/63560/103585404-dbd30500-4e97-11eb-82b4-3bef0bf4e4c1.png)

**Comment by pmcharrison** [comment]
Thanks for checking, @jesse! I agree, guess that's it then :-)
