### ISSUE TITLE
Improving speed of dallinger debug: 2pts

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2317]
Currently the `dallinger debug` command runs pretty slowly, often taking 10-15s to launch a local instance of the experiment. This slows down the interactive development cycle. Any ideas about how we might speed up this process? Perhaps have a command-line option that bypasses local Heroku?

**Comment by pmcharrison** [comment]
To do list for next time - 

- Set `threads = 1` for local debug
- Start browser windows in async processes

**Comment by pmcharrison** [comment]
Also I discovered another culprit:

``` py 
def verify_experiment_module(verbose):
    """Perform basic sanity checks on experiment.py.
    """
    ok = True
    if not os.path.exists("experiment.py"):
        return False
    # Bootstrap a package in a temp directory and make it importable:
    temp_package_name = "TEMP_VERIFICATION_PACKAGE"
    tmp = tempfile.mkdtemp()
    clone_dir = os.path.join(tmp, temp_package_name)
    to_ignore = shutil.ignore_patterns(
        os.path.join(".git", "*"), "*.db", "snapshots", "data", "server.log"
    )
    shutil.copytree(os.getcwd(), clone_dir, ignore=to_ignore)
```

The last line liberally copies files from the working directory to a new directory, which can be time consuming if you follow the practice of having a virtual environment folder in your experiment directory (my current one is 500 MB). Really this copy directive should be ignoring all files specified in gitignore (this logic is implemented somewhere else in Dallinger, but apparently not here).

**Comment by jessesnyder** [comment]
Nice catch, @pmcharrison. This function should be updated to also use `ExperimentFileSource`, like the `verify_directory` function above it. I think this would fix the problem.

**Comment by jessesnyder** [comment]
I'm less sure that it's safe to overwrite the `threads` setting. Some experiments may not work at all with a single thread (looking at you, Griduniverse). @alecpm will probably have insights here.

**Comment by alecpm** [comment]
I wouldn't mess with `threads` and would be very very surprised if doing so changes startup times significantly. I don't think Gunicorn startup times are impacted by the worker count.

**Comment by pmcharrison** [comment]
On my machine reducing threads to 1 reduces the startup time from 9 s to 8 s, so not a massive speed up. It does seem a bit unnecessary though that the number of threads will increase arbitrarily high depending on the number of CPU cores available, if there is a time penalty.

**Comment by pmcharrison** [comment]
...but one possibility would be to set a lower value of `threads` solely in debug mode?
