### ISSUE TITLE
Issue Loading Documentation

### ISSUE THREAD

**Issue by aalaouisoce** [Dallinger/Dallinger#2347]
## Current Behavior
The Dallinger documentation (docs.dallinger.io) isn't loading. The server IP address can't be found. Sorry for the bother.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Dallinger version used:
* Operating System and version (desktop or mobile):
* Browser and version (e.g. Chrome 39, node.js 5.4):
* Link to your project:

**Comment by alecpm** [comment]
If ownership of the dallinger.io domain has lapsed, someone with administrative access to the Dallinger https://readthedocs.org account (probably @suchow or @thomasmorgan) needs to remove the dallinger.io alias there and setup the docs url at e.g. dallinger.readthedocs.org.

**Comment by thomasmorgan** [comment]
It's not me. @suchow ?

**Comment by pmcharrison** [comment]
Hi @aalaouisoce , you can now find the documentation here: https://dallinger.readthedocs.io/en/latest/
