### ISSUE TITLE
Dashboard does not display Questions in database view: 3pt

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2414]
For some reason, the database view in the dashboard does not have a tab for Questions.

![image](https://user-images.githubusercontent.com/22684998/98657869-435a5180-233a-11eb-8dfe-8d461171fe08.png)

It would be useful to have this implemented.

**Comment by jacobyn** [comment]
I am not sure this is the place to report this, but there a few bugs in the display now.
The question tab is weird:
![image](https://user-images.githubusercontent.com/10518584/103415413-4c211400-4b82-11eb-8911-6e1422e01c4d.png)

Participant table shows nicely:
![image](https://user-images.githubusercontent.com/10518584/103415432-5e02b700-4b82-11eb-84db-b44b23c9ed26.png)

But info table shows jsons and list in a wierd way (not sure why):
![image](https://user-images.githubusercontent.com/10518584/103415452-6f4bc380-4b82-11eb-944e-3ba006187b85.png)


This probably interacts with our custom experiment here, but the hope that it would work like it works for the participant table in all cases.

**Comment by alecpm** [comment]
I'll take a look at the question table issue, my guess is that there's a table column the default config table isn't accounting for properly.

Is that `analysis` column from the `Info` table a JSON column in the DB or is it a varchar/text column that you store JSON string in? If it's the former, then there's probably something I need to change to make it format correctly. If it's the latter you'll probably need to customize your `Experiment.table_data` to provide formatting hints. In the latter case, you can look at `experiment_server.prep_datatables_options` to see how it manipulates the column data to provide a formatted string. Of course, it may be easier to change your custom column to JSON.

**Comment by pmcharrison** [comment]
Hi @alecpm , thanks for the quick response! Just to add - 

* It was probably obvious already, but the problem observed in the Question tab is (probably) not specific to the Question tab, but rather concerns the necessity to escape HTML content produced by the `__json__` method.
* The `analysis` column is compiled in the `__json__` method, it doesn't correspond directly to a column in the database, but is rather stored as an element within the `details` column. I thought that the `analysis` object would just correspond to a `dict`, but I'm not sure why this serialisation failure would happen, then. I am fairly confident I could get somewhere useful by sitting down and debugging, but haven't had the time yet.

**Comment by alecpm** [comment]
I was just going to ask if that JSON perhaps included some HTML. Generally speaking the templates escape HTML, but because we explicitly use `<code>` blocks for the rendered output we end up avoiding the default escaping. I'll see what I can do to HTML escape the JSON inside the code block from python.

If `analysis` ends up returning a JSON string instead of a dict, that could explain it, but I think any `dict` values should generally get turned into JSON wrapped in a `<code>` block.

**Comment by alecpm** [comment]
Not sure what happened here, but this PR was still open, so I don't think this got released before. Though maybe we already had a changelog entry for it?
