### ISSUE TITLE
Graphical issues with the dashboard monitor: 5pt

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2419]
- [ ] The dashboard visualization shows certain items as overlapping, specifically for complex structures with multiple network types. For example:

<img width="867" alt="Screen Shot 2020-11-12 at 3 12 24 PM (1)" src="https://user-images.githubusercontent.com/10518584/99074130-7bba9380-25b7-11eb-88fb-66836d2821c5.png">

The problem originates from the fact that in the original implementation by Nori we connected all nodes to a father "dummy" node. This made all networks to a tree/connected graph structure. This allows the js framework to order properly the network. Once this father node is absent bugs in the layout algorithm caused overlap in the networks. A simple solution to this problem would be to re-connect the top network to a father node.

- [ ] The network visualization shows networks as an empty square:
<img width="125" alt="Screen Shot 2020-11-12 at 3 10 53 PM (1)" src="https://user-images.githubusercontent.com/10518584/99074696-888bb700-25b8-11eb-8092-15e5c77e4447.png">

They should really look like this:
<img width="603" alt="Screen Shot 2020-11-13 at 1 57 15 PM" src="https://user-images.githubusercontent.com/10518584/99074517-2c289780-25b8-11eb-9c54-4179f0fc4e15.png">

This is probably due to a missing dependency (font-awesome : https://fontawesome.com/how-to-use/javascript-api/setup/getting-started). We should either add the missing font or replace the symbol for network to one that is supported so networks are not displayed as empty squares.

**Comment by thomasmorgan** [comment]
@jacobyn I didn't report this at the time, but I recently ran an experiment with multiple fully connected networks of varying sizes and the visualization went super weird very quickly. Networks were often placed huge distances apart from each other. Also, once we got to about 200 participants the page stopped loading which I guess was a visualization issue (though it could be something else on the page).

**Comment by jacobyn** [comment]
Hi @thomasmorgan this is super helpful. Can you perhaps provide the code for that visualization? It will be super useful in debugging this. There is a graph visualization library with some layout options, one option would be to expose these options to the experimenter allowing different optimizations for different use cases.

**Comment by thomasmorgan** [comment]
@jacobyn I can provide the experiment code or an exported data set, will that work? I'm not sure what you mean by "code for that visualization"

**Comment by jacobyn** [comment]
@thomasmorgan I mean the code for the experiment (so that it reproduce the issue with the visualization)

**Comment by thomasmorgan** [comment]
@jacobyn sure: https://github.com/thomasmorgan/mate-choice-prestige

**Comment by jacobyn** [comment]
I think that the right solution is to allow the user to change some of the parameters of the vis library.
The script `network-monitor.js` has the following layout parameters:

```
layout: {
        improvedLayout: false,
        hierarchical: {
          direction: 'UD',
          sortMethod: 'directed',
          edgeMinimization: false, // this is super important as of a bug in the library
          nodeSpacing: 100, // important due to a bug in the library
          treeSpacing: 200 // important due to a bug in the librarys
        }
```

It is probably hard to find parameters that are good for everybody, so perhaps there is a way to customize or simply let the user change the type of node organization ("hierarchical") and the parameters:  nodeSpacing and treeSpacing.

**Comment by alecpm** [comment]
I've got a branch/PR that tries to address these issues:

https://github.com/Dallinger/Dallinger/pull/2489
