### ISSUE TITLE
Upgrade version: 5pt

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2420]
The dallinger installation process is blocked from a number of reasons:

- [x]  Versions of libraries are not updated.

- [x]  Python dev installation instructions refer to python 3.7 but the current version is 3.9, so either change the instructions to point to download and install and older version or update the requirement to 3.9

- [x]  Unix installation fails.

**Comment by jessesnyder** [comment]
I think we need a preliminary discussion of which python versions we're going to support and test on Travis CI:

- Is it time to drop python2.7?
- Time to drop 3.6 as the oldest verion?
- What versions do we have available on Travis and Heroku?

**Comment by pmcharrison** [comment]
Good idea, @jessesnyder. Because these are quite big decisions, @jacobyn and I agreed that we should schedule them for a formal group discussion, hopefully to be finalised soon.

**Comment by jacobyn** [comment]
In the dallinger "board" meeting, @suchow, @thomasmorgan and I decided to:
a) Drop support for python 2.
b) Currently only 3.7 version works, it will be nice if all versions >3.7 will work
c) Update the Travis version so it is supporting the latest one.

**Comment by pmcharrison** [comment]
Travis has been extracted to #2454.

**Comment by cguardia** [comment]
Closing this one, since a release with all the improvements is out:

https://pypi.org/project/dallinger/7.0.0/
