### ISSUE TITLE
extra_parameters as class attribute: 2pt

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2432]
Currently `extra_parameters` must be defined as part of the experiment module (i.e. experiment.py). We want also to be able to define `extra_parameters` as part of the experiment class, so we can achieve inheritance etc. In other words, the user should be able to define a custom `extra_parameters` method in the `Experiment` class that provides calls to `config.register()`.

See also #2297 for a similar feature request.

**Comment by thomasmorgan** [comment]
@pmcharrison @jessesnyder What is the reason for having extra_parameters at all? Why not add these parameters as properties of the experiment class, instead of adding them to the config file and then making these accessible through extra_parameters?

**Comment by pmcharrison** [comment]
The story is a little complicated, but essentially we have made some properties of the Experiment class database-backed, so they are initialised from config.txt but can be changed mid-experiment. This doesn't work well with researchers overriding these properties when they inherit the experiment class, because the mutability property is lost.

**Comment by alecpm** [comment]
Noting the new PR for switching this to a class method #2528

**Comment by alecpm** [comment]
Proposed CHANGELOG entry:

* Added `experiment_parameters` `classmethod` to experiment class to simplify registration of custom `config` variables.
