### ISSUE TITLE
Discuss potential role of Docker

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2434]
We would like to discuss the possibility of moving towards Docker-based deployment of Dallinger apps. It seems that this could bring several benefits:

- Long-term reliability/reproducibility - we wouldn’t rely on Heroku for providing their own version of Redis/Postgres, but would specify our own with Docker. This would have saved us from the recent problems with Heroku’s Redis upgrade.
- Easy generalisation to other, non-Heroku cloud services. This is particularly relevant for collaborations where ethics insists that the servers be hosted on-site.
- More homogeneity between the development environment and the deployment environment, speeding the debug process. 

Obviously it would be a lot of work if we decided to go ahead with this, so we need to think about it carefully.

**Comment by skleinfeldt** [comment]
FYI Jazkarta did quite a bit of work on Docker back in the summer of 2018, there are user stories in Scrumdo (like 345, 385, 395). Witek did a lot of the work, @jessesnyder and @alecpm could say more about it. From my notes 10/27/2018:

> BTW Witek thinks Docker adds a whole layer of complexity, so not necessarily good to recommend it as the easiest way to run Dallinger. Virtualenv is easiest. Jesse thinks it is more a deployment solution, not a developer solution. Decided to leave it in separate repo, update 5.0 docs to accurately describe it, and do NOT include it in 5.0 release (aside from in the Dallinger documentation).

**Comment by jacobyn** [comment]
@thomasmorgan @suchow we would love to have you integrated in the discussion, could you report in the slack channel your availability in the coming week, so that we can try to schedule this discussion when you are available?  

In addition, @suchow  can you please comment on this? I remember you were saying you experimented with this in the workshop.

**Comment by alecpm** [comment]
I think the following links which relate to questions orchestrating data storage in a generic way for Dockerized applications may be useful for reference:

https://vsupalov.com/database-in-docker/
https://cloud.google.com/blog/products/databases/to-run-or-not-to-run-a-database-on-kubernetes-what-to-consider

Kubernetes is the most cloud agnostic way to orchestrate docker deployments, but it's not clear how safe it is to rely on it for the data storage layer (Dallinger experiments are relatively transient, so it may turn out to be fine now that kubernetes has support for Local Persistent Volumes).

[Terraform](https://www.terraform.io) seems to be the standard these days for cloud agnostic orchestration, but it still generally requires separate configurations for each cloud provider (e.g. we could provide a default AWS Terraform setup and allow people to contribute Terraform setups for other providers).

**Comment by pmcharrison** [comment]
Thanks for this, @alecpm, it helps a lot for illustrating what you said in
the meeting!

From what I've read from the materials, it does indeed like Terraform is
the natural way to abstract away from Heroku in a provider agnostic-way
while providing a natural database hosting solution.

**Comment by jacobyn** [comment]
I am still not sure what we would do if need to run it on a local server. If we choose Kubernetes and HELM we can naturally run K3S on a strong server to provide us Kubernetes on a local server (this can be also done locally on your computer to debug). Do Terraform has similar solution?

**Comment by jacobyn** [comment]
In addition I discussed yesterday the usage of Persistent Volumes with a friend that is an Kubernetes expert (he is leading dev in a startup that I know). He says that Persistent Volumes are good solution and will work well for our use case.
