### ISSUE TITLE
Discuss generic recruiter extension

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2435]
We would like to discuss how we could develop a more generic recruiter in Dallinger for easy application in various contexts, for example using Prolific, for conducting lab experiments, for conducting lab experiments via an intermediary, and so on. This generic recruiter needs certain features such as the ability to have a global recruitment link to which we can pass various URL parameters identifying the new participant, and at the end of the experiment generating (for example) crytographically verifiable assets to prove that the participant completed the experiment successfully.

We have developed some ideas in this [Google Doc](https://docs.google.com/document/d/1k2uE9WvfCxKt-DQmG39R678PIG0sfLfE94raaMaXWfE/edit?usp=sharing). However, we would like to discuss in more detail with a developer before committing to a particular way forward.

**Comment by thomasmorgan** [comment]
Generalizing Dallinger's recruitment capacity is becoming an increasingly important issue. Some collaborators are wary of using MTurk (it has a not great reputation), some journals consider it unreliable, and informally data quality appears to have gone downhill over the past year or so.

@jacobyn I'd suggest making this the key development milestone for this cycle, but it is your call.

**Comment by jacobyn** [comment]
@thomasmorgan @suchow we would love to have you integrated in the discussion, could you report in the slack channel your availability in the coming week, so that we can try to schedule this discussion when you are available?

**Comment by vaelgates** [comment]
@jacobyn Any progress on this? (I'd use it to recruit from Prolific for an upcoming experiment if it were available)

**Comment by pmcharrison** [comment]
We plan to start work on it soon, but haven't started yet, sorry.

**Comment by vaelgates** [comment]
Thanks! Do you know if it'll be completed within e.g. the next month? Need to figure out what I'm doing for a time-sensitive project, no problem if not obviously, just doing planning.

**Comment by pmcharrison** [comment]
Sorry, I'm not really sure! It seems possible but at the same time hard to
commit. I'll let @jacobyn jump in if he has a clearer idea.

**Comment by jacobyn** [comment]
I don't think it's a good idea to rely on it, for a time sensitive project. 1) We don't know how fast the progress will be 2) the support for Prolific would not as good as Mturk as long as prolific would not release their full API, several things would require manual work and so the speed in which you can work would not be as good as in Mturk even after we start developing the feature. Thus said, I believe that once we had the basic feature developed and after some work we probably have set of scripts that will make Prolific experience (almost) as good as in Mturk but this will take even more time. Another thing that can help is that prolific will release a full API something that they are planning to do, but we will need then to adapt it to dallinger. In short, all of this may require time and get matureness.

**Comment by vaelgates** [comment]
Sounds good-- thank you both very much!
