### ISSUE TITLE
Request: CLI ability to test email sending

### ISSUE THREAD

**Issue by thomasmorgan** [Dallinger/Dallinger#2447]
Compensating participants can involve dallinger sending them an email to let them know. However, setting up the email system is not trivial (it works fine for me, but won't work for some of my lab members with no clear reason) and there's no way to test it without attempting to compensating someone. It would be nice to add a CLI function to try sending an email to yourself that way you can know whether the email function is set up correctly or not.

e.g.
``` dallinger test_email ```
or
``` dallinger test_email --email my_email@emailprovider.com ```

**Comment by jessesnyder** [comment]
@thomasmorgan I added this CLI command at the same time the `dallinger compensate` command was added, for this reason:
https://dallinger.readthedocs.io/en/latest/command_line_utility.html#email-test

Example usage (I just ran it):
```
$ dallinger email_test

❯❯ Email Config
-----------------------  --------------------------
smtp_host                smtp.gmail.com:587
smtp_username            jesse@rasikaconsulting.com
contact_email_on_error   jsnyder@wesleyan.edu
smtp_password            fug......v
dallinger_email_address  jesse@rasikaconsulting.com
-----------------------  --------------------------

❯❯ ✓ email config looks good!

❯❯ Sending a test email from jesse@rasikaconsulting.com to jsnyder@wesleyan.edu

❯❯ ✓ Test email sent successfully to jsnyder@wesleyan.edu!
```

Does this do what you need?

**Comment by thomasmorgan** [comment]
@jessesnyder this is perfect thanks! Which release version is this in?

**Comment by jessesnyder** [comment]
@thomasmorgan Great to hear! It's in 6.2.1 and later:
https://github.com/Dallinger/Dallinger/blob/master/CHANGELOG.md#v-621-2020-04-25

**Comment by thomasmorgan** [comment]
Perfect, I will close the issue.
