### ISSUE TITLE
Simple Docker deployment (local deployment): 13 pts

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2467]
We want to implement an initial version of Docker deployment without worrying about orchestration things for now.

I think we want to have Redis and Postgres services contained within the Docker image, so the 'full package' is completely contained within Docker. However, we should also be able to use external Redis/Postgres services specified by URL.

For this present issue, we want to be able to build a Docker image from the command line, and also launch this Docker image using the Dallinger CLI.

**Comment by silviot** [comment]
The implementation in #2568 uses `docker-compose` to orchestrate redis, postgresql, worker and web server containers.
The docker image we generate is only used for the worker and web server. The other services are brought up by docker compose.
