### ISSUE TITLE
Use CDN versions of common JavaScript libraries and CSS

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#25]
## Expected Behavior

JavaScript libraries and CSS stylesheets, such as Bootstrap's, can be downloaded by the client directly from a CDN:

http://getbootstrap.com/getting-started/ 
## Current Behavior

These assets are served from the Dallinger server and are stored in the code base multiple times (e.g., once per demo).

**Comment by vlall** [comment]
This is solved: https://github.com/Dallinger/Dallinger/commit/192b65361d1c2c653ae76de72225870a97f8ee7e
