### ISSUE TITLE
Delay between opening dashboard and opening experiment window in dallinger debug

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2518]
When I run `dallinger debug`, there is a 5-second delay between the dashboard window opening and the experiment window opening. @jessesnyder , I remember you did some work already optimising start-up times. Does this delay happen for you? I think we discussed it already but didn't get round to addressing it yet.

**Comment by jessesnyder** [comment]
Yes, I spent quite a bit of time with it. The delay is more or less hard-coded in the webbrowser library (I should have made detailed notes, but didn't). I would not say it's definitely impossible to bypass the delay somehow, but I wasn't able to figure it out in the midst of whatever else I was working on.

I think this is our culprit:
https://github.com/python/cpython/blob/3.9/Lib/webbrowser.py#L244

I forget why remote is always true, but iirc this is the case.

**Comment by pmcharrison** [comment]
Ah, thank you for taking the time to (re)explain. Sounds too awkward to fix for now!

**Comment by pmcharrison** [comment]
I had another thought that might provide a quick win in practice. What if we just change the order of page opening, so that the experiment page opens first, then the dashboard page opens second? That way the experimenter can start already on working through the experiment (normally you don't need the dashboard until later on). 

Ideally there would be a way of preventing the dashboard window from stealing 'focus' when it opens (as far as I understand, when the page opens after its 5-second delay, the new window will take over from what the user was doing before). But that's not a big deal.

**Comment by jessesnyder** [comment]
This isn't a quick change, unfortunately (I was very optimistic!). We open the dashboard just before we start listening for messages from the recruiter (it is such a message that triggers opening the ad/consent windows for the experiment). Once we start listening, we're blocked, so trying to open the dashboard later means opening it only after the entire experiment is finished:

```python
            if result["status"] == "success":
                # ...
                self.display_dashboard_access_details(dashboard_url)
                if not self.no_browsers:
                    self.open_dashboard(dashboard_url)
                # this blocks for the remainder of the debug session:
                heroku.monitor(listener=self.notify)
```

We could maybe figure out a way to change this, but it's not the just-reorder-the-statements problem we were hoping for.

**Comment by pmcharrison** [comment]
Ah well, thanks for trying anyway!
