### ISSUE TITLE
Delay in dallinger debug

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2519]
When I run `dallinger debug`, there is a 5-second delay between the dashboard window opening and the experiment window opening. @jessesnyder , I remember you did some work already optimising start-up times. Does this delay happen for you? I think we discussed it already but didn't get round to addressing it yet.

**Comment by jessesnyder** [comment]
Yes, I spent quite a bit of time with it. The delay is more or less hard-coded int the `webbrowser` library (I should have made detailed notes, but didn't). I would not say it's definitely impossible to bypass the delay somehow, but I wasn't able to figure it out in the midst of whatever else I was working on.

**Comment by jessesnyder** [comment]
I think this is our culprit:
https://github.com/python/cpython/blob/3.9/Lib/webbrowser.py#L244

I forget why `remote` is always true, but iirc that was the case.

**Comment by jessesnyder** [comment]
Dup of https://github.com/Dallinger/Dallinger/issues/2518
