### ISSUE TITLE
Incorporate model into Mafia game

### ISSUE THREAD

**Issue by omonida** [Dallinger/Dallinger#2522]
During the daytime phases of the Mafia game, we would like to show the bystanders who is suspected as mafia according to a pre-trained model. What would be the best way to use such a model in the game for live experiments? Currently I am testing in debug by loading the model from my machine.

* Dallinger version used: 6.5.0
* Operating System and version (desktop or mobile): macOS
* Browser and version (e.g. Chrome 39, node.js 5.4): Chrome
* Link to your project: https://github.com/vaelgates/vaelgates_dallinger_demos/tree/master/mafia

**Comment by jacobyn** [comment]
Perhaps we move this to the help channel? It seems like a slack channel issue.

**Comment by omonida** [comment]
I see, should I close the issue here and post directly in the help channel?
