### ISSUE TITLE
Change dependency pinning in Dallinger

### ISSUE THREAD

**Issue by silviot** [Dallinger/Dallinger#2610]
Motivation and Context
----

Dallinger currently explicitly pins all versions of its dependencies.
This has the advantage of letting users specify a single pin in their experiment's requirements.txt file and have this imply all other pins.
However, this simplicity comes at the expenses of rigidity: Dallinger pins might conflict with third party ones.
Also, when an experiment specifies additional dependencies there is no assistance to the Dallinger user to pin those requirements to ensure repeatability. Also see #2445

Proposal
--------

The code that runs and deploys an experiment will be augmented to consume the `requirements.txt` file in the experiment directory and use `pip-compile` to produce a `constraints.txt` file alognside it.
If a `constraints.txt` file is already found next to a requirements.txt file, the existing one will be used saving on startup time and enabling repeatability.
The requirements.txt file that will be fed to Heroku and to Docker will have the contents of the `constraints.txt` file.

A new `constraints.txt` file can be generated deleting the old one and re-running dallinger.

The setup.py will be simplified. `setup_utils.py` will be removed.
Text files with requirements will exist in two incarnations:

* manually edited, ending in `.in`
* machine generated by `pip-compine`, ending in `.txt`

and will have to be used explicitly. Their content will derive from the current ones.

Continuous Integration
----------------------

As new versions of Dallinger dependencies are released they can potentially break Dallinger functionalities.
A CI job will be configured to run daily with the latest versions of all dependencies.
In case it starts failing a new Dallinger version can be released with an amended setup.py explicitly pinning out the defective dependency.

Regular CI jobs will instead run on a `build-requirements.txt` file generated manually by developers using `pip-compile` and checked into the repository.

Relying on the currently configured bot that opens PRs when new releases of dependencies come out might also be an option to get monitoring of failures due to new releases.

Risks
-----

This is a very sensitive part of the package, as any mistakes might prevent some users to use Dallinger altogether.
The existing tests should however mitigate these risks.
Using a newer Dallinger version with an experiment that pins a lower version not including this change will still yield the same versions as before: in that case `pip-compile` will output all the explicit pins that come with that Dallinger version.

A new dependency to `pip-tools` should be added to use the `pip-compile` script.
`pip-tools` has only `click` as a dependency, and Dallinger already depends on `click`.

**Comment by alecpm** [comment]
@silviot This sounds great to me! Thanks for putting so much thought into this proposal!

**Comment by silviot** [comment]
@pmcharrison 
In my view Dallinger's `setup.py` should specify its dependencies using pinnings only for versions that are known to cause problems. Users might get different versions depending on when they install Dallinger, but in case something goes wrong (for instance dependency XYZ version 2.0.3 used to work, but now XYZ 2.1.0 is out and for some reason it breaks Dallinger) we can:

* point the users to the `constraints.txt` file
* specify Dallinger can't work with the new version, by changing its dependency to `XYZ<2.1.0`

This approach has the advantage of keeping the decisions about versions separate from the list of versions we depend on.

I don't feel it's needed, but for peace of mind we could add a `dallinger[pinned]` extra that would work "the old way", pinning everything down.

The "one big venv for all experiments" approach should work fine with this proposal as well.

It is my understanding that if a user has Dallinger 7.0.0 installed and they run it on an experiment that specifies `dallinger==6.0.0` in its requirements.txt, the experiment worker and http server should run on version `6.0.0`. This is the behaviour I'm implementing with docker and the one I expect to be the current one with heroku.
