### ISSUE TITLE
Add config.txt option controlling notify_duration_exceeded behaviour: 3pts

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2617]
A process runs in the Dallinger clock that checks for a database inconsistency problem (see description by @thomasmorgan in #2309). If this problem is detected, then autorecruit is currently disabled. This behaviour is controversial (see discussion in #2309). 

Proposal: to add a config.txt option that determines whether to disable autorecruit on this occasion, as originally suggested by @alecpm on the Slack discussion of August 25th 2020. We can still send the warning email, just not disabling autorecruit.

**Comment by thomasmorgan** [comment]
Isn't this what the 'clock_on' parameter already does? At least when we first made it this was the only thing the clock does, so turning it off will solve your problem. If the clock is on, but an extra parameter prevents it from disabling autorecruit, then the clock process checks for the error but does nothing when it finds it, so you might as well turn it off anyway, no?

**Comment by pmcharrison** [comment]
That was our original solution, but now we want to use the clock for other processes too, so disabling it is no longer an option :-)

**Comment by thomasmorgan** [comment]
Ah ok, makes total sense. Just out of interest, is the plan to provide a means to allow users to add new clock processes with ease?

Then again, is this not duplicating the function of background tasks? The auto-recruit clock process could just be turned into a background task, no? Is there anything the clock can do that the background tasks can't?

**Comment by jacobyn** [comment]
That's was our original implementation using  background tasks to do some background work. The problem with this is that rarely the worker dyno dies and there is nothing that restarts the background process cue. It happen to us in an experiment this week. We discussed it with Jazkarta and it seems that clock are robust to restarts (https://devcenter.heroku.com/articles/scheduled-jobs-custom-clock-processes) so there is an advantage of using the clock for something like that.

**Comment by thomasmorgan** [comment]
Worrying that background tasks can die. Does this suggest we should move the entire background task system to clock processes? If clocks are just a better way of doing this than background tasks maybe we should switch rather than use both in parallel.

**Comment by pmcharrison** [comment]
Yes, I would support that decision. Dallinger itself doesn't use background tasks, nor does its demos. I think the term background task is a little misleading actually because the tasks just run once, on launch. I would instead call them something like 'post-launch routes'.

**Comment by thomasmorgan** [comment]
Interesting. In my usage they aways run forever, but I only because I wrap their contents in a while loop! But I guess this is not the intended behavior, as you say they are spawned only once, and immediately after launch. But running repeatedly in the background is what a clock process is supposed to do, so it will be more robust.

I guess this means there might be use cases for both systems. The clock for persistent, repeated checks. The background tasks for something that runs only once, but is intensive enough it can't be integrated into the foreground for some reason.
