### ISSUE TITLE
Expose the ability to schedule clock processes: 8pts

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2639]
Currently experimenters are encouraged to use the `background_tasks` Experiment property to schedule background tasks. These background tasks are executed once upon app startup. Recurring tasks are then defined using `while` loops. Unfortunately, this setup is not robust to node restarts.

A better alternative would be to use the periodic scheduler from `heroku/clock.py`. This scheduler is currently used only to run the `check_db_for_missing_notifications` function. We want to be able to specify custom processes in the Experiment class that will be registered in this scheduler. Bill Thompson has implemented something similar in his Dallinger fork (see [here](https://github.com/billdthompson/Dallinger/blob/multiple-clock-supervision/dallinger/experiment.py) and [here](https://github.com/billdthompson/Dallinger/blob/multiple-clock-supervision/dallinger/heroku/clock.py)).

**Comment by alecpm** [comment]
PR (#2850) is ready for review.
