### ISSUE TITLE
Print log message describing backup to S3: 1pts

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2729]
As described in #2710, Dallinger automatically backs up the output of `dallinger export` to S3. We would like the log messages to inform the user that this backup is happening, including printing the name of the bucket. This backup functionality was news to us :-)

**Comment by jessesnyder** [comment]
@pmcharrison @jacobyn This look OK?
```
A copy of your export was saved to Amazon S3!
	bucket name: dallinger-a40479cf
	bucket URL: https://dallinger-a40479cf.s3.amazonaws.com/7c703c9c-d562-9d94-82f4-3189e0e1ee71-data.zip
```

**Comment by pmcharrison** [comment]
Great! Will that precise link ever work if the S3 bucket is not public? Is maybe an AWS console link more appropriate? Something like this:

```
https://s3.console.aws.amazon.com/s3/object/dallinger-a40479cf?region=us-east-1&prefix=7c703c9c-d562-9d94-82f4-3189e0e1ee71-data.zip
```

That way the user won't get an Access Denied message if they follow the link.

**Comment by jessesnyder** [comment]
@pmcharrison No idea about the visibility of the URL. Upon further reflection I think it may just be the unique identifier we construct to register the bucket (it may not actually be an accessible resource). Maybe I overreached by adding a URL. How did you construct the s3 URL in your example?

**Comment by jessesnyder** [comment]
(Maybe I could get that URL from the bucket via https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.BucketWebsite ... I'll need to deploy another experiment to check)

**Comment by pmcharrison** [comment]
Yes, I expect the URL will not be visible (if it is, then there are serious data protection implications)! I constructed that URL myself just by navigating to the appropriate page on the S3 console. It would be easy to generate this programmatically, though potentially brittle if they change the console in the future.

**Comment by jessesnyder** [comment]
I went ahead with constructing the URL based on the various bits:
```
A copy of your export was saved also to Amazon S3:
 - bucket name: dallinger-a40479cf
 - S3 console URL: https://s3.console.aws.amazon.com/s3/object/dallinger-a40479cf?region=us-east-1&prefix=3a69e3dc-11d2-87b5-ed87-38c6a64041f4-data.zip
```

**Comment by pmcharrison** [comment]
Great!
