### ISSUE TITLE
Social chatroom pending transmissions

### ISSUE THREAD

**Issue by mongates** [Dallinger/Dallinger#274]
## Expected Behavior

I've been editing the social chatroom demo. When there are multiple pending transmissions, the transmissions are not correctly ordered by timestamp. 
## Current Behavior

See Postico image below. Creations times for the last four transmissions are reversed compared to the receive times.
![](https://cloud.githubusercontent.com/assets/18468901/19610747/f3d2859c-9792-11e6-9856-38c4e78b2198.png)

**Comment by cguardia** [comment]
Is this the chatroom demo under Dallinger/demos? Any tips for reproducing this?

**Comment by mongates** [comment]
This is the chatroom demo under Dallinger/demos! I haven't checked this recently, but to reproduce you should just be able to send a whole bunch of words really quickly from one chatroom window and see if they display in the right order in another window. (Also, very occasionally when I do this, sent words don't show up at all.)

**Comment by cguardia** [comment]
I was able to confirm that once in a while a word gets lost when typing quickly, but messages always came in the right order, so probably that's not an issue anymore? @suchow Do you want me to try anything else here?

**Comment by suchow** [comment]
@cguardia I don't think we've done anything that would have fixed this, so my guess is that we don't yet have a way to reliably reproduce this.

My *guess* is that it's this line of `models.py`, which loops through `pending_transmissions` to set the `receive_time` property, but may not do so in a way that respects the order in which the transmissions were sent.

**Comment by cguardia** [comment]
PR: https://github.com/Dallinger/Dallinger/pull/694
