### ISSUE TITLE
create a new route to access the config file

### ISSUE THREAD

**Issue by thomasmorgan** [Dallinger/Dallinger#275]
If we put lots of properties in config we will want to access these values from the front end. We should make a route to do this, here's an example:

```
@custom_code.route('/config/<prop>', methods=['GET'])
def config_property(prop):
    """Get a property from the config file by name."""
    p = dallinger.config.experiment_configuration.prop
    return success_response(field=prop, data=p, request_type=prop)
```

Note that this only gives the front end access to the experiment_configuration section of the config file which is probably important for safety

**Comment by thomasmorgan** [comment]
@suchow what do you think?

**Comment by suchow** [comment]
This is good, though we'll need to filter out any configuration variables that are sensitive (e.g., AWS keys). Doing this now.

**Comment by vlall** [comment]
I recall this being implemented at the home route /
