### ISSUE TITLE
DiscreteGenerational network's add_node is broken

### ISSUE THREAD

**Issue by thomasmorgan** [Dallinger/Dallinger#280]
The DiscreteGenerational network will always break when the add_node method is run once you get past the first generation.

## Expected Behavior
This part of add_node
```
prev_agents = Node.query\
                .filter_by(failed=False,
                           network_id=self.id,
                           generation=(curr_generation - 1))\
                .all()
```
should get all the nodes in the previous generation. It does this by filtering by generation.

## Current Behavior
Remember that generation is not a base property of nodes, rather, to use the discretegenerational network you have to define a subclass of Node that has a generation expression. However, because the query queries all Nodes, it breaks because you are trying to filter by a property that base class Node doesnt have. You get this error:

```
InvalidRequestError: Entity '<class 'dallinger.models.Node'>' has no property 'generation' 
```

## Steps to Reproduce (for bugs)
Run any experiment with a discrete generational network that does not entirely overwrite the add_node method and get into the 2nd generation.

## Suggested Fix
I think the best fix is to query over the type of node that you are adding, so the query becomes:

```
prev_agents = type(node).query\
                .filter_by(failed=False,
                           network_id=self.id,
                           generation=(curr_generation - 1))\
                .all()
```

This won't always work as if you have multiple types of node in the network it won't check them all, but in that case you are better off just overwriting the method

**Comment by suchow** [comment]
@thomasmorgan Safe to close this now that #281 is merged?

**Comment by thomasmorgan** [comment]
yep!
