### ISSUE TITLE
Custom server: urgent CLI commands

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2844]
#2761 (custom server deployment) creates the need for extending several pre-existing CLI commands to support custom servers. Some of these are urgent, some are less so. Here are the urgent ones:

`dallinger apps`
`dallinger deploy`
`dallinger export`
`dallinger destroy`
`dallinger sandbox`

**Comment by silviot** [comment]
I don't think `dallinger load` needs to be changed to work with docker ssh deployments: it starts a local server in debug mode using the heroku CLI and loads an archived database.

**Comment by pmcharrison** [comment]
Oops... I misremembered what it did. I'll edit the description.

**Comment by silviot** [comment]
Implemented in #2863
