### ISSUE TITLE
Installing dallinger in a directory with a space: 2 pts

### ISSUE THREAD

**Issue by raja-marjieh** [Dallinger/Dallinger#2861]
Installing dallinger in a directory with a space (e.g. "Google Drive") results in the following error message when sandboxing. The error disappears when dallinger is reinstalled in a directory without a space.

![image](https://user-images.githubusercontent.com/64031078/117454096-0916e900-af46-11eb-826a-0376d703b935.png)

**Comment by Luke-Poeppel** [comment]
This issue seems to be related to the following function in the utils:
https://github.com/Dallinger/Dallinger/blob/0ea737e6e3f4485c4140625deeab164fa6c5a442/dallinger/utils.py#L354-L363

I could resolve this by simply switching the return statement to
```
return os.path.dirname(egg_link)
```
My apologies if I'm missing something!

**Comment by alecpm** [comment]
@raja-marjieh Could you check if replacing that line with `return open(egg_link).readlines()[0].strip()` fixes the issue for you? I was not able to reproduce the issue directly, but I believe I understand the cause. I opened a PR with this proposed fix at #3038
