### ISSUE TITLE
MTURK Dashboard: Typo in extend_mturk_hit

### ISSUE THREAD

**Issue by mangl001** [Dallinger/Dallinger#2893]
When using the MTURK panel in the dashboard to extend a HIT, the command generated (see screenshot1) has a typo and, therefore, does not work (see screenshot2). I'm using Dallinger 7.2.0. I understand that it should be with hyphens, not underscores, namely: `dallinger extend-mturk-hit`

![s1](https://user-images.githubusercontent.com/33897368/118158761-821db100-b41c-11eb-90b6-a2dcf359a76c.png)

![s2](https://user-images.githubusercontent.com/33897368/118158763-834ede00-b41c-11eb-9da0-0099312a618a.png)

**Comment by jacobyn** [comment]
This should be solved by using: `extend-mturk-hit ` instead of `extend_mturk_hit`. I think this is now solved in version 7.2.1.
