### ISSUE TITLE
Use technologies from XDATA program?

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#293]
http://opencatalog.darpa.mil/XDATA.html#

**Comment by suchow** [comment]
We now use [odo](https://github.com/blaze/odo) from the Blaze project, funded by XDATA.

**Comment by vlall** [comment]
I participated in this project for over a year and can help with this if we ever needed to revisit this.

**Comment by vlall** [comment]
Closed and moved to milestone "Suggestions for Dallinger improvement"
