### ISSUE TITLE
dallinger.load() gives misleading error message

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2935]
Suppose you write an `experiment.py` file that tries to import an unavailable package (e.g. you haven't installed it yet). This will throw an `ImportError`, which is normally informative and helps you to debug the problem. However, `dallinger.load` catches `ImportError`s silently, and then only later throws a misleading error message: `"No experiment classes found"`. I propose adjusting the logic here to make the `ImportError` catch more strict, so it doesn't suppress meaningful error messages.

**Comment by alecpm** [comment]
@pmcharrison I think I may need a little more info on how to reproduce this. The current code appears to re-raise any `ImportError` that occurs when importing the experiment (though it tries a few different import paths before eventually re-raising the error).

The only time `"No experiment classes found"` should come up is when the module is importable, but there are no subclasses of `dallinger.experiment.Experiment` found in it (in which case that error message seems pretty accurate and I'm not sure how to supplement it).

If I try to import a non-existent module in the experiment module, I immediately get an `ImportError` or `ModuleNotFoundError` raised with a traceback in the commandline's `verify_package` function.

**Comment by pmcharrison** [comment]
Hi @alecpm, I just reproduced it by going to the MCMCP demo and adding `import asd` (a made-up package that I don't have installed) to it:

<img width="882" alt="Screenshot 2021-06-04 at 17 42 20" src="https://user-images.githubusercontent.com/22684998/120835424-38784000-c55c-11eb-85fc-f1ed516c850a.png">

<img width="1031" alt="Screenshot 2021-06-04 at 17 42 29" src="https://user-images.githubusercontent.com/22684998/120835450-3f06b780-c55c-11eb-89c9-9759d9f63b4d.png">

**Comment by alecpm** [comment]
@pmcharrison So I'm still seeing the same thing I was seeing yesterday:
```
  File "/Users/alecmitchell/.local/share/virtualenvs/Dallinger-3xPAAVH4/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/alecmitchell/Development/bundles/ucb_wallace/Dallinger/dallinger/command_line/utils.py", line 68, in wrapper
    if not verify_package(kwargs.get("verbose")):
  File "/Users/alecmitchell/Development/bundles/ucb_wallace/Dallinger/dallinger/command_line/utils.py", line 83, in verify_package
    verify_experiment_module(verbose),
  File "/Users/alecmitchell/Development/bundles/ucb_wallace/Dallinger/dallinger/command_line/utils.py", line 146, in verify_experiment_module
    from dallinger_experiment import experiment
  File "/var/folders/60/gry957xd62l876g8j5yrfg7h0000gn/T/tmpavorh9zo/TEMP_VERIFICATION_PACKAGE/experiment.py", line 16, in <module>
    import asd
ModuleNotFoundError: No module named 'asd'
```

Which happens almost immediately when running `dallinger debug`, `dallinger sandbox`, `dallinger deploy`, or `dallinger docker deploy`. Is this occurring on dallinger `master`? Perhaps this was incidentally fixed at some point? Or are you using another Dallinger command that's triggering this?

**Comment by pmcharrison** [comment]
@alecpm apologies for my incomplete information, that was bad on my part. I was using a CLI alias and didn't realise quite what I was running.

The real way to reproduce the issue was by running `from dallinger.experiment import load; load()`.

However, you're absolutely right that the `verify_package` function catches such problems early and provides the correct error message. The problem is only observed when one skips that step. So, probably the sensible conclusion is not to change anything in Dallinger, but for me simply to ensure that this `verify_package` is called prior to running `load()`.

**Comment by pmcharrison** [comment]
If you're happy with this summary, please feel welcome to close the issue and mark it as done.

**Comment by alecpm** [comment]
@pmcharrison In that case, I believe I have a simple fix that should help with similar issues using `experiment.load()`. I've made a small PR to improve exception handling/logging: https://github.com/Dallinger/Dallinger/pull/2997
