### ISSUE TITLE
Put Docker documentation on readthedocs.io: 3 pts

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2957]
The Docker support documentation [here](https://github.com/Dallinger/Dallinger/blob/b52192414e19d897620dc08628293aee6f141c94/docs/source/docker_support.rst) is great, can we put it on readthedocs.io now?

**Comment by silviot** [comment]
The last version that has documentation on readthedocs is 6.6.0. I'm not sure if there was an automatic step that needs to be re-enabled (I was not able to find it) or if it needs a manual push.

**Comment by jessesnyder** [comment]
Looks like the problem is that ReadTheDocs is using python 3.6 to build, and ipython does not support that version. We should be able to tell RTD to use a newer version:
https://docs.readthedocs.io/en/stable/config-file/v2.html#python

**Comment by alecpm** [comment]
It looks like the python version change wasn't sufficient, because the docs need Dallinger installed in order to build:

https://readthedocs.org/projects/dallinger/builds/14252821/

I think that should be a relatively straightforward fix, but might require some trial and error.

**Comment by alecpm** [comment]
It worked: https://dallinger.readthedocs.io/en/latest/docker_support.html

**Comment by pmcharrison** [comment]
Closed as completed
