### ISSUE TITLE
Recurrent bug in HITs submission

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#3028]
Some participants experience problems submitting Dallinger HITs. Upon activating the automatic dallinger error notification system, we realized that these are actually more common than what we thought

We’ve been noticing an influx of unexplained errors for a while. These errors fall into two main types

- “Default” type error
- “already_started_mturk_HIT” error

This is the notification table from postico:

![image](https://user-images.githubusercontent.com/10518584/122435053-f1e10780-cf97-11eb-9192-b7bc1ad7497f.png)

This is the notification email sent to us
![image](https://user-images.githubusercontent.com/10518584/122434899-cc53fe00-cf97-11eb-85ff-a7cc945c3a8a.png)

Investigating the notification column in the database in multiple experiments, we realized that these bugs are triggered by a problem in HIT submission, whereby the HIT “freezes” upon submitting it. 
Some participants mentioned that they get stuck on a “Loading next HIT…” blank page (which appears after finishing the experiment)

This is what the participant see (from an email that we received):
![image](https://user-images.githubusercontent.com/10518584/122434986-e261be80-cf97-11eb-9f0d-3013a03e0b92.png)

Some additional information:
The assignment_id for these notifications appear to be either “unknown” or in brackets.
Participant id appears to be “null” even though the participant appears in the Participant table

![image](https://user-images.githubusercontent.com/10518584/122435134-04f3d780-cf98-11eb-8262-fdc10d1df6c8.png)
![image](https://user-images.githubusercontent.com/10518584/122435150-09b88b80-cf98-11eb-8e97-0d9b704fcad6.png)

Paper trial logs:
![image](https://user-images.githubusercontent.com/10518584/122435213-1b019800-cf98-11eb-9d54-3b8aad19e0c8.png)

**Comment by jacobyn** [comment]
Here are presentation with information we gathered on this issue: https://docs.google.com/presentation/d/1F-qz3RDscHjAdxyaaYoNbq5Y3hPAaG7hq2hXfXAcq38/edit?usp=sharing

**Comment by raja-marjieh** [comment]
there's also this, maybe relevant
![image](https://user-images.githubusercontent.com/64031078/122444452-d7f7f280-cfa0-11eb-9839-3816034bb76a.png)

**Comment by raja-marjieh** [comment]
It could be that this bit of dallinger code under `if participant is not None:` is what's adding the tuples participant / assignment ids we're seeing in the error msgs
![image](https://user-images.githubusercontent.com/64031078/122795119-48628480-d2bd-11eb-9cc7-68f7b51a1ce2.png)

**Comment by jessesnyder** [comment]
@raja-marjieh Well spotted. You're absolutely right that this creates tuple inappropriately when populating data for the error page, which in turn gets saved in the database. I've fixed this bug (not yet merged), but I don't think it's related to our other problems, so I'll continue to research these.

**Comment by pmcharrison** [comment]
@jessesnyder we did start wondering whether it could be a PsyNet-specific problem... it would be impossible for you to debug if so! We can add you to our GitLab repository if you share your email address?

**Comment by jessesnyder** [comment]
@pmcharrison I'm not sure I want to open up the field of inquiry that much yet. I'll let you know if I think I need access to that.

**Comment by pmcharrison** [comment]
OK, good to know!
________________________________

**Comment by jessesnyder** [comment]
I traced the case illustrated in this screenshot:
https://user-images.githubusercontent.com/10518584/122435213-1b019800-cf98-11eb-9d54-3b8aad19e0c8.png

The logging is a bit misleading, and this may be what's feeding your concerns in this _particular_ case. The notification sent by MTurk includes the assignment ID and HIT ID, but not a participant ID (of course, since that's a Dallinger value), and we log the last line in the screenshot _before_ looking up the particpant ID based on the assignment ID. If we fail to find an participant, there will be another log message about that.
