### ISSUE TITLE
Dallinger generate-constraints should not use the latest versions

### ISSUE THREAD

**Issue by silviot** [Dallinger/Dallinger#3033]
`dallinger generate-constraints` should embed the python constraints of the currently running dallinger version (or the one specified in the experiment `requirements.txt`) instead of pulling in the latest ones.

This is not a problem if a new package we depend on is released when it doesn't require a compiler. But when it does (like `psycopg`, that had two releases in the past three days) it will break dallinger for no reason.

**Comment by pmcharrison** [comment]
Great find!

**Comment by pmcharrison** [comment]
Closed as completed
