### ISSUE TITLE
Unable to get Bartlett Demo to work

### ISSUE THREAD

**Issue by ayushchakravarthy** [Dallinger/Dallinger#3062]
## Expected Behavior
To work right out of the box after the installation process as in the documentation.

## Current Behavior
Raises error pkg_resources.VersionConflict: (dallinger 7.4.0 (/home/a/anaconda3/lib/python3.8/site-packages), Requirement.parse('dallinger==6.6.0'))

## Steps to Reproduce (for bugs)
Installed Dallinger exactly as in the documentation and tried to demo in order to verify installation is successful. However, the error says that I need to have a different version of dallinger installed. 

Is it as simple as changing the pip install dallinger[data] to pip install dallinger[data]==6.6.0? 
Thanks!

**Comment by pmcharrison** [comment]
Hi @ayushchakravarthy, sorry to hear about this! We think we might have fixed this now. Can you try with the latest Dallinger version?

**Comment by pmcharrison** [comment]
Closed because of lack of response
