### ISSUE TITLE
HIT was submitted twice - Failed to approve assignement Error

### ISSUE THREAD

**Issue by fotinidelig** [Dallinger/Dallinger#3072]
## Current Behaviour
When participants try to submit twice/refresh the submit page an error "Failed to approve assignement" is triggered with the following output:

`dallinger.mturk.MTurkServiceException: Failed to approve assignment 34QN5IT0T2G6HMWH25AHYCMAK3608U, {'id': '34QN5IT0T2G6HMWH25AHYCMAK3608U', 'status': 'Approved', 'hit_id': '3U18MJKL1WA8S1G7ULNIMQIIED9NCW', 'worker_id': 'A12IHTKQFQIPD1'}: An error occurred (RequestError) when calling the ApproveAssignment operation: This operation can be called with a status of: Submitted (1625139618656)`

It might also be due to some other delays.

## Expected Behavior
It might be best if this doesn't generate an error output since it will happen a few times from participants and it's unsolvable by whomever is running the experiment

**Comment by jessesnyder** [comment]
@fotinidelig The next release (currently dealing with some complications but hopefully out within a few days) will move MTurk qualification creation and assignment to a background worker, which will speed up the response on questionnaire submission _drastically_. I think this will make the double-submit scenario much less common. 🤞🏼 

P.S. Compliments on the "Spirited Away" github avatar. :-)
