### ISSUE TITLE
The `master` branch should have a version higher than the latest released one, marked as alpha

### ISSUE THREAD

**Issue by silviot** [Dallinger/Dallinger#3145]
Currently the `master` branch keeps the latest released version until a new release is performed.

This can lead to some confusion, since it's effectively a different version.

To mitigate this the `master` branch could use the next minor version that the latest released one marked as alpha. This way it can also safely pre-released, and users who want to test the latest changes before an official release could use the alpha, while other users would not be affected by the possibly buggy release.

Related to #3184

**Comment by jessesnyder** [comment]
@silviot I'll make this change right after the next release.

**Comment by jessesnyder** [comment]
Complete; closing
