### ISSUE TITLE
MTurk Qualification Assigment Errors

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#3152]
## Expected Behavior
MTurk qualification assignment should be handled by a Heroku worker dyno, without error.

## Current Behavior
Seeing a lot of this in the Papertrail logs:
```
 Jul 22 02:11:41 dlgr-ising-int1-3aggr app/worker.1 2021-07-22 09:11:41,129 Response body:
Jul 22 02:11:41 dlgr-ising-int1-3aggr app/worker.1 b'{"__type":"RequestError","Message":"You have already created a QualificationType with this name. A QualificationType\'s name must be unique among all of the QualificationTypes created by the same user. (1626945101122)","TurkErrorCode":"AWS.MechanicalTurk.QualificationTypeAlreadyExists"}'
Jul 22 02:11:41 dlgr-ising-int1-3aggr app/worker.1 2021-07-22 09:11:41,130 Response headers: {'x-amzn-RequestId': 'cc81809e-fe1c-4578-a39e-7b1bc634356f', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '286', 'Date': 'Thu, 22 Jul 2021 09:11:40 GMT', 'Connection': 'close'}
```

## Context
Live experiment, heroku ID ising-int1-3aggr

## Your Environment
* Dallinger version used: 7.5.0

**Comment by jessesnyder** [comment]
I looked through the Papertrail logs in detail, in conjunction with reviewing the related code, and I'm pretty confident that although the log entries look concerning, what we're actually seeing is expected behavior.

Every time we assign an experiment-specific qualification to a worker, we don't know whether the qualification itself exists yet. Rather than query for it by name, we just try to create it, and catch the exception if it already exists. All of this back-and-forth with MTurk gets dumped into the logs, so it's hard to sort out signal from noise.

Additional explanation in the context of looking at Papertrail:
https://www.screencast.com/t/AZQ9uLAPcD

@pmcharrison @jacobyn Does this explanation seem plausible? Are there additional symptoms you're seeing that suggest there is in fact a bug here? (Implicitly cc-ing Manu, though he doesn't appear to have access to the ticket thread.)

**Comment by pmcharrison** [comment]
Thanks @jessesnyder, that's really helpful to hear! Do you think there's any way (long-term) of sanitising the logs a little to stop experimenters from getting worried here?

**Comment by jessesnyder** [comment]
I'm pretty sure we've discussed this problem before, and @alecpm was pessimistic about suppressing the mturk/boto3 output, but I'll do some Googling.

**Comment by pmcharrison** [comment]
Fair enough! It might be an impossibly time-consuming task. What do you think about making a little doc page that accumulates common log messages and their explanations? Might be an efficient way to deal with this problem!

**Comment by jessesnyder** [comment]
There are some ideas here, of varying vintage :-)
https://stackoverflow.com/questions/1661275/disable-boto-logging-without-modifying-the-boto-files

Maybe try a couple of these methods to see if they're effective?

The documentation path you suggest may be more effective, unfortunately, since when something really _does_ go wrong, it's extremely helpful to have these requests and responses logged.
