### ISSUE TITLE
add --archive option to docker deployment: 5pts

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#3324]
The --archive flag allows to deploy from an existing experiment in a form of a exported data. 
This is not currently supported in docker deployment (heroku and server). We would like to add support to --archiv to these deployment option. This can make use of a local deployment if it is simplifies the implementation. The use case is a situation were we take off an exeperiment and want to continue - possibly after some minor and compatible changes to the code.

**Comment by pmcharrison** [comment]
Closed as completed
