### ISSUE TITLE
Discussion: Custom recruiter configuration

### ISSUE THREAD

**Issue by fmhoeger** [Dallinger/Dallinger#3355]
We want to integrate a further recruiting system, like e.g. LUCID.

What would be the best way to organize/specify LUCID-specific variables?
Two options come to mind:

1. Prepend LUCID-specific variables with ‘lucid_’. 
2. Use a `[Lucid]` section like e.g.:
```
[Lucid]
num_participants = 100
bucket = xyz
demography = lucid_us_adults.json
qualifications = lucid_musicians.json
acceptable_payment_range = 5.00, 7.50
``` 
Leverage the section as defined in `config.txt` and do something like config.get(“Lucid”, “bucket”).

In both cases also resolve references to LUCID-specific configuration files like e.g. `lucid_us_adults.json`.

**Comment by pmcharrison** [comment]
Advice from @jessesnyder - adopt option 1, where we prepend with `lucid_`.
