### ISSUE TITLE
Create Jupyter notebooks on binder for each demo

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#336]
The format for hosting interior directories on [binder](http://mybinder.org) is:
`mybinder.org/repo/Dallinger/Dallinger/notebooks/dallinger/demos/Bartlett1932/index.ipynb`

**Comment by vlall** [comment]
I think we decided it would be more useful to make a binder for nice demonstrations of dallinger where we have already collected the data.

**Comment by vlall** [comment]
this could be the demos or it could be experiments designed by other experimenters
