### ISSUE TITLE
error with incorrectly-specified MTurk payment amount

### ISSUE THREAD

**Issue by mongates** [Dallinger/Dallinger#337]
If the MTurk payment amount isn't correctly specified in the .config file when an experiment is run, and the experiment is then deployed, the entire experiment will launch and show no errors on the shell console. However, the URLs of the experiment will not be displayed, and the experiment will have not launched on MTurk. The error listed from papertrails logs about the server was:

" dlgr-f3eda974 app/web.2: *** reward must have format [dollars].[cents]"

## Expected Behavior
The payment error should be caught before the experiment is attempted to be launched.

## Current Behavior
The experiment currently deploys and then fails to materialize on MTurk without overt error messages.

## Steps to Reproduce (for bugs)
1. Set payment to "1" for example instead of "1.00"
2. dallinger deploy

**Comment by thomasmorgan** [comment]
@suchow we could add a config check function to dallinger verify - seems like a good place to catch this, what do you think?

**Comment by vlall** [comment]
Fixed in 3027f0f369df42686bf6974a9b17fdf3826a6697, where TypeErrors are resolved using `config.py.`
