### ISSUE TITLE
Document what dallinger_email_address and dallinger_email_password are used for

### ISSUE THREAD

**Issue by jhamrick** [Dallinger/Dallinger#342]
These seem to be keys that are required in the config file, but I can't find any documentation on what they are supposed to be or what they are used for. I assumed maybe the email address is an email address that will be contacted on error? But I really don't know what the password field is supposed to be. Presumably it is not the password for my email address (I hope)? That is currently what the name implies, though, which is also a bad idea from a UI standpoint (we don't want people giving out the passwords to their email accounts).

**Comment by thomasmorgan** [comment]
These are not documents as the feature no longer works following an update to gmail security (see issue #171)

In brief, when the feature worker, experimenters could create a throwaway gmail account which Dallinger could use to send emails. Emails were sent when Dallinger detected the db had entered an inconsistent state which implied that a notification from AWS had failed to arrive. Such instances are very rare, but very problematic. Dallinger either auto-fixed the issue, or, if it couldnt be autofixed, stopped the experiment, and then sent the experimenter an email from the throwaway account letting them know what had happened.

So the password field is the password the for the email address, but it should not be your email address, rather it should be a throwaway account for the purposes of Dallinger notifications. However, as I said, this feature no longer works as gmail no longer lets Dallinger access accounts so we have blocked the emailing feature while we look for a better solution (Dallinger will still autofix/pause experiments as necessary). Currently those values are needed in the config file but they can be anything (e.g. "hello").

Let me know if something is unclear

**Comment by jhamrick** [comment]
At the very least then can we add to the documentation that they aren't
needed but are being reserved for future use?

**Comment by thomasmorgan** [comment]
yep, or even better we can comment out the code that loads them and just remove them from the config entirely for now

**Comment by vlall** [comment]
This has been clarified: https://github.com/Dallinger/Dallinger/pull/1081
