### ISSUE TITLE
Prolific recruiter: 8pts

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#3499]
See related PR: #3535 

This issue is now replaced by #3732, the current issue is maintained to keep track of the discussion.

We want to be able to recruit from prolific using their recent API:
https://prolificapi.docs.apiary.io/#reference/studies/actions-on-one-study

Part of the issue is to understand what is the best way to do it.

As a user you will be able to specify the usage of the prolific recruiter in the config.txt
As a user you will be able to specify information regarding the definition of the HIT in the config.txt

Note about the implementation:
Dynamic recruiting is not possible in prolific, so this means that once the initial number of participants is set no more additional recruiting can be done.

Note that prolific have a fixed end route.

Note that prolific  support bonuses and this should be implemented in the initial implementation.

At a later stage we may want to consider to implement #1958 that allows the use of multiple HITs for the same app and therefore allows for dynamic recruiting via micro-batching, but this is not supposed to be part of the initial implementation (unless it is an essay to do it).

We have a group prolific account, and I can share it's credentials.

**Comment by jessesnyder** [comment]
Example study (HIT) POST request body:
```
{
  "id": "60d9aadeb86739de712faee0",  # Do we get to specify this?
  "name": "Study about API's",
  "internal_name": "Study about API's version2",
  "description": "This study aims to determine how to make a good public API",
  "external_study_url": "https://mysite.com?PROLIFIC_PID={{%PROLIFIC_PID%}}&STUDY_ID={{%STUDY_ID%}}&SESSION_ID={{%SESSION_ID%}}",
  "prolific_id_option": "question",  # This will be some other value to indicate URL param
  "completion_code": "7EF9FD0D",  # Do we get to specify this?
  "completion_option": "url",
  "total_available_places": 30,
  "estimated_completion_time": 5,
  "reward": 13,
  "device_compatibility": [
    "desktop"
  ],
  "peripheral_requirements": [],
  "eligibility_requirements": "TODO",
  "status": "UNPUBLISHED"
}
```

Error example:
```
{
  "error": {
    "status": 403,
    "title": "You do not have permission to perform this action.",
    "detail": "You don't have permission to view user data",
    "error_code": 140301,
    "additional_information": "/api/v1/errors/",
    "interactive": false
  }
}
```

**Comment by jessesnyder** [comment]
@jacobyn The API for bonuses seems a little weird. It looks like you have to register all the participant bonuses in one call, and then make a second call to pay them all. Does this sound right to you?
https://prolificapi.docs.apiary.io/#reference/bonuses/set-up-bonus-payment

**Comment by pmcharrison** [comment]
It seems plausible to me. Not sure how you're meant to get hold of 'Bulk bonus payment id' in the second call, though? I guess you'll work that out!

**Comment by jessesnyder** [comment]
@jacobyn @pmcharrison I've requested an API key, but haven't heard back yet. Do you have a key I can use in the meantime?

**Comment by pmcharrison** [comment]
I'm afraid I don't have one :-(

**Comment by jessesnyder** [comment]
I'm starting to think no one does, based on some correspondence on the message board at Prolific. Still on the chase, though. ;-)

**Comment by jessesnyder** [comment]
@jacobyn @pmcharrison Do you know which Study status we should use when we create a Study? `ACTIVE`, I'm guessing?

![Prolific_API_for_researchers_·_Apiary](https://user-images.githubusercontent.com/63560/140433740-2d983f67-f77a-4d01-9c46-46b468a06752.png)

**Comment by pmcharrison** [comment]
Sounds plausible, yes!

**Comment by jacobyn** [comment]
If the app is ready to receive traffic (participants) we should use "active". If not, we should the "unpublished" status and then activate the study when we're ready.

**Comment by jessesnyder** [comment]
Eligibility requirements will be a case where you just pass in some kind of JSON object in config, but I'm not yet clear on the exact format. Here are the API docs:

![Prolific_API_for_researchers_·_Apiary](https://user-images.githubusercontent.com/63560/140435724-f8b4f988-d91b-484f-9604-866e2930673a.png)

**Comment by jessesnyder** [comment]
> If the app is ready to receive traffic (participants) we should use "active". If not, we should the "unpublished" status and then activate the study when we're ready.

@jacobyn So this will need to be a config variable, then?

**Comment by pmcharrison** [comment]
Maybe it starts off as unpublished but then automatically gets marked as active once the launch route is called? I'm not sure there's a use case for us to have a study as unpublished long-term.

**Comment by jacobyn** [comment]
Why did this not merged to master? Can we actually try this implementation somehow? @jessesnyder

**Comment by jessesnyder** [comment]
I was just thinking about this earlier today because I got an email about something else from Prolific (I'm now on mailing lists, of course). They never got back to me about an API key, despite the fact that I talked to multiple people and received assurances/promises. I'll rattle someone's cage, but I suspect their API might still be vaporware to some degree. 🦄

**Comment by jacobyn** [comment]
Another option would be to provide a solution based on the prolific site (assuming you set up manually the app). Bill Thmposon wrote something like that based on the generic recruiter:

`@pysnooper.snoop()
def convert_prolific(
       self,
       entry_information
):
   """Convert prolific default url parameters
   into the format required for dallinger to
   maker a participant.
   See https://researcher-help.prolific.co
   /hc/en-gb/articles/360009220993-Recording-participants-Prolific
   -IDs-in-your-study-survey"""
   mappings = {
       'PROLIFIC_PID': 'worker_id',
       'STUDY_ID': 'hit_id',
       'SESSION_ID': 'assignment_id'
   }
   # if a participant arrives with no url args
   if not ('entry_information' in entry_information):
       return entry_information
   converted = entry_information.copy()
   for k, v in mappings.items():
       if k in converted['entry_information']:
           converted[v] = (
               converted['entry_information'][k]
           )
   return converted


@pysnooper.snoop()
def normalize_entry_information(
       self, entry_information
):
   """Accepts a dictionary with information about a recruited user. Returns
   a dictionary containing data the needed to create or load a Dallinger
   Participant. The returned data should include valid ``assignment_id``,
   ``worker_id``, and ``hit_id`` values. It may also include an
   ``entry_information`` key which should contain a transformed
   ``entry_information`` dict which will be stored for newly created
   participants.
   By default, the extraction of these values is delegated to the
   recruiter's `normalize_entry_information` method.
   Returning a dictionary without valid ``hit_id``, ``assignment_id``, or
   ``worker_id`` will generally result in an exception.
   """
   # retrieve from recruiter
   entry_data = self.recruiter.normalize_entry_information(
       entry_information
   )
   # convert prolific standards
   converted_entry_data = (
       self.convert_prolific(entry_data)
   )
   # fake the neccesary credentials if not present
   # just for debugging purposes
   if not converted_entry_data["worker_id"]:
       converted_entry_data[
           "worker_id"
       ] = generate_random_id()
   if not converted_entry_data["assignment_id"]:
       converted_entry_data[
           "assignment_id"
       ] = generate_random_id()
   if not converted_entry_data["hit_id"]:
       converted_entry_data[
           "hit_id"
       ] = generate_random_id()
   return converted_entry_data


def exit_info_for(self, participant):
   """An experiment can return a dictionary of infomation that will
   be shown to the participant at the very last point in their
   lifecycle, if the HIT is not submitted to an external recruitment
   service for submission.
   For complete control over the exit page, a customized version of
   the ``exit_recruiter.html`` template can be included in the experient
   directory, and this will override the default provided by Dallinger.
   :param participant: the ``Participant`` instance for which to calculate
       an exit value
   :returns: ``dict`` which may be rendered to the worker as an HTML table
       when they submit their assigment.
   """
   return {
       "Prolific Completion Code": "CODEGOESHERE",
       "Base Pay": participant.base_pay,
       "Bonus": participant.bonus,
   }`

**Comment by jacobyn** [comment]
```
@pysnooper.snoop()
def convert_prolific(
       self,
       entry_information
):
   """Convert prolific default url parameters
   into the format required for dallinger to
   maker a participant.
   See https://researcher-help.prolific.co
   /hc/en-gb/articles/360009220993-Recording-participants-Prolific
   -IDs-in-your-study-survey"""
   mappings = {
       'PROLIFIC_PID': 'worker_id',
       'STUDY_ID': 'hit_id',
       'SESSION_ID': 'assignment_id'
   }
   # if a participant arrives with no url args
   if not ('entry_information' in entry_information):
       return entry_information
   converted = entry_information.copy()
   for k, v in mappings.items():
       if k in converted['entry_information']:
           converted[v] = (
               converted['entry_information'][k]
           )
   return converted


@pysnooper.snoop()
def normalize_entry_information(
       self, entry_information
):
   """Accepts a dictionary with information about a recruited user. Returns
   a dictionary containing data the needed to create or load a Dallinger
   Participant. The returned data should include valid ``assignment_id``,
   ``worker_id``, and ``hit_id`` values. It may also include an
   ``entry_information`` key which should contain a transformed
   ``entry_information`` dict which will be stored for newly created
   participants.
   By default, the extraction of these values is delegated to the
   recruiter's `normalize_entry_information` method.
   Returning a dictionary without valid ``hit_id``, ``assignment_id``, or
   ``worker_id`` will generally result in an exception.
   """
   # retrieve from recruiter
   entry_data = self.recruiter.normalize_entry_information(
       entry_information
   )
   # convert prolific standards
   converted_entry_data = (
       self.convert_prolific(entry_data)
   )
   # fake the neccesary credentials if not present
   # just for debugging purposes
   if not converted_entry_data["worker_id"]:
       converted_entry_data[
           "worker_id"
       ] = generate_random_id()
   if not converted_entry_data["assignment_id"]:
       converted_entry_data[
           "assignment_id"
       ] = generate_random_id()
   if not converted_entry_data["hit_id"]:
       converted_entry_data[
           "hit_id"
       ] = generate_random_id()
   return converted_entry_data


def exit_info_for(self, participant):
   """An experiment can return a dictionary of infomation that will
   be shown to the participant at the very last point in their
   lifecycle, if the HIT is not submitted to an external recruitment
   service for submission.
   For complete control over the exit page, a customized version of
   the ``exit_recruiter.html`` template can be included in the experient
   directory, and this will override the default provided by Dallinger.
   :param participant: the ``Participant`` instance for which to calculate
       an exit value
   :returns: ``dict`` which may be rendered to the worker as an HTML table
       when they submit their assigment.
   """
   return {
       "Prolific Completion Code": "CODEGOESHERE",
       "Base Pay": participant.base_pay,
       "Bonus": participant.bonus,
   }
```

**Comment by jessesnyder** [comment]
Finally got an email back from Prolific (integrations@prolific.co) :

Hello Jesse,

Our apologies for not getting back to you sooner. And we hope it's not too late! We're the Integrations team at Prolific - thank you for reaching out to us.

Currently, you can integrate with Prolific either via URL Parameter or using API.

The easiest way to kickstart an integration is to set up a call with us via this [Calendly link](https://calendly.com/integrations-15/prolific-integrations). In the call, we can explore your needs and offer support faster.

Prolific Developer Platform

1. Create Study via URL Parameter

Create your Prolific study in 1 click without manually copying experiment parameters. You can find the documentation here.

2. API

Use our API to connect with your platform directly to manage studies and submissions. You would need an API token for this. Please reply to this email with the following:

- The email you use for Prolific
- A summary of what you hope the integration would do and who it is for

We look forward to speaking with you.


Best wishes,

Integrations Team

**Comment by jessesnyder** [comment]
@jacobyn Do you want to craft the answer to "A summary of what you hope the integration would do and who it is for"?

**Comment by jacobyn** [comment]
Hi @jessesnyder  happy new year! Thank you for pushing this. How about something like: " The dallinger platform (https://github.com/Dallinger/Dallinger/) is one of the leading open source platforms for automation of large scale complex experiments that involves interaction between participants. So far, the dallinger platform used exclusively Mturk for recruiting and we are now want to add a Prolific integration. Since the dallinger platform is highly automated we are  interested in using Prolfic API  to manage studies and submissions using an API token. We plan to release the integrated code as part of dallinger so it can be used by labs who uses dallinger to create complex experiments and recruit from Prolific. At the debug stage we need a key to test the integration and run test experiments". Maybe you introduce/involve me in the email, so that I can take/initiate this call?

**Comment by jessesnyder** [comment]
Happy new year! That sounds perfect, @jacobyn. I'll send the introduction email today.

**Comment by jessesnyder** [comment]
Which email address should I use for you on the CC?

**Comment by jacobyn** [comment]
slacking you! :)

**Comment by jacobyn** [comment]
This issue is now replaced by #3732, the current issue is maintained to keep track of the discussion.

**Comment by jacobyn** [comment]
@jessesnyder regardng your question about bonus. I think one should use in our case [Set up bonus payment](https://www.prolific.co/docs/api-docs/public/#tag/Bonuses/paths/~1api~1v1~1submissions~1bonus-payments~1/post ) call rather than a bulk bonus payment. This will be more appropriate (see the new specification)

**Comment by jessesnyder** [comment]
Initial draft complete; closing
