### ISSUE TITLE
Bump to python 3.10? (Now supported on heroku)

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#3514]
https://devcenter.heroku.com/articles/python-support

There are some nice improvements it would be nice to have.

**Comment by jessesnyder** [comment]
Two initial steps:
1. Add latest supported python version to tox matrix
2. Nori and company will try doing a Heroku deployment with this version

If these both work:
3. Add 3.10.x to officially supported list
4. revisit whether to update the default heroku deployment version

**Comment by jacobyn** [comment]
@fmhoeger can you please document your findings ASAP as we discussed?

**Comment by fmhoeger** [comment]
@jacobyn I made a comment in the PR (https://github.com/Dallinger/Dallinger/pull/3747#issuecomment-1024816044). The problem we had is fixed now and the corresponding code already merged into master, see https://github.com/Dallinger/Dallinger/pull/3772 . It would take some extra work to document this now after the fact.

**Comment by jessesnyder** [comment]
Complete; closing
