### ISSUE TITLE
Fatal vulnerability to AWS service errors when recruiting

### ISSUE THREAD

**Issue by thomasmorgan** [Dallinger/Dallinger#359]
I was running a small experiment today and an error occurred when recruiting more participants. Given Dallinger's current form, this error is effectively unfixable (unless you manually spend a lot of time fixing the database), moreover, it started a death spiral where participants were recruited only to be failed and for more participants to be recruited and so on. Fortunately I think there is a relatively easy fix, but more details below.

## The error
When an assignment submitted notification is received, Dallinger does a bunch of things, culminating in exp.submission_successful() and exp.recruit(). In my experiment, submission_successful() does a number of vital things. recruit() determines whether or not to recruit and if so sends a request to the recruiter. When recruiting, the recruiter changes the HIT in 2 ways: first it adds the requested number of assignments, secondly, it extends the duration of the hit to provide enough time for participants to take part. The latter of these caused an error, here is the server logs:

```
Dec 14 17:26:18 dlgr-3da1e17f app/worker.1:  Starting Dallinger's recruit_participants. 
Dec 14 17:26:18 dlgr-3da1e17f app/worker.1:  hit_id is 3BC9H1KCYUCXCJSNMIHJJKAK7X8YWM. 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:  2016-12-15 01:26:18,845 - dallinger.db - ERROR - Exception during scoped worker transaction, rolling back. 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:  Traceback (most recent call last): 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/db.py", line 30, in sessions_scope 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:      yield local_session 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/db.py", line 63, in wrapper 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:      return func(*args, **kwargs) 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:    File "/app/custom.py", line 1244, in worker_function 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:      exp.recruit() 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:    File "/app/dallinger_experiment.py", line 59, in recruit 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:      self.recruiter().recruit_participants(n=config.generation_size) 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/recruiters.py", line 192, in recruit_participants 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:      float(expiration_increment or 0) * 3600)) 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/boto/mturk/connection.py", line 545, in extend_hit 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:      return self._process_request('ExtendHIT', params) 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/boto/mturk/connection.py", line 821, in _process_request 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:      return self._process_response(response, marker_elems) 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/boto/mturk/connection.py", line 836, in _process_response 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:      raise MTurkRequestError(response.status, response.reason, body) 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:  MTurkRequestError: MTurkRequestError: 200 OK 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:  <?xml version="1.0"?> 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:  <ExtendHITResponse><OperationRequest><RequestId>40edbd76-7b35-48da-b28e-5e69b8aae031</RequestId></OperationRequest><ExtendHITResult><Request><IsValid>False</IsValid><Errors><Error><Code>AWS.ServiceUnavailable</Code><Message>There was an error with this request. (System error code: 1001 1481765178839)</Message></Error></Errors></Request></ExtendHITResult></ExtendHITResponse> 
Dec 14 17:26:19 dlgr-3da1e17f app/worker.1:  2016-12-15 01:26:18,847 - dallinger.db - ERROR - Exception during scoped worker transaction, rolling back.
```

It is not clear to me why this caused an error. The code that determines the amount of time required is flagged as the offender: `float(expiration_increment or 0) * 3600))`, however, this has run without fault on all previous occasions so perhaps it could just be that AWS was having difficulties.

## Why this is really bad
This error caused the db to rollback to the start of the assignment submitted notification code, meaning that it undid all the essential changes made by submission_successful(). However, dallinger had already requested more participants from AWS (that part of the request was successful) and this could not be undone. So, the db was no longer in a state suitable for more participants to arrive, but several slots had been opened on MTurk. Moreover, whenever these participants tried to take part, the bad state of the db caused errors and so Dallinger re-recruited replacement participants - this is the death spiral.

## Solutions
We can't stop AWS from failing, but there are a number of measures that would have stopped this problem:
1. Commit to the db after submission successful, but prior to recruit. This means that even if the AWS requests fail, the worst that will happen is that the experimenter will need to manually extend the HIT.
2. Have the recruiter add time to the HIT before adding participants. This means that the very last thing Dallinger does following a submitted notification is add participants - so participants are only added if the notification is processed successfully in its entirety.
3. Put all the requests to AWS in try/except. So if they fail the whole notification processing doesn't break.

I suggest implementing all 3, along with traceback printouts and informative print statements in the except brackets so the experimenter is not left confused by what happened.

**Comment by suchow** [comment]
@thomasmorgan Can this be closed now that we've merged the protections into `development`?

**Comment by thomasmorgan** [comment]
yep
