### ISSUE TITLE
Prolific recruiter - more specification - 13pts

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#3732]
### High Level Task Breakdown/Questions/Mullings
- [x] Prolific API wrapper (prolific.py) and tests(!) Given that there's no sandbox, I think some kind of isolation tests will be the best we can do. Probably wise not to get too ambitious here.
- [x] Iron out details of recruiter
    - [x] `close_recruitment()` - do we want to implement this?
    - [x] Change signature of `Recruiter.reward_bonus` to take the worker ID (may as well pass all the things a recruiter might need)
    - [x] Implement `reward_bonus()`
    - [x] Implement `recruit()` based on new Prolific API (see below... it's a PATCH call). We'll need a way to determine the _current_ number of participants, because the way this Prolific API works is to provide a _new total_, not a number to increment by
    - [x] We'll need `self.is_in_progress` (check if a Study/HIT is already running when calling `open_recruitment()`) Maybe we store the current study ID in redis the same way we now do for the MTurkRecruiter.
    - [x] I don't think we can re-use `reward`, because iirc in Prolific this is an hourly rate, not a lump sum
- [x] Config system: which variables belong as Dallinger vars, and which get dumped in prolific_recruitment_config.json or whatever we want to call it
- [x] Questions:
    - [x] Do we want to use `prolific_` as a config var prefix, or `prolific:`? I prefer the later, since it's clearer it's a prefix, but the mturk keys don't follow this, so maybe that ship is sailed if we prefer to maximize consistency
    - [x] How do we decide which configuration keys go in dallinger config variables? Maybe the answer is "as few as possible"? Only ones that are "generic" (title, description, base_pay, etc.)? Or maybe the required ones get top-level status and the optional ones go in the special file?
    - [x] Ideas on how to determine total current participants (see above)? ~Persist it?~ Query it?
- [x] Incorporate PR feedback
- [x] Do we want/need Prolific API integration tests to run on CI? **Answer: YES**
    - [x] Get Prolific API token into Github CI secrets
    - [x] Update CI test config to run with the required pytest flags
- [x] Get CI passing if possible - currently docker tests fail because of new configuration keys
- [x] Documentation
    - [x] Some general docs about Prolific recruitment lifecycle
    - [x] Other?
- [x] Clean up

-------------

This issue continues  (and replaces) #3499. It contains more detailed specification of the implementation.

### Preliminaries:
	
1. Prolific API can be found here: https://www.prolific.co/docs/api-docs/public/
2. We have a Dallinger account with an API token, slack me if you need it.
3. We have a computational audition account + API token that can be also used for additional testing (slack me if you need it).
4. We have a joining slack channel for support with the prolific integration team, please let me know if you want to join it.
5. Previously we thought that prolific is not supporting dynamic recruiting (namely changing the number of participants after the survey is started). In the API documentation this is explicitly mentioned as impossible. However, discussing the integration with the Prolific people they told us that they will share with us an undocumented feature that allow to update recruitment after the survey had started. I am giving the detailed answer near the “recruit” method.
6. The API of prolific is versioned, we should have a way to define the prolific API version via a parameter. Currently we only plan to actively support the current API version (v01).
7. Prolific does not have a sandbox environment - to do testing we will have to use active participants. Nori will reserve funds for that, and you can use these funds for testing. If more money is needed we can set this up.

### Recruiting parameters:

1. All the main recruiting parameters should be specified in the config.txt under the [prolific] section. Recruiting parameters that are relevant to prolific should have a name that starts with “prolific_” (namely: prolific_parameter_name = value)
2. Some parameters like “description” seems to overlap so much that we think that can be directly used (namely use the same variable name for Mturk and Prolific experiments, as the description is really the same thing across recruiters).
3. Secondary recruiting parameters are going to be stored in a file specified in prolific_recruitment_config = filename. This allows adding optional parameters, without declaring them on dallinger, allowing also for API changes in prolific without changing much in dallinger. This is similar to how we treat an additional qualification file in the current dallinger. Use something like: recruitment_config=json.loads(self.config.get("prolific_recruitment_config"))
4. The prolific API token should be specified in .dallinger_config.txt in the same way that the Mturk credentials are specified.
5. There should be a way for the recruiter class to access this security token as it is needed in order to make API calls.
 

### Recruiter methods to implement:

**Open_recruitment**
should call “Create a draft study” (https://www.prolific.co/docs/api-docs/public/#tag/Studies/paths/~1api~1v1~1studies~1/post)
Here is a list of the parameters. 

-` Name`- specified in the config by the user (config)
- `Description`- description of the study for the participants to read before starting the study; this is conceptually identical to Mturk’s “description” field and maybe reusing the same variable, as here the two variables really mean the same thing.
- `External_study_url`- dallinger provides this to Prolific this is the deployed app URL (for example https://dlgr-nori-app.herokuapp.com/)
- `Prolific_id_option `- should always be “url_parameters”, as we always receive participants with url parameters specifying their prolific ID.
- `Completion_code`- this is a “secret” code used to finalize the study, supposed to be not known to users before completing the HIT. We need to provide here a long randomized string.
- `Completion_option `- should be always “url” since we are always redirecting the user rather than giving him a code to type manually.
- `Total_available_places` - this is initial recruit size
- `Estimated_completion_time` - need to be specified in the config as a parameter (this parameter maybe can be called “prolific_est_duration” that is different then “duration” that in the M-turk case represents the maximal duration (typically longer than the actual duration).  
- `Reward`-this is like ”base_payment”: in Prolific maybe it should be called prolific_base_payment, alternatively we can reuse the same variable.
- `device_compatibility` - parameters taken from `prolific_recruitment_config`
- `Peripheral_requirements` - parameters taken from `prolific_recruitment_config`
-` Eligibility_requirements` - parameters taken from prolific_recruitment_config (typically this is empty for everyone).
- `status`	 - initially should be 'UNPUBLISHED' but then changed to 'ACTIVE'  at the end of the recruitment.
In the end of the process it should also revoke the Publish a draft study API call to finalize.

**Normalize_entry_information-** 
It is possible to configure what kind of URL prolific is creating but typically it will have the following form:
```

?PROLIFIC_PID={{%PROLIFIC_PID%}}&STUDY_ID={{%STUDY_ID%}}&SESSION_ID={{%SESSION_ID%}}
PROLIFIC_PID  is like Mturk’s “worker_id”
STUDY_ID is like “hit_id”
SESSION_ID is like “assignment_id”

```
The parameters can be translated to these values by the proper normalized entry information. Note that we discovered a related bug in #2652, however in this case this should work nevertheless. 

**Recruit** 
This should increment the current count of participants. Prolific will provide us with help on how to do it. But this will likely start with the “Get a study” API call to know the current number of participants and based on the number of recruited participants we will increment and update the participant count. So imagine that the function is called with n=10, and we currently have 70 participants recruited as indicated by the call to “Get a study” then the resulting update will be of 80 participants.

Here is the note from prolific how this can be done:
Doing a PATCH on the study and modifying the total_available_places is enough to do so.

```
url = f"{PROLIFIC_API_BASE}/api/v1/studies/{study_id}/"
requests.request(
    "PATCH", url, headers={
        "Authorization": f"Token {prolific_token}",
        "Content-Type": "application/json",
    }, data=json.dumps({"total_available_places": total_available_places + 3})
)
```
 
As we said before, this can only be done for normal requirements, not for representative samples or quota studies. 
The new number of places must be more than the current number of places taken. So increasing always works, but decreasing the number of places might return an error.
 
A final check we do is that the account must have enough available balance to pay for the extra places.

**close_recruitment**
Change the status of the experiment to 'PAUSED' or maybe 'COMPLETED' (not sure here?)

**Assign_experiment_qualifications**
This is not going to be implemented in the first stage, we may need another discussion on how to implement qualifications in cases that this is not supported (for example we can create our own key value system like qualification). 

**Compensate_worker** - delay implementation of this function to a later stage (open an issue for it)?

**exit_response** 
Should be customized to HIT the completion route.
Dallinger should apply this API call upon completion (Execute status transition): 	
https://www.prolific.co/docs/api-docs/public/#tag/Submissions/paths/~1api~1v1~1submissions~1{id}~1transition~1/post

Note that prolific has a getter API function (Get submission details) that allows you to get the status of a submission (a submission is similar to a HIT in mturk). Implementing the execute status transition may start with calling the Get submission details API function to test the validity of the transition (though I am not sure this is needed).   

**Reward_bonus**
Use Prolific API call (bonuses) :https://www.prolific.co/docs/api-docs/public/#tag/Bonuses

**Notify_duration_exceeded**: no need to implement

**Rejects_questionnaire_from**:not sure if needed to be implemented

**Submitted_event**:not sure if needed to be implemented.

**Comment by jonasanso** [comment]
@jacobyn I will do small comments with some details, improvements and/or clarifications so you can update this issue later on
In create study draft we also need
`maximum_allowed_time` : Max time in minutes for a participant to finish the submission. Submissions are timed out if it takes longer. Make sure it is not too low. At least two minutes plus two times the estimated time plus two times the square root of the estimated time. 

It was previously missing from the documentation. We plan to make it optional but for now is mandatory.

**Comment by jonasanso** [comment]
In the study create or update never send the status instead use the transition endpoints to change the status https://www.prolific.co/docs/api-docs/public/#tag/Studies/paths/~1api~1v1~1studies~1{id}~1transition~1/post 

A study is always created as a draft and to start recruiting it needs to transition to ACTIVE using the action PUBLISH

```
url = f"{PROLIFIC_API_BASE}/api/v1/studies/{study_id}/transition/"
requests.request(
    "PATCH", url, headers={
        "Authorization": f"Token {prolific_token}",
        "Content-Type": "application/json",
    }, data=json.dumps({"action": "PUBLISH"})
)
```

**Comment by jonasanso** [comment]
Recruitment does not need to be explicitly closed, in general when there number of completed submissions is equal to the total number of places for the study the study automatically transitions to a status AWAITING_REVIEW and when all submissions are approved it automatically updates to COMPLETED 

If a submission is rejected while in AWAITING_REVIEW the study automatically goes to ACTIVE and recruits new participants to get to the total number of places requested.

But if Dallinger needs to actively close recruitment, calling the transition endpoint with the action "STOP" will make sure that no more participants are requested.

**Comment by jonasanso** [comment]
On **Compensate_worker**

Submissions are automatically approved after 21 days (of course we prefer researchers that approve submissions sooner) 
So if you want to delay working on it, is not a blocker.

When a submission is approved the participant gets paid. 

Approving a submission or a set of submissions is not complicated and bonuses should also not be too complicated to handle.

**Comment by jonasanso** [comment]
On **Rejects_questionnaire_from**

We have documented how to reject a single submission https://www.prolific.co/docs/api-docs/public/#tag/Submissions/paths/~1api~1v1~1submissions~1{id}~1transition~1/post but there is also a bulk operation.

If in the future this is implemented, we can support on it.

**Comment by jessesnyder** [comment]
@jacobyn Related to increasing number of recruits:
> A final check we do is that the account must have enough available balance to pay for the extra places.

Would it be OK to just try and fail, rather than making an API call to check balance first?

**Comment by jacobyn** [comment]
> @jacobyn Related to increasing number of recruits:
> 
> > A final check we do is that the account must have enough available balance to pay for the extra places.
> 
> Would it be OK to just try and fail, rather than making an API call to check balance first?

Yes, exactly! You don't need to make an API just try and fail would be absolutely OK.

**Comment by jonasanso** [comment]
> @jacobyn Related to increasing number of recruits:
> 
> > A final check we do is that the account must have enough available balance to pay for the extra places.
> 
> Would it be OK to just try and fail, rather than making an API call to check balance first?

Absolutely, I only mentioned the validations we do so you are aware of the kind of errors you are going to receive.
In any case, our errors follow a standard format and you can log them for the final user to decide what action to take.

**Comment by jacobyn** [comment]
Regarding:
> Implement recruit() based on new Prolific API (see below... it's a PATCH call). We'll need a way to determine the current number of participants, because the way this Prolific API works is to provide a new total, not a number to increment by

and

> Ideas on how to determine total current participants (see above)? Persist it? Query it?

@jessesnyder 
My initial idea was this, so making another API call to "know" the current recruited people, and then make transparent and identical logic to the current dallinger recruit logic. Namely:

Recruit - should increment the current count of participants. This will likely start with the “Get a study” API call to know the current number of participants and based on the number of recruited participants we will increment and update the participant count. So imagine that the function is called with n=10, and we currently have 70 participants recruited as indicated by the call to “Get a study” then the resulting update will be of 80 participants.

**Comment by jessesnyder** [comment]
@jonasanso Does the `reward` property of a study represent a lump sum, or an hourly rate?

**Comment by jonasanso** [comment]
> @jonasanso Does the `reward` property of a study represent a lump sum, or an hourly rate?

Lump sum in cents

**Comment by jessesnyder** [comment]
@jonasanso I see I can delete studies through the website UI. Is there (or are there plans for) a DELETE API for studies? This would be very helpful for testing/development.

**Comment by jessesnyder** [comment]
@jonasanso I was able to deploy a study to Heroku, but I can't figure out how to access the study URL as a participant would see it, including the additional URL parameters (my understanding is that these parameters will be appended to the URL we provide Prolific when constructing the public URL shown to participants). I tried signing up as a participant, but I'm only offered to get on the waitlist.

![Prolific](https://user-images.githubusercontent.com/63560/151261210-357c12e5-f7a7-4dde-abfc-52182ef22098.png)

**Comment by jessesnyder** [comment]
@jacobyn Looks like assignment rejection might require some thought, given that there are predefined reasons, and a >= 100 character explanation is also required:

![API_doc](https://user-images.githubusercontent.com/63560/151262794-11d47b6c-9bb0-4d5a-9395-ea1f1821df07.png)

**Comment by jessesnyder** [comment]
Remembering now that we never, or almost never, reject a submission, at least on MTurk. Maybe the same principle applies here?

**Comment by jessesnyder** [comment]
Reviewing the MTurkRecruiter, it looks like we never reject an assignment. Instead we just quietly mark the data as bad internally and probably pay no bonus, but the base pay is still give. I'm guessing we will do the same with Prolific.

**Comment by jacobyn** [comment]
yes. @jessesnyder we never reject a HIT. We will do the same with prolific. The user can always modify the bonus but the "base" payment is given regardless.

**Comment by jacobyn** [comment]
@jessesnyder regarding the study URL. This is something *we* provide to prolific based on the heroku deployment. Here is my description above for this issue:
**External_study_url**- dallinger provides this to Prolific this is the deployed app URL (for example https://dlgr-nori-app.herokuapp.com/)

**Comment by jacobyn** [comment]
@jonasanso it maybe useful for us to get an account where we are in the role of a participant - is that possible to organize this on your end?

**Comment by jonasanso** [comment]
> @jonasanso I was able to deploy a study to Heroku, but I can't figure out how to access the study URL as a participant would see it, including the additional URL parameters (my understanding is that these parameters will be appended to the URL we provide Prolific when constructing the public URL shown to participants). I tried signing up as a participant, but I'm only offered to get on the waitlist.
> 
> ![Prolific](https://user-images.githubusercontent.com/63560/151261210-357c12e5-f7a7-4dde-abfc-52182ef22098.png)

@jessesnyder please add to the external study URL the parameters

external_study_url=https://heroku.com?recruiter=prolific&PROLIFIC_PID={{%PROLIFIC_PID%}}&STUDY_ID={{%STUDY_ID%}}&SESSION_ID={{%SESSION_ID%}}

You can also tweak the parameter names to suit your needs.

**Comment by jonasanso** [comment]
@jessesnyder once you have created a study draft, you can go to the study page and run a test using the `Preview` button. That will provide you with the link the participant will use with some mock data for the prolific id and session id.

**Comment by jonasanso** [comment]
> @jonasanso I see I can delete studies through the website UI. Is there (or are there plans for) a DELETE API for studies? This would be very helpful for testing/development.

You can delete a draft study using the API send a DELETE to https://api.prolific.co/api/v1/studies/{id}/
You can not delete a study once is published.

**Comment by jessesnyder** [comment]
> once you have created a study draft, you can go to the study page and run a test using the Preview button. 
Thanks, @jonasanso... that's what I was looking for and don't know how I failed to see it. For some reason I expected it to be at the top of the page.

**Comment by jessesnyder** [comment]
Since I don't see my study available for the regular "worker" account, I tried running though it in "Preview" mode. This raised an error when Dallinger tried to approve the submission. I guess that this might simply be because it was a preview rather than a real session. @jonasanso Do you know if this is the case?
```
"URL": "https://api.prolific.co/api/v1/submissions/035orbpf1pk3/transition/", 
"args": {
    "json": {"action": "APPROVE"}
}, 
"response": {
    "error": {
        "status": 405, 
        "title": "Method \"{method}\" not allowed.", 
        "error_code": 100000, 
        "detail": "Method \"POST\" not allowed.", 
        "additional_information": "/api/v1/errors/", 
        "interactive": false
    }
}
```

**Comment by jonasanso** [comment]
Yes that's right. The submission id is fake in the preview.

**Comment by jessesnyder** [comment]
@jonasanso I'm getting an error on study submission which I don't understand:

![Prolific](https://user-images.githubusercontent.com/63560/151881912-3b5c3af5-89e0-484d-ad84-9cf88d425ad8.png)

The URL I'm visiting here is:
https://app.prolific.co/submissions/complete?cc=0PODNCPX

This completion code matches what I see in the study details:

![Prolific](https://user-images.githubusercontent.com/63560/151882101-6057ba6d-6b51-4c4e-8c5c-37776bdbe901.png)

When I view the submission history, I see this:

![Prolific](https://user-images.githubusercontent.com/63560/151882367-ebe575d4-6dbb-4c83-86b8-9bb7d17de71e.png)


Any ideas?

**Comment by jessesnyder** [comment]
I'm confused about what I see in various places for bonus amounts. This study has a single submission for a single worker:

API call:
```
{'study_id': '61f85cb3c0fdc9abd96a4320', 'csv_bonuses': '61f2914e3bb4b4d40080a6ec,0.01'}
```

Worker UI:
![Prolific](https://user-images.githubusercontent.com/63560/151883528-e15e3325-4502-4712-a10a-ce08a6ff2c15.png)

Researcher UI:
![Prolific](https://user-images.githubusercontent.com/63560/151883674-3ba55d25-2d98-4265-a03f-a96e7b3d05fd.png)

Is it currency localization that's confusing me here?

**Comment by jessesnyder** [comment]
> Recruitment does not need to be explicitly closed, in general when there number of completed submissions is equal to the total number of places for the study the study automatically transitions to a status AWAITING_REVIEW and when all submissions are approved it automatically updates to COMPLETED
> 
> If a submission is rejected while in AWAITING_REVIEW the study automatically goes to ACTIVE and recruits new participants to get to the total number of places requested.
> 
> But if Dallinger needs to actively close recruitment, calling the transition endpoint with the action "STOP" will make sure that no more participants are requested.

@jacobyn I will need your thoughts here, on whether we want to implement this, or leave it as a no-op, as it is in the `MTurkRecruiter`.

**Comment by jessesnyder** [comment]
@jacobyn There are still some possible issues with approval (see above), but there's also a chance this whole thing will just work at this point. :flushed: 

We should touch base tomorrow and figure how to do some more realistic integrated testing. In particular, I'm thinking about rolling recruitment, which is maybe a little tricky.

**Comment by jonasanso** [comment]
> @jonasanso Another one for you, but this is probably my own lack of understanding.
> 
> I'm confused about what I see in various places for bonus amounts. This study has a single submission for a single worker:
> 
> API call:
> 
> ```
> {'study_id': '61f85cb3c0fdc9abd96a4320', 'csv_bonuses': '61f2914e3bb4b4d40080a6ec,0.01'}
> ```
> 
> Worker UI: ![Prolific](https://user-images.githubusercontent.com/63560/151883528-e15e3325-4502-4712-a10a-ce08a6ff2c15.png)
> 
> Researcher UI: ![Prolific](https://user-images.githubusercontent.com/63560/151883674-3ba55d25-2d98-4265-a03f-a96e7b3d05fd.png)
> 
> Is it currency localization that's confusing me here?

I think is the change in currency what is giving problems, all the operations you do with the API and in the UI as a researcher are in your prolific researcher currency. 

Ideally in Dallinger, the researcher should use the same currency as in Prolific to make things simpler, you can ask it for a configuration parameter or you can get the currency calling the `/users/me/` endpoint. 

At the moment you have 2 researcher accounts one in $ and one in £

**Comment by jonasanso** [comment]
> We should touch base tomorrow and figure how to do some more realistic integrated testing. In particular, I'm thinking about rolling recruitment, which is maybe a little tricky.

I think for rolling recruitment the best is to recruit actual participants, alternatively, we can give you a longer list of participants ids (maybe all the integrations team + your current testing accounts, about 7 in total) an do a coordinated test.

**Comment by jonasanso** [comment]
> @jonasanso I'm getting an error on study submission which I don't understand:
> 
> ![Prolific](https://user-images.githubusercontent.com/63560/151881912-3b5c3af5-89e0-484d-ad84-9cf88d425ad8.png)
> 
> The URL I'm visiting here is: https://app.prolific.co/submissions/complete?cc=0PODNCPX
> 
> This completion code matches what I see in the study details:
> 
> ![Prolific](https://user-images.githubusercontent.com/63560/151882101-6057ba6d-6b51-4c4e-8c5c-37776bdbe901.png)
> 
> When I view the submission history, I see this:
> 
> ![Prolific](https://user-images.githubusercontent.com/63560/151882367-ebe575d4-6dbb-4c83-86b8-9bb7d17de71e.png)
> 
> Any ideas?

Is it p[ossible that you arrived to the complete URL with a browser logged in as a researcher or as a participant that was not the participant taking the study

> https://app.prolific.co/submissions/complete?cc=0PODNCPX

I think I know what is the problem.
The expected flow is:
- User is doing the experiment and the submission is Active
- User finishes the experiment 
- User is redirected to the URL https://app.prolific.co/submissions/complete?cc=0PODNCPX and the submission is Awaiting Review
- Dallinger approves the submission

What happened is:
- User is doing the experiment and the submission is Active
- User finishes the experiment and Dallinger approves the submission
- User is redirected to the URL https://app.prolific.co/submissions/complete?cc=0PODNCPX and fails 

The reason we fail is because our code on `submissions/complete` would move the Submission back to Awaiting Review and nobody wants that, once the submission is approved the submission can be returned but not move back to awaiting review.

We have 2 solutions:
- Dallinger approves the submissions at a later step or with a delay giving time to the redirect to have done their work first.
- At Prolific we handle this unexpected order of actions and we only update the completion code and do not change the status of the submission

@jessesnyder @jacobyn please let us know if the first option is possible, we will try to evaluate the impact of this change in the flow and see if it is possible for us to accommodate this unexpected flow.

**Comment by jessesnyder** [comment]
@jonasanso Something I'd seen last week gave me the impression that if I attempted to approve an unsubmitted session I'd get an error, and I relied on this to deal with the race condition of submit vs approve. If this is not the case I'll need to explicitly check the status of the worker session, retrying until it's Awaiting Review. Does that sound right?

**Comment by jonasanso** [comment]
@jessesnyder I think that would be best to check the status before approving them.

**Comment by jessesnyder** [comment]
Thanks, @jonasanso - this seems to be working well!

**Comment by pmcharrison** [comment]
Closed as completed
