### ISSUE TITLE
Migrate to new way datetimes are localized

### ISSUE THREAD

**Issue by fmhoeger** [Dallinger/Dallinger#3841]
Get rid of following warnings in the log output:

`PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html`

**Comment by jessesnyder** [comment]
This is a duplicate of https://github.com/Dallinger/Dallinger/issues/3793

**Comment by fmhoeger** [comment]
Yes, just recognized that, too.
