### ISSUE TITLE
Have the ad print the url of the server in sandbox mode

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#393]
When multiple HITs are posted under the same ad group on MTurk, it's impossible to tell which is which without looking at the URL of the image on the ad. It would be better if the experiment UUID was immediately obvious.

## Expected Behavior
Experiment UUID is visible on MTurk sandbox ad.

## Current Behavior
Experiment UUID is not visible on MTurk sandbox ad.

## Steps to Reproduce (for bugs)
1. Launch experiment in sandbox mode.
2. View ad on MTurk sandbox.

**Comment by vlall** [comment]
Fixed by adding a config item for the application ID, which gets inserted into the jinja2 template depending on the mode.
