### ISSUE TITLE
Handling of repeat participants

### ISSUE THREAD

**Issue by jhamrick** [Dallinger/Dallinger#407]
It seems that if participants exit the experiment, and then click the "begin experiment" button again, Dallinger will detect that they are already in the experiment and not return an error. However, it also will not return the participant id, which ends up resulting in an error.

## Expected Behavior

1. If the participant has completed the experiment, and clicks "begin experiment" again (somehow), they should be redirected to a page telling them they can't do it twice.
2. If the participant started the experiment, but didn't complete it for some reason, they should be redirected to an error page and allow them to submit it anyway.

## Current Behavior

If the participant has already begun the experiment, Dallinger returns a status code 200 (https://github.com/Dallinger/Dallinger/blob/master/dallinger/custom.py#L379) rather than either an error or the participant json.

## Steps to Reproduce (for bugs)

1. Start the bartlett1932 experiment with `dallinger debug`.
2. Click through to "I'm done reading".
3. Close the popup window and click the "begin experiment" button again.
4. Click through the instructions. You will see that the experiment is broken now:
![image](https://cloud.githubusercontent.com/assets/83444/21792368/15ee8e56-d69e-11e6-98f5-79209ce46743.png)
5. If you check the javascript console, there will be a bunch of errors, the relevant one is the first one, which is where Dallinger has returned 200 but without the relevant participant json. This causes all the subsequent errors to occur:
![image](https://cloud.githubusercontent.com/assets/83444/21792380/32bd185e-d69e-11e6-97c3-48e87f385180.png)

## Your Environment

* Dallinger version used: master

**Comment by suchow** [comment]
Thanks for the report — it's a bug.

Note to future selves: expected behavior 1 can be accomplished by disabling the "Begin experiment" button after the first time it is clicked.

**Comment by thomasmorgan** [comment]
Is the begin experiment button still available after clicking when live? I thought MTurk made the contents of that frame change? But maybe not until they are ready to submit

**Comment by jessesnyder** [comment]
@suchow My PR addresses "expected behavior 1". I think some of the many changes I've made to support manual recruitment (story 73) may be relevant here, or at least affect the same code, so I wonder if we can defer "expected behavior 2" until that story is complete and merged?

**Comment by vlall** [comment]
This has been fixed- users now see an error page for both of these conditions.
