### ISSUE TITLE
Use javascript callbacks appropriately

### ISSUE THREAD

**Issue by jhamrick** [Dallinger/Dallinger#408]
## Current Behavior
In some of the javascript code, two asynchronous functions are called one after the other, e.g. https://github.com/Dallinger/Dallinger/blob/master/dallinger/frontend/static/scripts/dallinger.js#L109 :

```
submitResponses = function () {
    submitNextResponse(0);
    submitAssignment();
};
```

This is problematic because `submitAssignment` should only be called after `submitNextResponse` has successfully completed, but the way this code is written it is possible that the call to `submitAssignment` will happen before `submitNextResponse` has finished.

## Expected Behavior
The correct way to handle this type of scenario is to use callbacks, e.g.:

```
submitResponses = function () {
    submitNextResponse(0, submitAssignment);
};

submitNextResponse = function (n, callback) {
    ...
    reqwest({
        ...
        success: function() {
            if (n <= ids.length) {
                submitNextResponse(n + 1);
            } else {
                if (callback) callback();
            }
        },
        ...
    });
};
```

I haven't done a thorough audit of the javascript, so it's possible that it occurs in more places than just here, but I'm not sure.

**Comment by jessesnyder** [comment]
dallinger2.js now deals with sequential async calls correctly!
