### ISSUE TITLE
Four tests fail on every other run of tox

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#411]
Four tests are failing on `development` in tests/test_experiment_server.py:

1. `test_summary` 
2. `test_node_infos`
3. `test_node_vectors`
4. `test_participant_info`

All four tests include a call to `self._create_participant()` and, critically, fail on *every other* run of `tox`. This has been tested out to 12 repeated runs.

I have temporarily marked them with `@pytest.mark.xfail` so that the build runs.

**Comment by MatthewWilkes** [comment]
I suspect this may be to do with the pytest change, although I'm not sure why.  Happy to take a look.

**Comment by MatthewWilkes** [comment]
I'm not positive about this diagnostic, but I think something like this happened: 

1. The move to the dallinger config module caused the psiturk config object to not have some fields overridden by later config files.
2. That caused the value of `table_name` to stick to `turkdemo` as specified in `src/psiturk-dallinger/psiturk/local_config_defaults.txt`
3. The first test run would set up that table and use it fine
4. The following run would fail, and it would clean up that table (a guess)
5. The next run would be able to create it again, now it's been deleted, etc.

A small patch to psiturk would get this model to use the dallinger config object

```
diff --git a/psiturk/models.py b/psiturk/models.py
index 9e6057c..2b90b3c 100644
--- a/psiturk/models.py
+++ b/psiturk/models.py
@@ -4,19 +4,14 @@
 from sqlalchemy import Column, Integer, String, DateTime, Boolean, Float, Text
 
 from db import Base
-from psiturk_config import PsiturkConfig
+from dallinger.config import get_config
 
-config = PsiturkConfig()
-config.load_config()
-
-TABLENAME = config.get('Database Parameters', 'table_name')
-CODE_VERSION = config.get('Task Parameters', 'experiment_code_version')
 
 class Participant(Base):
     """
     Object representation of a participant in the database.
     """
-    __tablename__ = TABLENAME
+    __tablename__ = 'psiturk'
    
     uniqueid =Column(String(128), primary_key=True)
     assignmentid =Column(String(128), nullable=False)
@@ -41,7 +36,8 @@ def __init__(self, **kwargs):
         for key in kwargs:
             setattr(self, key, kwargs[key])
         self.status = 1
-        self.codeversion = CODE_VERSION
+        config = get_config()
+        self.codeversion = config.get('experiment_code_version')
         self.beginhit = datetime.datetime.now()
     
     def __repr__(self):
```

however I'm inclined to think that expected failure is a better representation of the fact that the failures are in code that we're intending to remove. Thoughts?

**Comment by davisagli** [comment]
The failing tests have been marked as expected failures on the development branch, and the stories/137-mturkrecruiter-dev-rebase fixes the problem (by no longer using the psiturk participant model). So I think this can be closed.

**Comment by suchow** [comment]
No longer a problem now that story 137 is merged.
