### ISSUE TITLE
Can't hibernate experiment

### ISSUE THREAD

**Issue by mongates** [Dallinger/Dallinger#421]
After running dallinger hibernate --app [appID], I get the following error and am unable to hibernate my experiment: 

<Error><Code>TooManyBuckets</Code><Message>You have attempted to create more buckets than allowed</Message><CurrentNumberOfBuckets>101</CurrentNumberOfBuckets><AllowedNumberOfBuckets>101</AllowedNumberOfBuckets><RequestId>D555B1F7B196CF38</RequestId><HostId>r5O+URiHMcMXTrqFbksxECDbe59sx17V//vGF5qbX+HacD24vDJmj9n29+RR+sSTPBa4oTRaIWc=</HostId></Error>

**Comment by suchow** [comment]
(Note to future self — store everything in a `dallinger` bucket, the limit on the number of files is >>> the limit on the number of buckets.)

**Comment by jhamrick** [comment]
Getting this error, too. (Probably because I bet @mongates and I are using the same account)

**Comment by jhamrick** [comment]
FYI, it seems that destroying the app using `dallinger destroy` doesn't remove any AWS buckets that are being used. I just tried destroying a few hibernated apps of mine in order to hopefully free up room to hibernate this new one, but no luck...
