### ISSUE TITLE
Flask --eager-loading option is no longer valid

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#4290]
The new[ish] `dallinger develop` system launches Flask with an `--eager-loading` flag. As of some recent version of Flask, this flag is not supported. Early experimentation suggests that it's perhaps not needed.

**Comment by pmcharrison** [comment]
Makes sense, reading the Flask GitHub discussions.

**Comment by pmcharrison** [comment]
I tried it out and it works for me as long as I upgrade Flask to the correct version; if I leave it at the old version, the app fails to launch, but this is OK I reckon.
