### ISSUE TITLE
Log warnings when configuration parameters are not registered

### ISSUE THREAD

**Issue by alecpm** [Dallinger/Dallinger#433]
## Expected Behavior
When a new configuration parameter is included in a config file, but not registered using the `extra_settings` hook, a warning should be logged.

## Current Behavior
Currently, if a new configuration parameter is added to a config file, but not registered the variable will not be included in the configuration and not be available to any experiments. Worse still, the parameter is ignored silently.

## Steps to Reproduce (for bugs)
1. Add a new parameter to an experiment configuration (e.g. `demos/bartlett1832/config.txt`)
2. Use the command line to run the experiment in debug mode.
3. Look at the snapshot `config.txt` for the experiment, the parameter will not have been included, and no warnings will have been logged regarding the unknown parameter.

## Context
Knowing why and when your custom experiment configuration parameters are not being incorporated into the running experiment configuration will be important to debugging issues related to experiment configuration.

## Your Environment
* Dallinger version used: `development` branch

**Comment by alecpm** [comment]
This should have been addressed with 4487830

**Comment by suchow** [comment]
Fixed the issue I saw above, so I believe this is now fixed.
