### ISSUE TITLE
Migrate default /develop directory to home directory: 5pts

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#4331]
`dallinger develop` currently collates the experiment files in the experiment directory, in a folder called `/develop`. This collated files include secret keys (e.g. AWS credentials), which seems dangerous as the user might accidentally commit these to Git. Proposal: to change the default location to the user's home directory, e.g. '~/.dallinger_develop'.

**Comment by jessesnyder** [comment]
@pmcharrison The first problem I'm running into (in general, I don't see many problems yet!) is that a hard-coded develop directory location makes testing hard. Running the tests will write to the same directory that you actually use during development, which is sub-optimal. This is actually the case currently also; not something that's introduced by this proposed change. 

I'm thinking to add an optional `--directory` arg to `dallinger develop bootstrap` and `dallinger develop run`, which would allow customization and support testing at the same time. Seem OK? I could probably also alter the way the tests work to avoid adding this user-facing change.

**Comment by pmcharrison** [comment]
Happy for this to be an optional argument, yes! Though it does mean the default behaviour is still risky for the reasons we discussed. You could make the default a temporary directory, and let it be customised via this suggested option?

**Comment by jessesnyder** [comment]
Related idea: could the directory be specified in `.dallingerconfig` instead of as a cli option, since you generally will come up with one location and stick with it? Tests could set the config value to a temp directory. The default value would be '~/.dallinger_develop` (the path would be represented as a string in the config file, which should work:
```
>>> Path(os.path.expanduser("~/.dallinger_develop"))
PosixPath('/Users/jesses/.dallinger_develop')
```

**Comment by pmcharrison** [comment]
Yes sounds good!

**Comment by jessesnyder** [comment]
Running into more the sort of snag I'd expected, but I'm hopeful that I'm just missing something obvious.

When I run `dallinger develop debug`, Flask fails to start:
```
$ dallinger develop debug

    ____        ____
   / __ \____ _/ / (_)___  ____ ____  _____
  / / / / __ `/ / / / __ \/ __ `/ _ \/ ___/
 / /_/ / /_/ / / / / / / / /_/ /  __/ /
/_____/\__,_/_/_/_/_/ /_/\__, /\___/_/
                        /____/
                                 v9.1.0a1

                Laboratory automation for
       the behavioral and social sciences.


❯❯ Preparing your pristine development environment...

❯❯ Checking your local Postgres database connection...

❯❯ Experiment UID: 913dc0d5-d96d-2645-80f5-678d823aaad1

❯❯ Wiping develop directory and re-writing it...
/Users/jesses/.dallinger_develop/constraints.txt
/Users/jesses/.dallinger_develop/models.py
/Users/jesses/.dallinger_develop/requirements.txt
/Users/jesses/.dallinger_develop/config.txt
/Users/jesses/.dallinger_develop/demo.ipynb
/Users/jesses/.dallinger_develop/__init__.py
/Users/jesses/.dallinger_develop/run.sh
/Users/jesses/.dallinger_develop/README.md
/Users/jesses/.dallinger_develop/experiment.py
/Users/jesses/.dallinger_develop/static
/Users/jesses/.dallinger_develop/app.py
/Users/jesses/.dallinger_develop/templates
/Users/jesses/.dallinger_develop/Procfile
/Users/jesses/.dallinger_develop/prepare_docker_image.sh

❯❯ Re-initializing database...

❯❯ Files symlinked in /Users/jesses/.dallinger_develop.
Run './run.sh' in that directory to start Flask, plus the worker and clock processes.
Firing up run.sh from: /Users/jesses/.dallinger_develop
Starting flask...
Remember to terminate this process with <control-c> before running 'dallinger bootstrap' again
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Could not import '.dallinger_develop.app'.
```

If I go to `~/.dallinger_develop` and run `./run.sh`, it works correctly:
```
 $ ./run.sh
Firing up run.sh from: /Users/jesses/.dallinger_develop
Starting flask...
Remember to terminate this process with <control-c> before running 'dallinger bootstrap' again
 * Serving Flask app "app.py" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 190-076-265
 ```

I'm flummoxed for the moment.

**Comment by jessesnyder** [comment]
The problem seems to have been the fact that the directory name has a leading `'.'`.  When I switched to `~/dallinger_develop`, Flask launched. The experiment in turn launched over and over again and iTerm asked for access to a bunch of things in my home directory, which is the next thing to figure out.
![global_config_defaults_txt_—_Dallinger3102](https://user-images.githubusercontent.com/63560/191863928-0cdf7a76-9242-4a54-b9b2-c32305c8a8f9.png)

**Comment by jessesnyder** [comment]
Repeated experiment loading was due to all the enqueued jobs which had piled up for each failed run. I've dealt with that by clearing the queue on failure.
