### ISSUE TITLE
psiTurk server failure: curl: (7) Failed to connect to 0.0.0.0 port 22362

### ISSUE THREAD

**Issue by Yuan-Meng** [Dallinger/Dallinger#484]
## Expected Behavior

First, I typed `heroku login` in Terminal and entered my credentials. Then, I set my working directory to where **bartlett1932** is and typed `dallinger debug`. I was supposed to see psiTurk server starting and could debug the experiment.
## Current Behavior

However, I encountered the error below:

`❯❯ Starting up the server...
curl: (7) Failed to connect to 0.0.0.0 port 22362: Connection refused`

I entered `server on` and then `debug`, but was told that:

`Error: Sorry, you need to have the server running to debug your experiment.  Try 'server on' first.`

I fiddled with a few things (and then back), but to no avail:
1. changed the port number in .dallingerconfig from  5000 to 22362 to match psiTurk's usual port number.

2. logged off from Heroku and logged in again.

I don't know if the problem is with any of the Dallinger files, or Heroku, or my network. When I switched to psiTurk and ran the psiTurk example (i.e. Stroop), I was able to turn on the server in the debug mode.

The reason why I want to use Dallinger is that I don't want to deal with the IP issue that psiTurk has. But now I wonder, does Dallinger have similar issues? Is there something that I should do in order to run experiments on my laptop?

Many thanks for your help!

## Your Environment

* Dallinger version used: 2.7.0
* Operating System: MacOS Sierra
* Wi-Fi: Airbears2 in Tolman Hall at UC Berkeley

**Comment by vlall** [comment]
This issue sounds like a local setup problem. Perhaps those local ports were already busy. Or perhaps there's a process hanging in the background. Since this was from over a year ago and it's not clear to me this is a dallinger issue I will close this.
