### ISSUE TITLE
Faulty logic for ending debugging on development branch

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#514]
On the `development` branch, the debugging session ends too early.

## Expected Behavior
The debugging session should end when a notification is received that the final participant has submitted the assignment.

## Current Behavior
The debugging session ends when recruitment is closed (i.e., the first time that a participant submits an assignment after all participants have been recruited, even if some participants are still participating.)

## Steps to Reproduce (for bugs)
1. Launch the chatroom demo with two participants.
2. Both participants enter the chatroom.
3. First participant leaves the chatroom and submits the assignment. 
4. Second participant tries to leave the chatroom and submit the assignment.

**Comment by alecpm** [comment]
This should be fixed on `bot_queue`
