### ISSUE TITLE
Allow Experiments to define custom WorkerEvents to run asynchronously

### ISSUE THREAD

**Issue by alecpm** [Dallinger/Dallinger#5407]
## Background

Dallinger provides the ability to run certain functions via an asynchronous worker function that pull tasks off of an `rq` job queue. This is a very powerful feature which could be useful for experiments in many contexts, but it's currently restricted to running tasks using a limited list of `WorkerEvent` sub-classes which are generally queued in response to a callback from a recruiter.

I think it could be very useful for Experiments to be able to register their own `WorkerEvent` classes and queue up asynchronous work as needed during the course of an experiment. Doing all work synchronously within the experiment methods is not always ideal, and providing a simple mechanism for offloading certain experiment tasks to be done asynchronously seems like it would be very useful.

In particular, I think that experiments which make use of WebSocket connections (see e.g. #5330) might find this useful.

## Current Behavior

Typical Dallinger experiments run multiple web application instances which handle browser requests to API routes that e.g. create `Info` obects. Experiments can also have multiple worker instances which handle processing async tasks using WorkerEvents. That allows for straightforward horizontal and vertical scaling (e.g. more servers or more CPUs allows you to run more application instances and workers).

In a WebSocket based Dallinger experiment, the primary communication between the server and client is via a persistent WebSocket connection to application instances. Those application instances push the WebSocket messages into a queue, where they can be forwarded and/or processed. Each web application instance runs a "Chat Backend" which relays messages from the queue to all connected clients based on the message "channels" to which the clients are subscribed. That allows for straightforward scaling of sending and receiving WebSocket messages, but messages generally also need to be processed by the experiment and that's where scaling becomes difficult.

When a WebSocket based experiment starts, its `/launch` route registers the experiment as a subscriber to a WebSocket channel and begins sending messages to the experiment for processing. Unfortunately, that processing all runs in a single application instance (the one that handled the `/launch` request). That means that the processing of incoming messages by the experiment is generally bound to a single CPU and cannot scale. Because the websocket messages are sent into a PubSub queue, having multiple experiment application instances handle incoming messages would result in duplicated work and would not improve scaling.

Providing an easy way for such experiments to delegate expensive processing to asynchronous worker functions would help alleviate this problem by allowing the message processing (e.g. things like writing data to the experiment database) to be performed by a worker instance which could be running on a separate CPU core or server.

## Proposed API

Instead of a fixed list of named `WorkerEvent` classes, I propose we provide a registry for named `WorkerEvents`. If an experiment wishes to hand off some processing to WorkerEvents it could do something like the following:

```
from dallinger.experiment import Experiment
from dallinger.experiment_server.worker_events import WorkerEvent, register_worker_event, worker_function

# Registration occurs class happens implicitly via a metaclass
class ProcessIncomingMessage(WorkerEvent):

    def __call__(self):
        # Do some work. Would currently have access to "participant", "assignment_id",
        # "experiment", "session", "config", "now" attributes. I propose extending the base class
        # to include "node", and "details" attributes already supported by "worker_function" for
        # "TrackingEvent".
        ...
        self.experiment.publish_to_subscribers(response_data, channel_id)


class MyExperiment(Experiment):
    ...
    def send(self, raw_message):
        "Send the message
        from dallinger.experiment_server.experiment_server import q
        ...
        q.enqueue(worker_function, "ProcessIncomingMessage", None,
                           participant_id=participant_id, node_id=node_id, details={"websocket_message": raw_message})
```

I recommend we customize `WorkerEvent` to automatically register sub-classes, and update `WorkerEvent.__init__` to add a couple of new optional keyword arguments to match those already in `worker_function`.

Perhaps the default implementation of the WebSocket `Experiment.send` message handler could use this sort of async message handling out of the box. Unfortunately, that would be backwards incompatible and might result in higher latency for small/simple experiments. However, since the WebSocket support has been broken for some time, maybe that's a worthwhile tradeoff.

This does not solve the problem of what happens when the application instance running an experiment's WebSocket listener thread is restarted, but it does allow already queued events to continue being processed by worker instances in such cases.

**Comment by ecl-ucb** [comment]
Does this improve upon/overlap conceptually with https://dallinger.readthedocs.io/en/latest/scheduled_tasks.html ?

**Comment by alecpm** [comment]
This has been implemented as part of the existing WebSockets PR, since it involves a re-implementation of the update WebSocket support for Experiments. See PR #5377.

**Comment by alecpm** [comment]
@ecl-ucb scheduled tasks run on a single server/application instance (the "Clock Server") and are intended for recurring timed tasks or tasks that need to be started when the clock server starts up. This is about generically being able to delegate work to an event handler that runs on worker applications of which there may be many spread across many servers. It's related in the sense that they both provide the ability to do work on processes of the web application instances, but this allows that work to be triggered in response to web (or websocket) requests by the web application instances.
