### ISSUE TITLE
Exclude repeat participants

### ISSUE THREAD

**Issue by mongates** [Dallinger/Dallinger#559]
Related to: https://github.com/Dallinger/Dallinger/issues/78

Work-in-progress code here: https://github.com/Dallinger/Dallinger/tree/exclude-duplicates

## Goals

Broadly, we want to be able to prevent participants from taking part in a group of related experiments more than once by creating a blacklist, replicating behavior from the website TurkGate (http://gideongoldin.github.com/TurkGate).

The experimenter can specify a group of experiments and when participants are recruited from Amazon Mechanical Turk, these participants can only participate a specified number of times (usually once) in any of the experiments in this group. 

Specifically, we would like any participant who accepts a HIT in a group to be excluded from any other experiments in the group, in that they do not see new experiments advertised. In MTurk terms: MTurk’s “Hit Visibility” should be “Hidden” to participants with specific MTurk worker ids. 

## Work Flow

Experimenters specify which experiments constitute a group by filling in the new `group_name` variable in config.txt. If experimenters do not specify a `group_name`, then `group_name` defaults to the experiment UUID. 

As soon as a participant becomes “Active” in an experiment, we assign their MTurk worker id a “qualification” online on the MTurk website, with the name specified by `qualification_type_id`, which is the `group_name`. 

In Dallinger, we describe a variable `blacklist`, which is the same as the “qualification_type_id” for the study. We then specify that in recruiting participants, MTurk workers must not have a qualification that is on the blacklist. We expect that this work flow lets us not advertise to participants who have already participated in a experiment within a group. 

## What is working: 

Dallinger is appropriately assigning qualifications to workers’ live MTurk accounts. 

## What is not working: 

Dallinger is not assigning qualifications to workers’ sandbox accounts. We moved the qualification assignment code from `command_line.py` into `recruiters.py` in the hopes of fixing this. Unfortunately, it still does not work -- running `dallinger sandbox` does not assign the `group_name` to the worker sandbox accounts.

Because Dallinger isn’t assigning qualifications to workers’ sandbox accounts, it’s hard to test if Dallinger is excluding participants appropriately (in that the new experiments do not appear for them).

## What is sort of working: 

There were many unicode errors that occurred. Fixes were put in place to make the code run. 

I personally was having trouble running Dallinger’s demos consistently to test this on my system; I assume that this is because the Dallinger version used here is several behind master. 

## Context

As an experimenter, I want to run large-scale experiments without recruiting the same participants over and over. Having too many repeaters invalidates the data.

**Comment by jessesnyder** [comment]
Closing. This is complete and was merged in May.
