### ISSUE TITLE
add data integrity check to mcmcp demo

### ISSUE THREAD

**Issue by jcpeterson** [Dallinger/Dallinger#577]
An error in getting a subject's final trial in the mcmcp demo can cause both infos to set chosen=False. The next subject then will not be able to extend the network because no previous chosen infos from the last subject's trial can be found. This will go on forever. The probability of it happening on any particular trial is empirically about 2% (n = 2 real experiments), which is not good for long chains.

One solution is to add this check:

```
    def data_check(self, participant):

        infos = participant.infos()

        return len([info for info in infos if info.chosen])*2 == len(infos)
```

**Comment by suchow** [comment]
Closed via #580.
