### ISSUE TITLE
Update README support section

### ISSUE THREAD

**Issue by fmhoeger** [Dallinger/Dallinger#5784]
Broken link to Google user group: https://groups.google.com/d/forum/dallinger in README:

If you are having issues, please [let us know](http://github.com/Dallinger/Dallinger/issues). We run a users group at https://groups.google.com/d/forum/dallinger.

**Comment by jacobyn** [comment]
I think this should refer to the new change you once made saying that you can get paid support which gives you access to the slack channel. Do we still have that? (Text by Tom Morgan, that I had sent you sometime ago).

**Comment by fmhoeger** [comment]
@jacobyn Yes, it was already merge here: https://github.com/Dallinger/Dallinger/pull/5551

Should the text in the green/yellow box be put into the README?

**Comment by jacobyn** [comment]
I think so. Thank you!
