### ISSUE TITLE
Specify Heroku runtime

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#624]
> Effective Tuesday, June 20th, 2017, new Python applications pushed to Heroku will use the python-3.6.1 runtime by default (instead of python-2.7.13).
> 
> Existing applications will not be affected by this change.
> 
> If you would like to specify Python 2.7, rather than using the new default, please refer to the Heroku Dev Center.
> 
> Many thanks,
> 
> The Heroku Python Team

**Comment by suchow** [comment]
https://devcenter.heroku.com/articles/python-runtimes#supported-python-runtimes

**Comment by vlall** [comment]
Fixed in releases 2.7.3 and 3.0.1
