### ISSUE TITLE
Demo "memoryexpt": participants stuck in waiting room

### ISSUE THREAD

**Issue by mongates** [Dallinger/Dallinger#660]
On the `memoryexpt2` branch, I'm running "memoryexpt" in debug mode. Participants can enter the waiting room, and the progress bar for each new participant is updated appropriately. However, the progress bars for each old participant are not updated. Thus, if there are four participants, the windows look like this once all of the participants have joined: 

Participant 1: progress bar stuck at 25%
Participant 2: progress bar stuck at 50%
Participant 3: progress bar stuck at 75%
Participant 4: experiment begins as expected. 

The desired behavior is that the progress bar will update for all participants as each participant is added. 

The `memoryexpt2` branch has been updated so that it reflects the most recent changes in `master`, and I am running Dallinger 3.3.0. To replicate this issue, checkout the `memoryexpt2` branch, then run `cd demos/memoryexpt`, then `dallinger debug`. 

Note that I wanted to test to see if the chatroom demo was working (previously when I was having this issue about updating the progress bars, the chatroom was working and my experiment (demos/memoryexpt) was not.) However, I'm having trouble running the demos/chatroom experiment on my system after the new update to the `master` branch. I'm getting this error: "Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

**Comment by jessesnyder** [comment]
@mongates The branch issues/660-memoryexp-stuck-waiting should fix this problem. I haven't dug too deeply into your waiting room implementation (in your demo), but I wonder if you need it at all. Could you just use the one provided by `dallinger`, as the chatroom demo does? If so, there is a bunch more stuff that could be deleted from your `experiment.js` file.

I frustrating aspect of testing: you'll need to refresh (or possibly hard-refresh) the consent page in order to get the updated JS.

**Comment by vlall** [comment]
Another note running the chatroom app, I had that same error and it turns out i had some extra worker processes still running. I ran `ps -ef | grep gunicorn` to check if the processes were there. Then i ran `pkill gunicorn` to shut them all down. This got rid of the ```Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.```
