### ISSUE TITLE
Function that takes {worker_ID} & {group_name} as input and assigns a qualification

### ISSUE THREAD

**Issue by mongates** [Dallinger/Dallinger#662]
It would be great if we could have a tool that, when given an MTurk ID and group_name, gives that participant the desired qualification on MTurk. It'd be great if this function call would be easily loopable, such that I could call it over and over for dozens of participants. This would allow retroactive post-experiment qualifications.

**Comment by jessesnyder** [comment]
@mongates We have this function, in the `MTurkService` class:
```
    def increment_qualification_score(self, name, worker_id, notify=False):
        """Increment the current qualification score for a worker, on a
        qualification with the provided name.
        """
```
If a worker doesn't currently have the qualification, they'll be assigned a value of 1. The only requirement for using this method is that a qualification with the provided name has to exist already. To create a new qualification by name, use `create_qualification_type`, in the same class:
```
    def create_qualification_type(self, name, description, status='Active'):
        """Create a new qualification Workers can be scored for.
        """
```

Is this enough for your needs, or did you want help creating a command-line tool? `dallinger qualify` is close, but it requires a qualification ID rather than a name.

**Comment by mongates** [comment]
@jessesnyder This doesn't work (I'm not importing / using MTurkService correctly) but something like this? 

************************************************************************************************

from dallinger.mturk import MTurkService

aws_access_key_id = ''
aws_secret_access_key = ''
conn = MTurkService(aws_access_key_id, aws_secret_access_key)

group_name = ''
description = ''

# if the qualification (group_name) doesn't exist, then create one
conn.create_qualification_type(group_name, description, status='Active')
"""Create a new qualification Workers can be scored for. """

list_of_ids = ['']
for worker_id in list_of_ids:
    # assign a qualification to the worker_id, if exist qualification type

   conn.increment_qualification_score(group_name, worker_id, notify=False)
   """Increment the current qualification score for a worker, on a
   qualification with the provided name."""

**Comment by jessesnyder** [comment]
Yep. Piggy-backing on your sketch:

```
from dallinger.mturk import MTurkService
from dallinger.mturk import DuplicateQualificationNameError

aws_access_key_id = ''
aws_secret_access_key = ''
conn = MTurkService(aws_access_key_id, aws_secret_access_key)

group_name = ''
description = ''
try:
    conn.create_qualification_type(group_name, description, status='Active')
except DuplicateQualificationNameError:
    pass  # we probably expect it to already exist, right?

list_of_ids = ['']
for worker_id in list_of_ids:
    result = conn.increment_qualification_score(group_name, worker_id)
    print result
```

**Comment by mongates** [comment]
Thanks! This almost works if I put this file in the /Dallinger folder. 

Problems:
1. It's defaulting to creating the qualification in sandbox? I don't know what settings I'm using...
2. If the qualification hasn't been created before, it creates it (I put a print statement in after `create_qualification_type`) but then it gives a QualificationNotFoundException error. If I run the script again then it does assign the qualification.

**Comment by jessesnyder** [comment]
1. To use the real MTurk, pass `sandbox=False` to the MTurkService constructor:
```
conn = MTurkService(aws_access_key_id, aws_secret_access_key, sandbox=False)
```

2. I forgot about that. After creating a new qualification type, it takes a while for the name to be indexed on MTurk. In the meantime, attempts to look up the qualification by name fail. Just running the script once to create the qualification, waiting 20-30 seconds, then running it again like you did is fine.

**Comment by mongates** [comment]
Thank you Jesse! This works :). Final script: 

```
from dallinger.mturk import MTurkService
from dallinger.mturk import DuplicateQualificationNameError

aws_access_key_id = ''
aws_secret_access_key = ''
conn = MTurkService(aws_access_key_id, aws_secret_access_key, sandbox=False)

group_name = ''

# if the qualification (group_name) doesn't exist, then create one
# note that this takes about 20-30 seconds
try:
	description = 'Participated in group ' + group_name
	conn.create_qualification_type(group_name, description, status='Active')
	print('created')
except DuplicateQualificationNameError:
    pass 

list_of_ids = ['']
# assign a qualification to the worker_id, if exist qualification type
for worker_id in list_of_ids:
   result = conn.increment_qualification_score(group_name, worker_id, notify=False)
   """Increment the current qualification score for a worker, on a
   qualification with the provided name."""
   print result

```
