### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#663]
Seeing this all the time:

```
Jul 06 17:59:12 dlgr-73d9cabf app/worker.1:  Traceback (most recent call last): 
Jul 06 17:59:12 dlgr-73d9cabf app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/dallinger/experiments/__init__.py", line 18, in <module> 
Jul 06 17:59:12 dlgr-73d9cabf app/worker.1:      globals()[entry_point.name] = entry_point.load() 
Jul 06 17:59:12 dlgr-73d9cabf app/worker.1:    File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2310, in load 
Jul 06 17:59:12 dlgr-73d9cabf app/worker.1:      return self.resolve() 
Jul 06 17:59:12 dlgr-73d9cabf app/worker.1:    File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2316, in resolve 
Jul 06 17:59:12 dlgr-73d9cabf app/worker.1:      module = __import__(self.module_name, fromlist=['__name__'], level=0) 
Jul 06 17:59:12 dlgr-73d9cabf app/worker.1:  ImportError: No module named bartlett1932.experiment 
```

**Comment by suchow** [comment]
To replicate this:

```
mkvirtualenv --python=/usr/bin/python2.7 dallinger-test-import-error
workon dallinger-test-import-error
pip install dallinger==3.3.0
dallinger --help
```

produces:

```
ERROR:dallinger.experiments:Could not import registered entry point Bartlett1932
Traceback (most recent call last):
  File "/Users/jordansuchow/.virtualenvs/dallinger-test10/lib/python2.7/site-packages/dallinger/experiments/__init__.py", line 18, in <module>
    globals()[entry_point.name] = entry_point.load()
  File "/Users/jordansuchow/.virtualenvs/dallinger-test10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/Users/jordansuchow/.virtualenvs/dallinger-test10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named bartlett1932.experiment
Usage: dallinger [OPTIONS] COMMAND [ARGS]...

  Dallinger command-line utility.

Options:
  -v, --version  Show the version and exit.
  -h, --help     Show this message and exit.

Commands:
  awaken     Restore the database from a given url.
  bot        Run the experiment bot.
  debug      Run the experiment locally.
  deploy     Deploy app using Heroku to MTurk.
  destroy    Tear down an experiment server.
  export     Export the data.
  hibernate  Pause an experiment and remove costly...
  load       Import database state from an exported zip...
  logs
  monitor    Set up application monitoring.
  qualify    Assign a qualification to a worker.
  rq_worker  Start an rq worker in the context of...
  sandbox    Deploy app using Heroku to the MTurk Sandbox.
  setup      Walk the user though the Dallinger setup.
  summary    Print a summary of a deployed app's status.
  uuid       Print a new UUID
  verify     Verify that app is compatible with Dallinger.
```

**Comment by suchow** [comment]
`git bisect` reveals that this began on commit ff9b4ed0b3979033a38a502d18d997be806f57af.

@cguardia @jessesnyder

**Comment by suchow** [comment]
Looking at this more closely, ff9b4ed0b3979033a38a502d18d997be806f57af is related to logging and so may be the first commit where the error message appears but not the first commit where the import error itself occurs.

**Comment by alecpm** [comment]
The primary issue here seems to be that doing a `pip install dallinger` doesn't install the demos anywhere, though the `setup.py` references `demos.bartlett1932` in an entry point. The simplest solution would be to remove that bartlett entry point from the dallinger `setup.py`. Alternatively, we could ensure that the demos are installed by default in a manner that allows the entry point to work.

Before the logging change the exception was just swallowed silently, but I'm not really happy with that logging config change in the context of a library module (`bots.py`). Log output should only be configured by the command line or experiment server applications, not at the library level. My guess is @cguardia added that to help debug an issue with bot running, but I'd prefer we revert https://github.com/Dallinger/Dallinger/commit/ff9b4ed0b3979033a38a502d18d997be806f57af as well.

**Comment by suchow** [comment]
If the Bartlett1932 entry point were removed, what would be the process for installing it?

**Comment by alecpm** [comment]
I think it would depend on how people typically install the demos after doing a `pip install.` We could make each demo an installable package following the GridUniverse model, or make a dallinger.demos package that adds entry points for all of them.

**Comment by alecpm** [comment]
To clarify the `demos` could live either within a standard `dallinger` install or we could release a separate `dlgr.demos` package that contains all the demos and registers them for use via the API.

**Comment by alecpm** [comment]
@suchow Do you have some preference about how we should release/provide the demo experiments given their new organization into a single `dlgr` namespaced package in the repo?
