### ISSUE TITLE
Tables display headers do not show on dashboard

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#6672]
Tables summary have heading that indicates the field that they are associated with it.
Somehow this does not show up:
For example in this image:
<img width="1530" alt="image" src="https://github.com/Dallinger/Dallinger/assets/10518584/4f332c5c-d0fd-4e6f-9165-1d590807e4bc">

It used to show titles with the field name, but it is not visible anymore.

**Comment by fmhoeger** [comment]
Fixed
![image](https://github.com/user-attachments/assets/a134c028-6896-437b-8dc5-5ba6324b76ae)
