### ISSUE TITLE
Dallinger upgrade fails because of enum type problem

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#6854]
# Symptoms

When upgrading to the latest Dallinger, I see this error:

```
Traceback (most recent call last):
  File "/Users/peter/.virtualenvs/psynet/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/Users/peter/.virtualenvs/psynet/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input value for enum participant_status: "recruiter_submission_started"
LINE 4: ...cipant.status = 'working' OR participant.status = 'recruiter...
```

# Diagnosis

I believe this is due to the introduction of the "recruiter_submission_started" enum type in #6183. It looks like `init_db(drop_all=True)` does not drop the pre-existing enum type for `participant.status`, and SQLAlchemy silently fails to add new values to this enum type.

@fmhoeger I am curious about whether you experienced the same problem?

I can manually fix this problem by running

```
dropdb dallinger
createdb -O dallinger dallinger
```

and we can instruct users to do this when upgrading Dallinger, but it is a bit awkward for the user. I wonder whether we can find an more streamlined way, for example updating `init_db(drop_all=True)` so that it treats enum values properly.

# Steps to reproduce

To reproduce the error, I do the following:

```
dropdb dallinger
createdb -O dallinger dallinger
git checkout v10.1.3
dallinger debug  # actually I have been doing psynet debug local but should be the same with dallinger
# CTRL-C to stop process
git checkout master
dallinger debug
# You need to start the experiment (creating a participant object) to see the error
```

**Comment by pmcharrison** [comment]
Fixed in #6860

**Comment by fmhoeger** [comment]
I could only reproduce this error with a PsyNet demo experiment (mcmcp). when I tried the same with the Dallinger bartlett demo I didn't get any error.

**Comment by pmcharrison** [comment]
Wow @fmhoeger, thank you for spotting that, I really should have noticed that myself. Turns out that PsyNet actually uses a different version of `init_db`, and that's where the problem was happening... Will close this MR now, see https://gitlab.com/PsyNetDev/PsyNet/-/merge_requests/729 for a much simpler PsyNet patch.
