### ISSUE TITLE
Add missing docs on installing demos

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#699]
<img width="1138" alt="screenshot 2017-08-14 19 40 39" src="https://user-images.githubusercontent.com/613981/29296487-a76ab262-8128-11e7-8adf-71e48b113fa1.png">

**Comment by jessesnyder** [comment]
Seems to me that if you're doing Dallinger development work, running a demo is a pretty fundamental activity, so maybe the setup guide is the right place (it's not only for running tests that this is useful).
