### ISSUE TITLE
Add `restart: always` to `docker-compose.yml`

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#7098]
Currently if you restart a server that is running Docker compose services for a given experiment, those services do not persist on server reboot. We think that it is best if these services do restart automatically. This can be done by adding `restart: unless-stopped` to the template `docker-compose.yml` files (see `docker-compose-server.yml`).

While doing this, we should also add `restart: unless-stopped` to the Dozzle service.

**Comment by polvanrijn** [comment]
@fmhoeger, I'll implement this quickly and you can review the PR, ok?

**Comment by pmcharrison** [comment]
Now done in #7104
