### ISSUE TITLE
User-modified settings in .dallingerconfig not saved

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#73]
Users have the option of including experiment configuration parameters in one of two locations: the experiment's `config.txt` or a global `.dallingerconfig` file. This separation has two benefits: (1) it allows keys for Heroku and other web services to be stored outside of the files that are packaged up in a zip file each time an experiment is run; and (2) it allows for default settings, such as the organization name, to be overwritten once instead of needing to rewrite it for each new experiment. However, `.dallingerconfig` is not saved. It should be, because the file can contain information relevant to the experiment and how it was run.

**Comment by suchow** [comment]
(However, access keys should not be saved.)

**Comment by suchow** [comment]
So pretty much the logic here is: in the snapshot, save all the local config variables that are actually going to be used, except access tokens.

**Comment by alecpm** [comment]
I believe once PR #389 is merged that all config variables will be saved into the experiment snapshot's config.txt. We should add some filtering to avoid saving passwords and/or secrets when writing out the file (we could probably just naively filter out any keys containing "secret", "password" or "token"). Doing that filtering will mean that we'll need to ensure that the server-side has access to such config secrets via environment variables when it needs them. Alternatively, we could include them in the config.txt that's run on the server-side, but filter and re-save the config.txt before creating the snapshot.

**Comment by alecpm** [comment]
Fixed on `development` in c1328f2
