### ISSUE TITLE
Use template inheritance for ad & consent pages

### ISSUE THREAD

**Issue by davisagli** [Dallinger/Dallinger#740]

**Comment by MatthewWilkes** [comment]
@davisagli Can you clarify this please? The templates already appears to inherit from layout.html, is this to make them inherit from a centralised ad.html and consent.html?

**Comment by davisagli** [comment]
That's right -- ad.html and consent.html are (almost?) identical between all the demo experiments, so we should just maintain one copy in dallinger/frontend/templates rather than a separate copy for each demo.

In the case of centralizing questionnaire.html (for which I already made a PR), @suchow wanted a way to override the template to add an additional question without duplicating the entire template, so I put a questionnaire.html in dallinger/frontend/templates/base which defines a block that can be filled, and a questionnaire.html in dallinger/frontend/templates which merely extends the base one without changing anything (to serve as the default for demos that don't provide their own questionnaire.html). Demos which want to add a question can provide a questionnaire.html that extends base/questionnaire.html and fills the `questions` block. I'm not sure if we need that complexity for these others or not.

**Comment by MatthewWilkes** [comment]
Great, thanks!

**Comment by suchow** [comment]
Just one more comment — these two templates are somewhat special in that they are nearly identical across all the demos (except for the particular experiment-specific line in the advertisement), but will almost always be modified by an experimenter running their own experiment (they'll have their own IRB-mandated consent-form language, for example). And so what we want is to cut down on repeated code across the demos, while still allowing experimenters to override the default language. Maybe there could be a section of the consent template with the consent-form text, and then the individual demos could inherit from that consent template and (optionally) overwrite that particular section with their own text.
