### ISSUE TITLE
Private browsing window

### ISSUE THREAD

**Issue by vlall** [Dallinger/Dallinger#767]
## Expected Behavior
An experiment should not use cached experiment files.

## Current Behavior
Experimenters run into an issue during development where the cache is not cleared before each run. They must manually do this, which sometimes also fails, or open a private browsing window.

The solution would be to use Selenium with proper private browsing flags, which is much more robust than the current Python `webbrowser` implementation.

**Comment by alecpm** [comment]
On a related note, when testing/debugging it can also be useful to disable mixed-content blocking (in Chrome this is done using `--allow-running-insecure-content`) this is essential when locally testing experiments like `dlgr.wikiresearch` which depend on loading experiment resources into an https site.

**Comment by MatthewWilkes** [comment]
To be clear, this is suggesting that the browser window opened as a convenience with `dallinger debug` should be replaced with (not headless) selenium session that doesn't attempt to control the browser directly?

**Comment by vlall** [comment]
Correct. So I think the main issue here is solving the fact that a pre-existing web browser profile is used with webbroswer. I looked at the Python documentation and didn't see anything that allowed us to clear the cache. So the Selenium profile is only one solution. If theres a solution that still uses webbrowser that should be fine too. The task should be changed to "Experimenters run into an issue during development where the cache is not cleared before each run. They must manually do this, which sometimes also fails, or open a private browsing window. This should be fixed", where using Selenium is one of multiple solutions.

**Comment by alecpm** [comment]
It would also be nice if for experiments that open multiple ad HIT urls for simultaneous users the opened browser windows each used different profiles (to ensure distinct cookies and local storage).
