### ISSUE TITLE
info_post() route function raises error on Bartlett1932 Demo

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#823]
## Expected Behavior
Included demos should run without error in debug mode

## Current Behavior
Submitting the answer to a question on Bartlett1932 raises an exception:
```
17:14:01 web.1      |  [2017-12-15 17:14:01,060] ERROR in app: Exception on /info/2 [POST]
17:14:01 web.1      |  Traceback (most recent call last):
17:14:01 web.1      |    File "/Users/jesses/.virtualenvs/dallinger2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
17:14:01 web.1      |      response = self.full_dispatch_request()
17:14:01 web.1      |    File "/Users/jesses/.virtualenvs/dallinger2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
17:14:01 web.1      |      rv = self.handle_user_exception(e)
17:14:01 web.1      |    File "/Users/jesses/.virtualenvs/dallinger2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
17:14:01 web.1      |      reraise(exc_type, exc_value, tb)
17:14:01 web.1      |    File "/Users/jesses/.virtualenvs/dallinger2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
17:14:01 web.1      |      rv = self.dispatch_request()
17:14:01 web.1      |    File "/Users/jesses/.virtualenvs/dallinger2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
17:14:01 web.1      |      return self.view_functions[rule.endpoint](**req.view_args)
17:14:01 web.1      |    File "/Users/jesses/.virtualenvs/dallinger2/lib/python2.7/site-packages/flask_crossdomain.py", line 31, in wrapped_function
17:14:01 web.1      |      resp = make_response(f(*args, **kwargs))
17:14:01 web.1      |    File "/Users/jesses/py_dev/Dallinger2/dallinger/experiment_server/experiment_server.py", line 1050, in info_post
17:14:01 web.1      |      details = loads(details)
17:14:01 web.1      |    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
17:14:01 web.1      |      return _default_decoder.decode(s)
17:14:01 web.1      |    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
17:14:01 web.1      |      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
17:14:01 web.1      |  TypeError: expected string or buffer
```

## Steps to Reproduce (for bugs)

1. Run `dallinger debug --verbose` from `demos/dlgr/demos/bartlett1932`
2. Click through initial pages
3. Submit some text on the page with the heading "Now reproduce the passage, verbatim:"
4. Check console output

## Your Environment

* Dallinger version used: master

## Notes
The route expects the `details` parameter to be present, but Bartlett1932 does not include this value when it calls `dallinger2.js.createInfo()` in its `experiment.js` file.

I'm unsure what should change here. Should the route accept posts without this value, or should clients always include it? If the latter, the route should check the return value of `request_parameter(parameter="details")` and raise an explicit error that way.

**Comment by jessesnyder** [comment]
@thomasmorgan I found this bug while starting work on another feature. I'm not sure where it crept in; I suspect with some recent JS refactoring. I could use some guidance on how this route should behave when the `details` key is omitted from the POST data. Hoping you have some familiarity with this(?)

**Comment by suchow** [comment]
@jessesnyder I'm pretty sure that the `details` column is specific to Griduniverse and not used elsewhere, and so perhaps this is a backwards incompatibility introduced by some changes made to support Griduniverse.

**Comment by thomasmorgan** [comment]
@jessesnyder I think Jordan is right. I have no familiarity with a details column and so it has likely been added for griduniverse. I am not sure exactly how griduniverse uses it, but the most obvious solution to me is to make it an optional argument. This should allow all the demos to work.

**Comment by alecpm** [comment]
It should definitely be optional on the route. The intent is to eventually replace the `propertyN` attributes with more flexible structured JSON data in the `details` column. Currently Griduniverse and the generic web tracking support make use of this column, but it's expected that other experiments will as well.
