### ISSUE TITLE
Reliable Docker support

### ISSUE THREAD

**Issue by vlall** [Dallinger/Dallinger#899]
Installation is difficult for experimenters and even developers. We already have a Docker image located here: https://hub.docker.com/r/dallinger/dallinger/. Our instructions to run that image is here: https://github.com/Dallinger/Dallinger/blob/6b1b4d73a512a11fbe8970d8a981e153bd8d8124/docs/source/docker_setup.rst

Docker support should be developed on, tested, and should be used as the preferred method of installation and running experiments for most experimenters. Docker can be downloaded in less than 5 minutes (https://docs.docker.com/docker-for-mac/install/#download-docker-for-mac), is a common standard among developers, and an image can be downloaded/run an experiment with 1 line of code each. Experimenters can even share their images via Dockerhub.

Automated tests should be included to make sure Docker images are compatible with new releases.

**Comment by witekdev** [comment]
Latest process here:
https://github.com/Dallinger/Dockerfiles/tree/stories/385-dockerfile-mac

**Comment by witekdev** [comment]
@vlall should this be closed?
