### ISSUE TITLE
dallinger2.js::ajax() behaves differently depending on browser

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#924]
`dallinger2.js::ajax()` behaves differently depending on browser (tested in Chrome vs. Firefox).

## Expected Behavior
Consistent behavior across major browsers

## Current Behavior
In Firefox, if client code called by `deferred.reject(err)` resets `window.location`, the remainder of `ajax()` is not executed, so the error page/form is not displayed. In Chrome, the function completes after the `deferred.reject(err)` call, and the error page is displayed, potentially in place of the intended page.

## Steps to Reproduce (for bugs)
1. Run Bartlett1932 in debug mode (`dallinger debug --verbose`)
2. Open /ad URL in Chrome
3. Click through and submit response when asked to reproduce text
4. You will see the error page instead of the questionnaire.

## Your Environment
* Dallinger version used: master branch
* Chrome 65.0.3325.181
* Firefox 58.0.2

## Recommendations
Perhaps the code to display the error page should be extracted from `ajax()`, and the client code should decide whether to call it from its own deferred.fail() handler.

**Comment by davisagli** [comment]
If I'm understanding correctly the problem here is that this experiment expects and handles an error response in order to know when it's time to go to the questionnaire, so does not want `ajax()` to do its own error handling. So I think we just need a way to turn off the error page redirect in selected cases like this one?

**Comment by jessesnyder** [comment]
That's the gist of it. One thought I had was to move most of the code from the body of `ajax()`'s error handler into a separate method on the `dlgr` object, leaving basically just the `deferred.reject(err)`. The client would then decide whether to call the new method when the deferred is rejected, from `deferred.fail()`. Moving more responsibility for error handling to the experiment has pros and cons of course.
