### ISSUE TITLE
Notes on Dallinger installation docs (and other docs too)

### ISSUE THREAD

**Issue by witekdev** [Dallinger/Dallinger#999]
Here are some notes on my getting bootstrapped process. Hopefully we can integrate these into the docs. Created an issue first to invite comments as to the best way to update the docs, after which I can create a PR.

This is feedback on http://docs.dallinger.io/en/latest/developing_dallinger_setup_guide.html

I'm on Ubuntu 16.04, using a relatively fresh VM, which means it is likely similar to someone out there who has not yet installed extra development libraries in the their system etc.

I installed python3.6 using the deadsnakes repo:
https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
as per https://askubuntu.com/questions/865554/how-do-i-install-python-3-6-using-apt-get
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.6
```

___

The following sections have been addressed and incorporated into https://github.com/Dallinger/Dallinger/pull/1110

~~~
**Notes on **Install Postgres** section:**

As I saw that _NB: If you have installed an older version of Postgres (e.g., < 10.3)_ was referring to version 10.3 as an old version and Ubuntu 16.04 comes with version 9.5, and I wasn't sure what is the minimum version I need to get dallinger working, I decided to get the latest version of Postgres 10 by following the instructions here: https://www.postgresql.org/download/linux/ubuntu/

* Create the file /etc/apt/sources.list.d/pgdg.list and add a line for the repository
deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
* Import the repository signing key, and update the package lists
```sudo apt-get update ```
* Ubuntu includes PostgreSQL by default. To install PostgreSQL on Ubuntu, use the apt-get (or other apt-driving) command:
``` sudo apt-get install postgresql-10 ```

Thinking back 9.5 would probably have been fine?? but this was not clear to me at the time.

After installing postgres, ``` Check using psql –version ``` does not work:
I got: 
```witek@ubuntu:~/dev/jazkarta/Dallinger$ psql
psql: FATAL: role "witek" does not exist
```
The solution from the Create the Databases section did not make sense to me, namely:
_If you get a fatal error that your ROLE does not exist, run these commands:
createuser dallinger
dropdb dallinger
createdb -O dallinger dallinger
createdb -O dallinger dallinger-import_

Seems the solution to the fatal role error is to create a user
``` sudo -u postgres createuser --superuser $USER ``` 
as per:  https://stackoverflow.com/questions/15301826/psql-fatal-role-postgres-does-not-exist/31712520#31712520

However this was not required for me to progess on as I manged to ```sudo -u postgres -i``` and use the postgres user to create the necessary user and databases.

At the end of the Install Postgres section:
_After that you’ll need to run the following commands_
```
runuser -l postgres -c "createuser -ds root"
createuser dallinger
createdb -O dallinger dallinger
sed /etc/postgresql/10.3/main/pg_hba.conf -e 's/md5/trust/g' --in-place
sed -e "s/[#]\?listen_addresses = .*/listen_addresses = '*'/g" -i '/etc/postgresql/10.3/main/postgresql.conf'
service postgresql reload
```
This is confusing to me, since it seems here we create the dallinger user and the dallinger database, then do some config adjustments, and the in the next section (Create the Databases) we tell the user to create the dallinger user again and the 2 databases?

Perhaps we can also update the Known Postgres Issues section here http://dallinger.readthedocs.io/en/latest/troubleshooting.html with regards what to do when one gets the fatal role error?
~~~

~~~
**Notes on **Set up a virtual environment** section:**

I found this section confusing. I did not use pip as I wasn't sure if I had to use pip3 or not? and if there would be issues later with some things installed via pip and others via pip3?? Not sure if that is a valid concern? Nevertheless, I recommend adding a Ubuntu specific mention to this section in the docs:
My process was the following: 
```
sudo aptitude install virtualenv virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
mkdir -p $WORKON_HOME
```
This line was not working in Ubuntu  ``` source $(which virtualenvwrapper.sh) ```
I had to find the location of virtualenvwrapper.sh manually:
``` sudo find / -name virtualenvwrapper.sh ```
which in my case turned out to be in: ``` /usr/share/virtualenvwrapper/virtualenvwrapper.sh ```

After which: ``` source /usr/share/virtualenvwrapper/virtualenvwrapper.sh ```

The rest of the steps worked fine:
```
clone Dallinger repo
mkvirtualenv Dallinger --python /usr/local/bin/python3.6
cd Dallinger
source bin/activate
```
~~~

~~~
**Notes on **Install prerequisites for building documentation** section:**

_To be able to build the documentation, you will need:_
It is not clear to me if this is an optional step or not? Will most users be building documentation during their interactions with dallinger, or is a special kind of user that will want to create documentation?

The link specified for the Enchant Library is bad as https://pythonhosted.org/pyenchant/download.html no longer exists? I found some information here instead: https://github.com/rfk/pyenchant

What was strange to me is that after running pip install -r dev-requirements.txt both import pyenchant and import pypandoc work inside of python3.6. Before pip install, they both returned ModuleNotFoundError.

**Update**: I propose removing this section entirely as all the requirements for creating documentations are included in the dev-requirements.txt file that is used for installing dallinger for developers.
~~~

~~~
**Notes on **Install Dallinger** section:**~~

I ran into an issue when running pip install -r dev-requirements.txt.
Namely I was missing python3.6 development files which I explicitly need to get:
``` sudo aptitude install python3.6-dev ```
Running ``` sudo apt-get install python3-dev ``` was not enough since ubuntu 16.04 comes with Python 3.5, it would get the development headers for Python 3.5 instead by default.
~~

**Comment by witekdev** [comment]
This is feedback on http://docs.dallinger.io/en/latest/aws_etc_keys.html

Regarding:  _Next, sign up for Heroku and install the Heroku toolbelt._

Looks like the Heroku Toolbelt is now legacy as per:
https://devcenter.heroku.com/articles/heroku-cli#troubleshooting

**Comment by witekdev** [comment]
This is feedback on http://docs.dallinger.io/en/latest/demoing_dallinger.html

This text is confusing:
_To test out Dallinger, we’ll run a demo experiment in debug mode. First download the Bartlett (1932) demo and unzip it. Then run Dallinger in debug mode from within that demo directory:_

Since what was required was to run ``` dallinger debug ``` from the /Dallinger/demos/dlgr/demos/bartlett1932$ directory

**Comment by witekdev** [comment]
If when exporting data from an experiment  you get:
`psycopg2.OperationalError: FATAL:  Peer authentication failed for user "dallinger"`

Make sure that you have the following in your `/etc/postgresql/10/main/pg_hba.conf` file
`local   all             all                                     trust`
instead of 
`local   all             all                                     peer`
which did not work

**Comment by witekdev** [comment]
http://docs.dallinger.io/en/latest/running_the_tests.html

Would perhaps be useful to add that one needs to install some additional packages for the test commands to be available. Namely: tox, pytest and mock

**Comment by alecpm** [comment]
* It's not clear to me that we should advise and/or document using a non-default python version on Linux (e.g. 3.6 on 16.04), since Dallinger supports both 2.7 and 3.x. I think that anyone who requires python 3.6 for some reason, but is stuck on an older Linux release, should probably be able to update their system python on their own.

2) We should definitely document the minimum PostgreSQL version required (I think 9.4.x for JSONB support).

3) I think anyone developing Dallinger (as opposed to making experiments with dallinger) should be updating documentation as they do so, so the documentation pre-requesities should be installed for anyone installing the dev requirements in my opinion.

**Comment by witekdev** [comment]
http://docs.dallinger.io/en/latest/communicating_with_the_server.html

The sentence in this paragraph is not clear to me, we should rewrite it for clarity:

"Routes are specific web addresses on the server that respond to requests from the front-end. Routes have direct access to the database, though most of the time they will pass requests to the experiment which will in turn access the database. **_As such, changing the behavior of the experiment is the easiest way to create a new experiment._** However it is also possible to change the behavior of the routes or add new routes entirely."

**Comment by jessesnyder** [comment]
> Why aren't the changes I'm making to some dallinger python file taking effect when I run an experiment??

Summary
---------
A common pitfall while doing development on the dallinger codebase while also working on external experiments which include dallinger as a dependency: you `pip install` a demo experiment in your active virtualenvironment, and it overwrites the `dallinger.egg-link` file in that environment's `site-packages` directory with an actual copy of the `dallinger` package.

Details
-------
When installing dallinger with the intent to work **on dallinger**, the recommended way to install dallinger itself is with pip's "editable mode", but passing the `-e` or `--editable` flag to pip install:
```
pip install -e .[data]
```
This creates a form of symbolic link in the active python's `site-packages` directory to the working copy of dallinger you're sitting in. This allows you to make changes to python files in the dallinger working copy and have them immediately active when using `dallinger` commands or any other actions that invoke the active python interpreter.

Running `pip install` *without* the `-e` flag while installing dallinger directly, or installing a separate experiment which includes dallinger as a dependency, will instead place a **copy** of the dallinger package in the `site-packages` directory. These files will then be executed when the active python is running, and any changes to your local working copy will be ignored.

You can check to see if you are working in "editable mode" by inspecting the contents of your active virtual environment's `site-packages` folder. In "editable mode", you will see a `dallinger.egg-link` file listed in the directory:
```
...
drwxr-xr-x    9 jesses  staff   306B May 29 12:30 coverage_pth-0.0.2.dist-info
-rw-r--r--    1 jesses  staff    44B May 29 12:30 coverage_pth.pth
-rw-r--r--    1 jesses  staff    33B Jun 14 16:08 dallinger.egg-link
drwxr-xr-x   21 jesses  staff   714B Mar 19 17:24 datashape
drwxr-xr-x   10 jesses  staff   340B Mar 19 17:24 datashape-0.5.2.dist-info
...
```
The contents of this file point will include the path to the working copy that's active:
```
/Users/jesses/py_dev/Dallinger3
.
```
If you instead see a directory tree with actual dallinger files, you can restore "editable mode" by re-running the installation steps for dallinger from the "Developer Installation" documentation.

**Comment by vlall** [comment]
I still need to test the Mac installation process, however, the instructions @witekdev made are merged.

**Comment by witekdev** [comment]
@vlall there are still notes here that have not made it into any docs.
Should we keep this issue open or open another?
